//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class AdminTaskDefinitions : XPLiteObject
    {
        int fAdminTaskID;
        [Key(true)]
        public int AdminTaskID
        {
            get { return fAdminTaskID; }
            set { SetPropertyValue<int>("AdminTaskID", ref fAdminTaskID, value); }
        }
        string fTaskName;
        [Indexed(Name = @"IX_Taskname", Unique = true)]
        [Size(50)]
        public string TaskName
        {
            get { return fTaskName; }
            set { SetPropertyValue<string>("TaskName", ref fTaskName, value); }
        }
        string fTaskDescription;
        [Size(254)]
        public string TaskDescription
        {
            get { return fTaskDescription; }
            set { SetPropertyValue<string>("TaskDescription", ref fTaskDescription, value); }
        }
        MPetUsers fModifedBy;
        [Association(@"AdminTaskDefinitionsReferencesMPetUsers")]
        public MPetUsers ModifedBy
        {
            get { return fModifedBy; }
            set { SetPropertyValue<MPetUsers>("ModifedBy", ref fModifedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        [Association(@"TemplateTasksReferencesAdminTaskDefinitions", typeof(TemplateTasks))]
        public XPCollection<TemplateTasks> TemplateTasksCollection { get { return GetCollection<TemplateTasks>("TemplateTasksCollection"); } }
    }

}
