//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Attachments : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        Jobs fnJobID;
        [Association(@"AttachmentsReferencesJobs")]
        public Jobs nJobID
        {
            get { return fnJobID; }
            set { SetPropertyValue<Jobs>("nJobID", ref fnJobID, value); }
        }
        Jobsteps fnJobstepID;
        [Association(@"AttachmentsReferencesJobsteps")]
        public Jobsteps nJobstepID
        {
            get { return fnJobstepID; }
            set { SetPropertyValue<Jobsteps>("nJobstepID", ref fnJobstepID, value); }
        }
        string fDocType;
        [Size(10)]
        public string DocType
        {
            get { return fDocType; }
            set { SetPropertyValue<string>("DocType", ref fDocType, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fLocationOrURL;
        [Size(2304)]
        public string LocationOrURL
        {
            get { return fLocationOrURL; }
            set { SetPropertyValue<string>("LocationOrURL", ref fLocationOrURL, value); }
        }
        Tasks fn_TaskID;
        [Association(@"AttachmentsReferencesTasks")]
        public Tasks n_TaskID
        {
            get { return fn_TaskID; }
            set { SetPropertyValue<Tasks>("n_TaskID", ref fn_TaskID, value); }
        }
        Masterparts fn_MasterpartID;
        [Association(@"AttachmentsReferencesMasterparts")]
        public Masterparts n_MasterpartID
        {
            get { return fn_MasterpartID; }
            set { SetPropertyValue<Masterparts>("n_MasterpartID", ref fn_MasterpartID, value); }
        }
        MaintenanceObjects fn_MaintObjectID;
        [Association(@"AttachmentsReferencesMaintenanceObjects")]
        public MaintenanceObjects n_MaintObjectID
        {
            get { return fn_MaintObjectID; }
            set { SetPropertyValue<MaintenanceObjects>("n_MaintObjectID", ref fn_MaintObjectID, value); }
        }
        string fShortName;
        [Size(20)]
        public string ShortName
        {
            get { return fShortName; }
            set { SetPropertyValue<string>("ShortName", ref fShortName, value); }
        }
        string fAssignedGuid;
        [Size(36)]
        public string AssignedGuid
        {
            get { return fAssignedGuid; }
            set { SetPropertyValue<string>("AssignedGuid", ref fAssignedGuid, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"AttachmentsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedDate;
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>("CreatedDate", ref fCreatedDate, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"AttachmentsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        int fn_storesissueid;
        public int n_storesissueid
        {
            get { return fn_storesissueid; }
            set { SetPropertyValue<int>("n_storesissueid", ref fn_storesissueid, value); }
        }
        int fn_grieflogid;
        public int n_grieflogid
        {
            get { return fn_grieflogid; }
            set { SetPropertyValue<int>("n_grieflogid", ref fn_grieflogid, value); }
        }
        int fn_shippingreportid;
        public int n_shippingreportid
        {
            get { return fn_shippingreportid; }
            set { SetPropertyValue<int>("n_shippingreportid", ref fn_shippingreportid, value); }
        }
        int fn_IncidentLogID;
        public int n_IncidentLogID
        {
            get { return fn_IncidentLogID; }
            set { SetPropertyValue<int>("n_IncidentLogID", ref fn_IncidentLogID, value); }
        }
        int fn_TimeBatchID;
        public int n_TimeBatchID
        {
            get { return fn_TimeBatchID; }
            set { SetPropertyValue<int>("n_TimeBatchID", ref fn_TimeBatchID, value); }
        }
        int fn_UserID;
        public int n_UserID
        {
            get { return fn_UserID; }
            set { SetPropertyValue<int>("n_UserID", ref fn_UserID, value); }
        }
        int fn_CheckInID;
        public int n_CheckInID
        {
            get { return fn_CheckInID; }
            set { SetPropertyValue<int>("n_CheckInID", ref fn_CheckInID, value); }
        }
        int fn_CheckOutID;
        public int n_CheckOutID
        {
            get { return fn_CheckOutID; }
            set { SetPropertyValue<int>("n_CheckOutID", ref fn_CheckOutID, value); }
        }
        int fn_ReceiptID;
        public int n_ReceiptID
        {
            get { return fn_ReceiptID; }
            set { SetPropertyValue<int>("n_ReceiptID", ref fn_ReceiptID, value); }
        }
    }

}
