//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class BaseTableList : XPLiteObject
    {
        int fBaseTableID;
        [Key(true)]
        public int BaseTableID
        {
            get { return fBaseTableID; }
            set { SetPropertyValue<int>("BaseTableID", ref fBaseTableID, value); }
        }
        string fBaseTableName;
        [Indexed(Name = @"IX_BaseTableList", Unique = true)]
        [Size(50)]
        public string BaseTableName
        {
            get { return fBaseTableName; }
            set { SetPropertyValue<string>("BaseTableName", ref fBaseTableName, value); }
        }
        string fBaseTableDesc;
        [Size(254)]
        public string BaseTableDesc
        {
            get { return fBaseTableDesc; }
            set { SetPropertyValue<string>("BaseTableDesc", ref fBaseTableDesc, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"BaseTableListReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"BaseTableListReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        [Association(@"TemplateBaseTablesReferencesBaseTableList", typeof(TemplateBaseTables))]
        public XPCollection<TemplateBaseTables> TemplateBaseTablesCollection { get { return GetCollection<TemplateBaseTables>("TemplateBaseTablesCollection"); } }
    }

}
