//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class CycleCounts : XPLiteObject
    {
        PartsAtLocation fn_PartAtLocID;
        [Association(@"CycleCountsReferencesPartsAtLocation")]
        public PartsAtLocation n_PartAtLocID
        {
            get { return fn_PartAtLocID; }
            set { SetPropertyValue<PartsAtLocation>("n_PartAtLocID", ref fn_PartAtLocID, value); }
        }
        Masterparts fn_MasterPartID;
        [Association(@"CycleCountsReferencesMasterparts")]
        public Masterparts n_MasterPartID
        {
            get { return fn_MasterPartID; }
            set { SetPropertyValue<Masterparts>("n_MasterPartID", ref fn_MasterPartID, value); }
        }
        MfgParts fn_MFGPartID;
        [Association(@"CycleCountsReferencesMfgParts")]
        public MfgParts n_MFGPartID
        {
            get { return fn_MFGPartID; }
            set { SetPropertyValue<MfgParts>("n_MFGPartID", ref fn_MFGPartID, value); }
        }
        Manufacturers fn_MFGID;
        [Association(@"CycleCountsReferencesManufacturers")]
        public Manufacturers n_MFGID
        {
            get { return fn_MFGID; }
            set { SetPropertyValue<Manufacturers>("n_MFGID", ref fn_MFGID, value); }
        }
        int fQtyOfRecord;
        public int QtyOfRecord
        {
            get { return fQtyOfRecord; }
            set { SetPropertyValue<int>("QtyOfRecord", ref fQtyOfRecord, value); }
        }
        int fFirstCountQty;
        public int FirstCountQty
        {
            get { return fFirstCountQty; }
            set { SetPropertyValue<int>("FirstCountQty", ref fFirstCountQty, value); }
        }
        int fSecondCountQty;
        public int SecondCountQty
        {
            get { return fSecondCountQty; }
            set { SetPropertyValue<int>("SecondCountQty", ref fSecondCountQty, value); }
        }
        int fFirstVariance;
        public int FirstVariance
        {
            get { return fFirstVariance; }
            set { SetPropertyValue<int>("FirstVariance", ref fFirstVariance, value); }
        }
        int fSecondVariance;
        public int SecondVariance
        {
            get { return fSecondVariance; }
            set { SetPropertyValue<int>("SecondVariance", ref fSecondVariance, value); }
        }
        string fStatusFlag;
        [Size(25)]
        public string StatusFlag
        {
            get { return fStatusFlag; }
            set { SetPropertyValue<string>("StatusFlag", ref fStatusFlag, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"CycleCountsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"CycleCountsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
    }

}
