//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class EmailNotifications : XPLiteObject
    {
        int fPKID;
        [Key(true)]
        public int PKID
        {
            get { return fPKID; }
            set { SetPropertyValue<int>("PKID", ref fPKID, value); }
        }
        MPetUsers fUserID;
        [Association(@"EmailNotificationsReferencesMPetUsers")]
        public MPetUsers UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<MPetUsers>("UserID", ref fUserID, value); }
        }
        int fEmailID;
        public int EmailID
        {
            get { return fEmailID; }
            set { SetPropertyValue<int>("EmailID", ref fEmailID, value); }
        }
        EmailNotificationTypes fEmailNotificationID;
        [Association(@"EmailNotificationsReferencesEmailNotificationTypes")]
        public EmailNotificationTypes EmailNotificationID
        {
            get { return fEmailNotificationID; }
            set { SetPropertyValue<EmailNotificationTypes>("EmailNotificationID", ref fEmailNotificationID, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"EmailNotificationsReferencesMPetUsers1")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"EmailNotificationsReferencesMPetUsers2")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
    }

}
