//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class EquipmentNumber : XPLiteObject
    {
        int fn_EquipmentNumberID;
        [Key(true)]
        public int n_EquipmentNumberID
        {
            get { return fn_EquipmentNumberID; }
            set { SetPropertyValue<int>("n_EquipmentNumberID", ref fn_EquipmentNumberID, value); }
        }
        string fEquipmentNumberID;
        [Size(30)]
        public string EquipmentNumberID
        {
            get { return fEquipmentNumberID; }
            set { SetPropertyValue<string>("EquipmentNumberID", ref fEquipmentNumberID, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"EquipmentNumberReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"EquipmentNumberReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        [Association(@"FieldDataCollectionReferencesEquipmentNumber", typeof(FieldDataCollection))]
        public XPCollection<FieldDataCollection> FieldDataCollections { get { return GetCollection<FieldDataCollection>("FieldDataCollections"); } }
        [Association(@"IncidentsReferencesEquipmentNumber", typeof(Incidents))]
        public XPCollection<Incidents> IncidentsCollection { get { return GetCollection<Incidents>("IncidentsCollection"); } }
        [Association(@"JobPartsReferencesEquipmentNumber", typeof(JobParts))]
        public XPCollection<JobParts> JobPartsCollection { get { return GetCollection<JobParts>("JobPartsCollection"); } }
        [Association(@"JobsReferencesEquipmentNumber", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection { get { return GetCollection<Jobs>("JobsCollection"); } }
        [Association(@"JobstepsReferencesEquipmentNumber", typeof(Jobsteps))]
        public XPCollection<Jobsteps> JobstepsCollection { get { return GetCollection<Jobsteps>("JobstepsCollection"); } }
        [Association(@"MaintenanceObjectsReferencesEquipmentNumber", typeof(MaintenanceObjects))]
        public XPCollection<MaintenanceObjects> MaintenanceObjectsCollection { get { return GetCollection<MaintenanceObjects>("MaintenanceObjectsCollection"); } }
        [Association(@"requisitionsReferencesEquipmentNumber", typeof(requisitions))]
        public XPCollection<requisitions> requisitionsCollection { get { return GetCollection<requisitions>("requisitionsCollection"); } }
        [Association(@"StoresIssuesReferencesEquipmentNumber", typeof(StoresIssues))]
        public XPCollection<StoresIssues> StoresIssuesCollection { get { return GetCollection<StoresIssues>("StoresIssuesCollection"); } }
        [Association(@"time_batch_itemsReferencesEquipmentNumber", typeof(time_batch_items))]
        public XPCollection<time_batch_items> time_batch_itemss { get { return GetCollection<time_batch_items>("time_batch_itemss"); } }
    }

}
