//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class F4301Z1 : XPLiteObject
    {
        string fSYEDCT;
        [Size(2)]
        public string SYEDCT
        {
            get { return fSYEDCT; }
            set { SetPropertyValue<string>("SYEDCT", ref fSYEDCT, value); }
        }
        string fSYTYTN;
        [Size(8)]
        public string SYTYTN
        {
            get { return fSYTYTN; }
            set { SetPropertyValue<string>("SYTYTN", ref fSYTYTN, value); }
        }
        string fSYEDFT;
        [Size(10)]
        public string SYEDFT
        {
            get { return fSYEDFT; }
            set { SetPropertyValue<string>("SYEDFT", ref fSYEDFT, value); }
        }
        decimal fSYEDDT;
        public decimal SYEDDT
        {
            get { return fSYEDDT; }
            set { SetPropertyValue<decimal>("SYEDDT", ref fSYEDDT, value); }
        }
        char fSYDRIN;
        public char SYDRIN
        {
            get { return fSYDRIN; }
            set { SetPropertyValue<char>("SYDRIN", ref fSYDRIN, value); }
        }
        double fSYEDDL;
        public double SYEDDL
        {
            get { return fSYEDDL; }
            set { SetPropertyValue<double>("SYEDDL", ref fSYEDDL, value); }
        }
        char fSYEDSP;
        public char SYEDSP
        {
            get { return fSYEDSP; }
            set { SetPropertyValue<char>("SYEDSP", ref fSYEDSP, value); }
        }
        string fSYPNID;
        [Size(15)]
        public string SYPNID
        {
            get { return fSYPNID; }
            set { SetPropertyValue<string>("SYPNID", ref fSYPNID, value); }
        }
        string fSYTNAC;
        [Size(2)]
        public string SYTNAC
        {
            get { return fSYTNAC; }
            set { SetPropertyValue<string>("SYTNAC", ref fSYTNAC, value); }
        }
        string fSYKCOO;
        [Size(5)]
        public string SYKCOO
        {
            get { return fSYKCOO; }
            set { SetPropertyValue<string>("SYKCOO", ref fSYKCOO, value); }
        }
        double fSYDOCO;
        public double SYDOCO
        {
            get { return fSYDOCO; }
            set { SetPropertyValue<double>("SYDOCO", ref fSYDOCO, value); }
        }
        string fSYDCTO;
        [Size(2)]
        public string SYDCTO
        {
            get { return fSYDCTO; }
            set { SetPropertyValue<string>("SYDCTO", ref fSYDCTO, value); }
        }
        string fSYSFXO;
        [Size(3)]
        public string SYSFXO
        {
            get { return fSYSFXO; }
            set { SetPropertyValue<string>("SYSFXO", ref fSYSFXO, value); }
        }
        string fSYMCU;
        [Size(12)]
        public string SYMCU
        {
            get { return fSYMCU; }
            set { SetPropertyValue<string>("SYMCU", ref fSYMCU, value); }
        }
        string fSYOKCO;
        [Size(5)]
        public string SYOKCO
        {
            get { return fSYOKCO; }
            set { SetPropertyValue<string>("SYOKCO", ref fSYOKCO, value); }
        }
        string fSYOORN;
        [Size(8)]
        public string SYOORN
        {
            get { return fSYOORN; }
            set { SetPropertyValue<string>("SYOORN", ref fSYOORN, value); }
        }
        string fSYOCTO;
        [Size(2)]
        public string SYOCTO
        {
            get { return fSYOCTO; }
            set { SetPropertyValue<string>("SYOCTO", ref fSYOCTO, value); }
        }
        string fSYRKCO;
        [Size(5)]
        public string SYRKCO
        {
            get { return fSYRKCO; }
            set { SetPropertyValue<string>("SYRKCO", ref fSYRKCO, value); }
        }
        string fSYRORN;
        [Size(8)]
        public string SYRORN
        {
            get { return fSYRORN; }
            set { SetPropertyValue<string>("SYRORN", ref fSYRORN, value); }
        }
        string fSYRCTO;
        [Size(2)]
        public string SYRCTO
        {
            get { return fSYRCTO; }
            set { SetPropertyValue<string>("SYRCTO", ref fSYRCTO, value); }
        }
        double fSYAN8;
        public double SYAN8
        {
            get { return fSYAN8; }
            set { SetPropertyValue<double>("SYAN8", ref fSYAN8, value); }
        }
        double fSYSHAN;
        public double SYSHAN
        {
            get { return fSYSHAN; }
            set { SetPropertyValue<double>("SYSHAN", ref fSYSHAN, value); }
        }
        decimal fSYDRQJ;
        public decimal SYDRQJ
        {
            get { return fSYDRQJ; }
            set { SetPropertyValue<decimal>("SYDRQJ", ref fSYDRQJ, value); }
        }
        decimal fSYTRDJ;
        public decimal SYTRDJ
        {
            get { return fSYTRDJ; }
            set { SetPropertyValue<decimal>("SYTRDJ", ref fSYTRDJ, value); }
        }
        decimal fSYPDDJ;
        public decimal SYPDDJ
        {
            get { return fSYPDDJ; }
            set { SetPropertyValue<decimal>("SYPDDJ", ref fSYPDDJ, value); }
        }
        decimal fSYOPDJ;
        public decimal SYOPDJ
        {
            get { return fSYOPDJ; }
            set { SetPropertyValue<decimal>("SYOPDJ", ref fSYOPDJ, value); }
        }
        decimal fSYADDJ;
        public decimal SYADDJ
        {
            get { return fSYADDJ; }
            set { SetPropertyValue<decimal>("SYADDJ", ref fSYADDJ, value); }
        }
        decimal fSYCNDJ;
        public decimal SYCNDJ
        {
            get { return fSYCNDJ; }
            set { SetPropertyValue<decimal>("SYCNDJ", ref fSYCNDJ, value); }
        }
        decimal fSYPEFJ;
        public decimal SYPEFJ
        {
            get { return fSYPEFJ; }
            set { SetPropertyValue<decimal>("SYPEFJ", ref fSYPEFJ, value); }
        }
        decimal fSYPPDJ;
        public decimal SYPPDJ
        {
            get { return fSYPPDJ; }
            set { SetPropertyValue<decimal>("SYPPDJ", ref fSYPPDJ, value); }
        }
        decimal fSYPSDJ;
        public decimal SYPSDJ
        {
            get { return fSYPSDJ; }
            set { SetPropertyValue<decimal>("SYPSDJ", ref fSYPSDJ, value); }
        }
        string fSYVR01;
        [Size(25)]
        public string SYVR01
        {
            get { return fSYVR01; }
            set { SetPropertyValue<string>("SYVR01", ref fSYVR01, value); }
        }
        string fSYVR02;
        [Size(25)]
        public string SYVR02
        {
            get { return fSYVR02; }
            set { SetPropertyValue<string>("SYVR02", ref fSYVR02, value); }
        }
        string fSYDEL1;
        [Size(30)]
        public string SYDEL1
        {
            get { return fSYDEL1; }
            set { SetPropertyValue<string>("SYDEL1", ref fSYDEL1, value); }
        }
        string fSYDEL2;
        [Size(30)]
        public string SYDEL2
        {
            get { return fSYDEL2; }
            set { SetPropertyValue<string>("SYDEL2", ref fSYDEL2, value); }
        }
        string fSYRMK;
        [Size(30)]
        public string SYRMK
        {
            get { return fSYRMK; }
            set { SetPropertyValue<string>("SYRMK", ref fSYRMK, value); }
        }
        string fSYDESC;
        [Size(30)]
        public string SYDESC
        {
            get { return fSYDESC; }
            set { SetPropertyValue<string>("SYDESC", ref fSYDESC, value); }
        }
        string fSYINMG;
        [Size(10)]
        public string SYINMG
        {
            get { return fSYINMG; }
            set { SetPropertyValue<string>("SYINMG", ref fSYINMG, value); }
        }
        string fSYASN;
        [Size(8)]
        public string SYASN
        {
            get { return fSYASN; }
            set { SetPropertyValue<string>("SYASN", ref fSYASN, value); }
        }
        string fSYPRGP;
        [Size(8)]
        public string SYPRGP
        {
            get { return fSYPRGP; }
            set { SetPropertyValue<string>("SYPRGP", ref fSYPRGP, value); }
        }
        string fSYPTC;
        [Size(3)]
        public string SYPTC
        {
            get { return fSYPTC; }
            set { SetPropertyValue<string>("SYPTC", ref fSYPTC, value); }
        }
        string fSYEXR1;
        [Size(2)]
        public string SYEXR1
        {
            get { return fSYEXR1; }
            set { SetPropertyValue<string>("SYEXR1", ref fSYEXR1, value); }
        }
        string fSYTXA1;
        [Size(10)]
        public string SYTXA1
        {
            get { return fSYTXA1; }
            set { SetPropertyValue<string>("SYTXA1", ref fSYTXA1, value); }
        }
        string fSYTXCT;
        [Size(20)]
        public string SYTXCT
        {
            get { return fSYTXCT; }
            set { SetPropertyValue<string>("SYTXCT", ref fSYTXCT, value); }
        }
        string fSYHOLD;
        [Size(2)]
        public string SYHOLD
        {
            get { return fSYHOLD; }
            set { SetPropertyValue<string>("SYHOLD", ref fSYHOLD, value); }
        }
        char fSYATXT;
        public char SYATXT
        {
            get { return fSYATXT; }
            set { SetPropertyValue<char>("SYATXT", ref fSYATXT, value); }
        }
        double fSYINVC;
        public double SYINVC
        {
            get { return fSYINVC; }
            set { SetPropertyValue<double>("SYINVC", ref fSYINVC, value); }
        }
        string fSYNTR;
        [Size(2)]
        public string SYNTR
        {
            get { return fSYNTR; }
            set { SetPropertyValue<string>("SYNTR", ref fSYNTR, value); }
        }
        string fSYCNID;
        [Size(20)]
        public string SYCNID
        {
            get { return fSYCNID; }
            set { SetPropertyValue<string>("SYCNID", ref fSYCNID, value); }
        }
        string fSYFRTH;
        [Size(3)]
        public string SYFRTH
        {
            get { return fSYFRTH; }
            set { SetPropertyValue<string>("SYFRTH", ref fSYFRTH, value); }
        }
        string fSYZON;
        [Size(3)]
        public string SYZON
        {
            get { return fSYZON; }
            set { SetPropertyValue<string>("SYZON", ref fSYZON, value); }
        }
        double fSYANBY;
        public double SYANBY
        {
            get { return fSYANBY; }
            set { SetPropertyValue<double>("SYANBY", ref fSYANBY, value); }
        }
        double fSYANCR;
        public double SYANCR
        {
            get { return fSYANCR; }
            set { SetPropertyValue<double>("SYANCR", ref fSYANCR, value); }
        }
        string fSYMOT;
        [Size(3)]
        public string SYMOT
        {
            get { return fSYMOT; }
            set { SetPropertyValue<string>("SYMOT", ref fSYMOT, value); }
        }
        string fSYCOT;
        [Size(3)]
        public string SYCOT
        {
            get { return fSYCOT; }
            set { SetPropertyValue<string>("SYCOT", ref fSYCOT, value); }
        }
        string fSYRCD;
        [Size(3)]
        public string SYRCD
        {
            get { return fSYRCD; }
            set { SetPropertyValue<string>("SYRCD", ref fSYRCD, value); }
        }
        char fSYFRTC;
        public char SYFRTC
        {
            get { return fSYFRTC; }
            set { SetPropertyValue<char>("SYFRTC", ref fSYFRTC, value); }
        }
        char fSYFUF1;
        public char SYFUF1
        {
            get { return fSYFUF1; }
            set { SetPropertyValue<char>("SYFUF1", ref fSYFUF1, value); }
        }
        char fSYFUF2;
        public char SYFUF2
        {
            get { return fSYFUF2; }
            set { SetPropertyValue<char>("SYFUF2", ref fSYFUF2, value); }
        }
        double fSYOTOT;
        public double SYOTOT
        {
            get { return fSYOTOT; }
            set { SetPropertyValue<double>("SYOTOT", ref fSYOTOT, value); }
        }
        double fSYPCRT;
        public double SYPCRT
        {
            get { return fSYPCRT; }
            set { SetPropertyValue<double>("SYPCRT", ref fSYPCRT, value); }
        }
        string fSYRTNR;
        [Size(3)]
        public string SYRTNR
        {
            get { return fSYRTNR; }
            set { SetPropertyValue<string>("SYRTNR", ref fSYRTNR, value); }
        }
        string fSYWUMD;
        [Size(2)]
        public string SYWUMD
        {
            get { return fSYWUMD; }
            set { SetPropertyValue<string>("SYWUMD", ref fSYWUMD, value); }
        }
        string fSYVUMD;
        [Size(2)]
        public string SYVUMD
        {
            get { return fSYVUMD; }
            set { SetPropertyValue<string>("SYVUMD", ref fSYVUMD, value); }
        }
        char fSYPURG;
        public char SYPURG
        {
            get { return fSYPURG; }
            set { SetPropertyValue<char>("SYPURG", ref fSYPURG, value); }
        }
        char fSYLGCT;
        public char SYLGCT
        {
            get { return fSYLGCT; }
            set { SetPropertyValue<char>("SYLGCT", ref fSYLGCT, value); }
        }
        char fSYPROM;
        public char SYPROM
        {
            get { return fSYPROM; }
            set { SetPropertyValue<char>("SYPROM", ref fSYPROM, value); }
        }
        char fSYMATY;
        public char SYMATY
        {
            get { return fSYMATY; }
            set { SetPropertyValue<char>("SYMATY", ref fSYMATY, value); }
        }
        char fSYOSTS;
        public char SYOSTS
        {
            get { return fSYOSTS; }
            set { SetPropertyValue<char>("SYOSTS", ref fSYOSTS, value); }
        }
        char fSYAVCH;
        public char SYAVCH
        {
            get { return fSYAVCH; }
            set { SetPropertyValue<char>("SYAVCH", ref fSYAVCH, value); }
        }
        char fSYPRPY;
        public char SYPRPY
        {
            get { return fSYPRPY; }
            set { SetPropertyValue<char>("SYPRPY", ref fSYPRPY, value); }
        }
        char fSYCRMD;
        public char SYCRMD
        {
            get { return fSYCRMD; }
            set { SetPropertyValue<char>("SYCRMD", ref fSYCRMD, value); }
        }
        string fSYPRP5;
        [Size(3)]
        public string SYPRP5
        {
            get { return fSYPRP5; }
            set { SetPropertyValue<string>("SYPRP5", ref fSYPRP5, value); }
        }
        string fSYARTG;
        [Size(12)]
        public string SYARTG
        {
            get { return fSYARTG; }
            set { SetPropertyValue<string>("SYARTG", ref fSYARTG, value); }
        }
        double fSYCORD;
        public double SYCORD
        {
            get { return fSYCORD; }
            set { SetPropertyValue<double>("SYCORD", ref fSYCORD, value); }
        }
        char fSYCRRM;
        public char SYCRRM
        {
            get { return fSYCRRM; }
            set { SetPropertyValue<char>("SYCRRM", ref fSYCRRM, value); }
        }
        string fSYCRCD;
        [Size(3)]
        public string SYCRCD
        {
            get { return fSYCRCD; }
            set { SetPropertyValue<string>("SYCRCD", ref fSYCRCD, value); }
        }
        double fSYCRR;
        public double SYCRR
        {
            get { return fSYCRR; }
            set { SetPropertyValue<double>("SYCRR", ref fSYCRR, value); }
        }
        string fSYLNGP;
        [Size(2)]
        public string SYLNGP
        {
            get { return fSYLNGP; }
            set { SetPropertyValue<string>("SYLNGP", ref fSYLNGP, value); }
        }
        double fSYFAP;
        public double SYFAP
        {
            get { return fSYFAP; }
            set { SetPropertyValue<double>("SYFAP", ref fSYFAP, value); }
        }
        string fSYORBY;
        [Size(10)]
        public string SYORBY
        {
            get { return fSYORBY; }
            set { SetPropertyValue<string>("SYORBY", ref fSYORBY, value); }
        }
        string fSYTKBY;
        [Size(10)]
        public string SYTKBY
        {
            get { return fSYTKBY; }
            set { SetPropertyValue<string>("SYTKBY", ref fSYTKBY, value); }
        }
        string fSYURCD;
        [Size(2)]
        public string SYURCD
        {
            get { return fSYURCD; }
            set { SetPropertyValue<string>("SYURCD", ref fSYURCD, value); }
        }
        decimal fSYURDT;
        public decimal SYURDT
        {
            get { return fSYURDT; }
            set { SetPropertyValue<decimal>("SYURDT", ref fSYURDT, value); }
        }
        double fSYURAT;
        public double SYURAT
        {
            get { return fSYURAT; }
            set { SetPropertyValue<double>("SYURAT", ref fSYURAT, value); }
        }
        double fSYURAB;
        public double SYURAB
        {
            get { return fSYURAB; }
            set { SetPropertyValue<double>("SYURAB", ref fSYURAB, value); }
        }
        string fSYURRF;
        [Size(15)]
        public string SYURRF
        {
            get { return fSYURRF; }
            set { SetPropertyValue<string>("SYURRF", ref fSYURRF, value); }
        }
        string fSYTORG;
        [Size(10)]
        public string SYTORG
        {
            get { return fSYTORG; }
            set { SetPropertyValue<string>("SYTORG", ref fSYTORG, value); }
        }
        string fSYUSER;
        [Size(10)]
        public string SYUSER
        {
            get { return fSYUSER; }
            set { SetPropertyValue<string>("SYUSER", ref fSYUSER, value); }
        }
        string fSYPID;
        [Size(10)]
        public string SYPID
        {
            get { return fSYPID; }
            set { SetPropertyValue<string>("SYPID", ref fSYPID, value); }
        }
        string fSYJOBN;
        [Size(10)]
        public string SYJOBN
        {
            get { return fSYJOBN; }
            set { SetPropertyValue<string>("SYJOBN", ref fSYJOBN, value); }
        }
        decimal fSYUPMJ;
        public decimal SYUPMJ
        {
            get { return fSYUPMJ; }
            set { SetPropertyValue<decimal>("SYUPMJ", ref fSYUPMJ, value); }
        }
        double fSYTDAY;
        public double SYTDAY
        {
            get { return fSYTDAY; }
            set { SetPropertyValue<double>("SYTDAY", ref fSYTDAY, value); }
        }
        string fSYVR03;
        [Size(25)]
        public string SYVR03
        {
            get { return fSYVR03; }
            set { SetPropertyValue<string>("SYVR03", ref fSYVR03, value); }
        }
        double fSYRSHT;
        public double SYRSHT
        {
            get { return fSYRSHT; }
            set { SetPropertyValue<double>("SYRSHT", ref fSYRSHT, value); }
        }
        double fSYMKFR;
        public double SYMKFR
        {
            get { return fSYMKFR; }
            set { SetPropertyValue<double>("SYMKFR", ref fSYMKFR, value); }
        }
        double fSYDRQT;
        public double SYDRQT
        {
            get { return fSYDRQT; }
            set { SetPropertyValue<double>("SYDRQT", ref fSYDRQT, value); }
        }
        double fSYDOC1;
        public double SYDOC1
        {
            get { return fSYDOC1; }
            set { SetPropertyValue<double>("SYDOC1", ref fSYDOC1, value); }
        }
        string fSYDCT4;
        [Size(2)]
        public string SYDCT4
        {
            get { return fSYDCT4; }
            set { SetPropertyValue<string>("SYDCT4", ref fSYDCT4, value); }
        }
        double fSYBTAN;
        public double SYBTAN
        {
            get { return fSYBTAN; }
            set { SetPropertyValue<double>("SYBTAN", ref fSYBTAN, value); }
        }
        string fSYBCRC;
        [Size(3)]
        public string SYBCRC
        {
            get { return fSYBCRC; }
            set { SetPropertyValue<string>("SYBCRC", ref fSYBCRC, value); }
        }
        char fSYPOHP01;
        public char SYPOHP01
        {
            get { return fSYPOHP01; }
            set { SetPropertyValue<char>("SYPOHP01", ref fSYPOHP01, value); }
        }
        char fSYPOHP02;
        public char SYPOHP02
        {
            get { return fSYPOHP02; }
            set { SetPropertyValue<char>("SYPOHP02", ref fSYPOHP02, value); }
        }
        char fSYPOHP03;
        public char SYPOHP03
        {
            get { return fSYPOHP03; }
            set { SetPropertyValue<char>("SYPOHP03", ref fSYPOHP03, value); }
        }
        char fSYPOHP04;
        public char SYPOHP04
        {
            get { return fSYPOHP04; }
            set { SetPropertyValue<char>("SYPOHP04", ref fSYPOHP04, value); }
        }
        char fSYPOHP05;
        public char SYPOHP05
        {
            get { return fSYPOHP05; }
            set { SetPropertyValue<char>("SYPOHP05", ref fSYPOHP05, value); }
        }
        char fSYPOHP06;
        public char SYPOHP06
        {
            get { return fSYPOHP06; }
            set { SetPropertyValue<char>("SYPOHP06", ref fSYPOHP06, value); }
        }
        char fSYPOHP07;
        public char SYPOHP07
        {
            get { return fSYPOHP07; }
            set { SetPropertyValue<char>("SYPOHP07", ref fSYPOHP07, value); }
        }
        char fSYPOHP08;
        public char SYPOHP08
        {
            get { return fSYPOHP08; }
            set { SetPropertyValue<char>("SYPOHP08", ref fSYPOHP08, value); }
        }
        char fSYPOHP09;
        public char SYPOHP09
        {
            get { return fSYPOHP09; }
            set { SetPropertyValue<char>("SYPOHP09", ref fSYPOHP09, value); }
        }
        char fSYPOHP10;
        public char SYPOHP10
        {
            get { return fSYPOHP10; }
            set { SetPropertyValue<char>("SYPOHP10", ref fSYPOHP10, value); }
        }
        char fSYPOHP11;
        public char SYPOHP11
        {
            get { return fSYPOHP11; }
            set { SetPropertyValue<char>("SYPOHP11", ref fSYPOHP11, value); }
        }
        char fSYPOHP12;
        public char SYPOHP12
        {
            get { return fSYPOHP12; }
            set { SetPropertyValue<char>("SYPOHP12", ref fSYPOHP12, value); }
        }
        string fSYPOHC01;
        [Size(3)]
        public string SYPOHC01
        {
            get { return fSYPOHC01; }
            set { SetPropertyValue<string>("SYPOHC01", ref fSYPOHC01, value); }
        }
        string fSYPOHC02;
        [Size(3)]
        public string SYPOHC02
        {
            get { return fSYPOHC02; }
            set { SetPropertyValue<string>("SYPOHC02", ref fSYPOHC02, value); }
        }
        string fSYPOHC03;
        [Size(3)]
        public string SYPOHC03
        {
            get { return fSYPOHC03; }
            set { SetPropertyValue<string>("SYPOHC03", ref fSYPOHC03, value); }
        }
        string fSYPOHC04;
        [Size(3)]
        public string SYPOHC04
        {
            get { return fSYPOHC04; }
            set { SetPropertyValue<string>("SYPOHC04", ref fSYPOHC04, value); }
        }
        string fSYPOHC05;
        [Size(3)]
        public string SYPOHC05
        {
            get { return fSYPOHC05; }
            set { SetPropertyValue<string>("SYPOHC05", ref fSYPOHC05, value); }
        }
        string fSYPOHC06;
        [Size(3)]
        public string SYPOHC06
        {
            get { return fSYPOHC06; }
            set { SetPropertyValue<string>("SYPOHC06", ref fSYPOHC06, value); }
        }
        string fSYPOHC07;
        [Size(10)]
        public string SYPOHC07
        {
            get { return fSYPOHC07; }
            set { SetPropertyValue<string>("SYPOHC07", ref fSYPOHC07, value); }
        }
        string fSYPOHC08;
        [Size(10)]
        public string SYPOHC08
        {
            get { return fSYPOHC08; }
            set { SetPropertyValue<string>("SYPOHC08", ref fSYPOHC08, value); }
        }
        string fSYPOHC09;
        [Size(10)]
        public string SYPOHC09
        {
            get { return fSYPOHC09; }
            set { SetPropertyValue<string>("SYPOHC09", ref fSYPOHC09, value); }
        }
        string fSYPOHC10;
        [Size(10)]
        public string SYPOHC10
        {
            get { return fSYPOHC10; }
            set { SetPropertyValue<string>("SYPOHC10", ref fSYPOHC10, value); }
        }
        string fSYPOHC11;
        [Size(10)]
        public string SYPOHC11
        {
            get { return fSYPOHC11; }
            set { SetPropertyValue<string>("SYPOHC11", ref fSYPOHC11, value); }
        }
        string fSYPOHC12;
        [Size(10)]
        public string SYPOHC12
        {
            get { return fSYPOHC12; }
            set { SetPropertyValue<string>("SYPOHC12", ref fSYPOHC12, value); }
        }
        decimal fSYPOHD01;
        public decimal SYPOHD01
        {
            get { return fSYPOHD01; }
            set { SetPropertyValue<decimal>("SYPOHD01", ref fSYPOHD01, value); }
        }
        decimal fSYPOHD02;
        public decimal SYPOHD02
        {
            get { return fSYPOHD02; }
            set { SetPropertyValue<decimal>("SYPOHD02", ref fSYPOHD02, value); }
        }
        double fSYPOHAB01;
        public double SYPOHAB01
        {
            get { return fSYPOHAB01; }
            set { SetPropertyValue<double>("SYPOHAB01", ref fSYPOHAB01, value); }
        }
        double fSYPOHAB02;
        public double SYPOHAB02
        {
            get { return fSYPOHAB02; }
            set { SetPropertyValue<double>("SYPOHAB02", ref fSYPOHAB02, value); }
        }
        double fSYCUKID;
        public double SYCUKID
        {
            get { return fSYCUKID; }
            set { SetPropertyValue<double>("SYCUKID", ref fSYCUKID, value); }
        }
        string fSYPOHP13;
        [Size(30)]
        public string SYPOHP13
        {
            get { return fSYPOHP13; }
            set { SetPropertyValue<string>("SYPOHP13", ref fSYPOHP13, value); }
        }
        DateTime fSYPOHU01;
        public DateTime SYPOHU01
        {
            get { return fSYPOHU01; }
            set { SetPropertyValue<DateTime>("SYPOHU01", ref fSYPOHU01, value); }
        }
        DateTime fSYPOHU02;
        public DateTime SYPOHU02
        {
            get { return fSYPOHU02; }
            set { SetPropertyValue<DateTime>("SYPOHU02", ref fSYPOHU02, value); }
        }
        char fSYRETI;
        public char SYRETI
        {
            get { return fSYRETI; }
            set { SetPropertyValue<char>("SYRETI", ref fSYRETI, value); }
        }
        string fSYCLASS01;
        [Size(3)]
        public string SYCLASS01
        {
            get { return fSYCLASS01; }
            set { SetPropertyValue<string>("SYCLASS01", ref fSYCLASS01, value); }
        }
        string fSYCLASS02;
        [Size(3)]
        public string SYCLASS02
        {
            get { return fSYCLASS02; }
            set { SetPropertyValue<string>("SYCLASS02", ref fSYCLASS02, value); }
        }
        string fSYCLASS03;
        [Size(3)]
        public string SYCLASS03
        {
            get { return fSYCLASS03; }
            set { SetPropertyValue<string>("SYCLASS03", ref fSYCLASS03, value); }
        }
        string fSYCLASS04;
        [Size(3)]
        public string SYCLASS04
        {
            get { return fSYCLASS04; }
            set { SetPropertyValue<string>("SYCLASS04", ref fSYCLASS04, value); }
        }
        string fSYCLASS05;
        [Size(3)]
        public string SYCLASS05
        {
            get { return fSYCLASS05; }
            set { SetPropertyValue<string>("SYCLASS05", ref fSYCLASS05, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(10)]
            [Persistent("SYEDUS")]
            public string SYEDUS { get; set; }
            [Size(15)]
            [Persistent("SYEDBT")]
            public string SYEDBT { get; set; }
            [Size(22)]
            [Persistent("SYEDTN")]
            public string SYEDTN { get; set; }
            [Persistent("SYEDLN")]
            public double SYEDLN { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
