//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class FieldDataCollection : XPLiteObject
    {
        int fFieldDataID;
        [Key(true)]
        public int FieldDataID
        {
            get { return fFieldDataID; }
            set { SetPropertyValue<int>("FieldDataID", ref fFieldDataID, value); }
        }
        string fJobid;
        [Size(20)]
        public string Jobid
        {
            get { return fJobid; }
            set { SetPropertyValue<string>("Jobid", ref fJobid, value); }
        }
        string fFieldDataDescription;
        [Size(254)]
        public string FieldDataDescription
        {
            get { return fFieldDataDescription; }
            set { SetPropertyValue<string>("FieldDataDescription", ref fFieldDataDescription, value); }
        }
        MaintenanceObjects fObjectID;
        [Association(@"FieldDataCollectionReferencesMaintenanceObjects")]
        public MaintenanceObjects ObjectID
        {
            get { return fObjectID; }
            set { SetPropertyValue<MaintenanceObjects>("ObjectID", ref fObjectID, value); }
        }
        SubAssemblyNames fSubAssemblyID;
        [Association(@"FieldDataCollectionReferencesSubAssemblyNames")]
        public SubAssemblyNames SubAssemblyID
        {
            get { return fSubAssemblyID; }
            set { SetPropertyValue<SubAssemblyNames>("SubAssemblyID", ref fSubAssemblyID, value); }
        }
        MPetUsers fRequestedByID;
        [Association(@"FieldDataCollectionReferencesMPetUsers2")]
        public MPetUsers RequestedByID
        {
            get { return fRequestedByID; }
            set { SetPropertyValue<MPetUsers>("RequestedByID", ref fRequestedByID, value); }
        }
        DateTime fStartingOn;
        public DateTime StartingOn
        {
            get { return fStartingOn; }
            set { SetPropertyValue<DateTime>("StartingOn", ref fStartingOn, value); }
        }
        DateTime fCompletedOn;
        public DateTime CompletedOn
        {
            get { return fCompletedOn; }
            set { SetPropertyValue<DateTime>("CompletedOn", ref fCompletedOn, value); }
        }
        decimal fWorkLength;
        public decimal WorkLength
        {
            get { return fWorkLength; }
            set { SetPropertyValue<decimal>("WorkLength", ref fWorkLength, value); }
        }
        Priorities fPriorityID;
        [Association(@"FieldDataCollectionReferencesPriorities")]
        public Priorities PriorityID
        {
            get { return fPriorityID; }
            set { SetPropertyValue<Priorities>("PriorityID", ref fPriorityID, value); }
        }
        JobReasons fReasonCodeID;
        [Association(@"FieldDataCollectionReferencesJobReasons")]
        public JobReasons ReasonCodeID
        {
            get { return fReasonCodeID; }
            set { SetPropertyValue<JobReasons>("ReasonCodeID", ref fReasonCodeID, value); }
        }
        MPetUsers fRouteToID;
        [Association(@"FieldDataCollectionReferencesMPetUsers3")]
        public MPetUsers RouteToID
        {
            get { return fRouteToID; }
            set { SetPropertyValue<MPetUsers>("RouteToID", ref fRouteToID, value); }
        }
        OutcomeCodes fOutcomeCodeID;
        [Association(@"FieldDataCollectionReferencesOutcomeCodes")]
        public OutcomeCodes OutcomeCodeID
        {
            get { return fOutcomeCodeID; }
            set { SetPropertyValue<OutcomeCodes>("OutcomeCodeID", ref fOutcomeCodeID, value); }
        }
        StateRoutes fStateRouteID;
        [Association(@"FieldDataCollectionReferencesStateRoutes")]
        public StateRoutes StateRouteID
        {
            get { return fStateRouteID; }
            set { SetPropertyValue<StateRoutes>("StateRouteID", ref fStateRouteID, value); }
        }
        MilePostDirections fMilepostDirectionID;
        [Association(@"FieldDataCollectionReferencesMilePostDirections")]
        public MilePostDirections MilepostDirectionID
        {
            get { return fMilepostDirectionID; }
            set { SetPropertyValue<MilePostDirections>("MilepostDirectionID", ref fMilepostDirectionID, value); }
        }
        decimal fMilepostFrom;
        public decimal MilepostFrom
        {
            get { return fMilepostFrom; }
            set { SetPropertyValue<decimal>("MilepostFrom", ref fMilepostFrom, value); }
        }
        decimal fMilepostTo;
        public decimal MilepostTo
        {
            get { return fMilepostTo; }
            set { SetPropertyValue<decimal>("MilepostTo", ref fMilepostTo, value); }
        }
        decimal fGPSX;
        public decimal GPSX
        {
            get { return fGPSX; }
            set { SetPropertyValue<decimal>("GPSX", ref fGPSX, value); }
        }
        decimal fGPSY;
        public decimal GPSY
        {
            get { return fGPSY; }
            set { SetPropertyValue<decimal>("GPSY", ref fGPSY, value); }
        }
        decimal fGPSZ;
        public decimal GPSZ
        {
            get { return fGPSZ; }
            set { SetPropertyValue<decimal>("GPSZ", ref fGPSZ, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>("Notes", ref fNotes, value); }
        }
        CostCodes fCostCodeID;
        [Association(@"FieldDataCollectionReferencesCostCodes")]
        public CostCodes CostCodeID
        {
            get { return fCostCodeID; }
            set { SetPropertyValue<CostCodes>("CostCodeID", ref fCostCodeID, value); }
        }
        FundSrcCodes fFundSourceCodeID;
        [Association(@"FieldDataCollectionReferencesFundSrcCodes")]
        public FundSrcCodes FundSourceCodeID
        {
            get { return fFundSourceCodeID; }
            set { SetPropertyValue<FundSrcCodes>("FundSourceCodeID", ref fFundSourceCodeID, value); }
        }
        WorkOrderCodes fWorkOrderCodeID;
        [Association(@"FieldDataCollectionReferencesWorkOrderCodes")]
        public WorkOrderCodes WorkOrderCodeID
        {
            get { return fWorkOrderCodeID; }
            set { SetPropertyValue<WorkOrderCodes>("WorkOrderCodeID", ref fWorkOrderCodeID, value); }
        }
        WorkOperations fWorkOperationID;
        [Association(@"FieldDataCollectionReferencesWorkOperations")]
        public WorkOperations WorkOperationID
        {
            get { return fWorkOperationID; }
            set { SetPropertyValue<WorkOperations>("WorkOperationID", ref fWorkOperationID, value); }
        }
        OrganizationCodes fOrganizationCodeID;
        [Association(@"FieldDataCollectionReferencesOrganizationCodes")]
        public OrganizationCodes OrganizationCodeID
        {
            get { return fOrganizationCodeID; }
            set { SetPropertyValue<OrganizationCodes>("OrganizationCodeID", ref fOrganizationCodeID, value); }
        }
        FundingGroupCodes fFundingGroupCodeID;
        [Association(@"FieldDataCollectionReferencesFundingGroupCodes")]
        public FundingGroupCodes FundingGroupCodeID
        {
            get { return fFundingGroupCodeID; }
            set { SetPropertyValue<FundingGroupCodes>("FundingGroupCodeID", ref fFundingGroupCodeID, value); }
        }
        ControlSections fControlSectionID;
        [Association(@"FieldDataCollectionReferencesControlSections")]
        public ControlSections ControlSectionID
        {
            get { return fControlSectionID; }
            set { SetPropertyValue<ControlSections>("ControlSectionID", ref fControlSectionID, value); }
        }
        EquipmentNumber fEquipmentNumberID;
        [Association(@"FieldDataCollectionReferencesEquipmentNumber")]
        public EquipmentNumber EquipmentNumberID
        {
            get { return fEquipmentNumberID; }
            set { SetPropertyValue<EquipmentNumber>("EquipmentNumberID", ref fEquipmentNumberID, value); }
        }
        string fBreakdown;
        [Size(1)]
        public string Breakdown
        {
            get { return fBreakdown; }
            set { SetPropertyValue<string>("Breakdown", ref fBreakdown, value); }
        }
        string fWorkCompleted;
        [Size(1)]
        public string WorkCompleted
        {
            get { return fWorkCompleted; }
            set { SetPropertyValue<string>("WorkCompleted", ref fWorkCompleted, value); }
        }
        string fUpdateExpiration;
        [Size(1)]
        public string UpdateExpiration
        {
            get { return fUpdateExpiration; }
            set { SetPropertyValue<string>("UpdateExpiration", ref fUpdateExpiration, value); }
        }
        string fUpdateLifeCycle;
        [Size(1)]
        public string UpdateLifeCycle
        {
            get { return fUpdateLifeCycle; }
            set { SetPropertyValue<string>("UpdateLifeCycle", ref fUpdateLifeCycle, value); }
        }
        string fUpdateInService;
        [Size(1)]
        public string UpdateInService
        {
            get { return fUpdateInService; }
            set { SetPropertyValue<string>("UpdateInService", ref fUpdateInService, value); }
        }
        MPetUsers fCreatedByID;
        [Association(@"FieldDataCollectionReferencesMPetUsers")]
        public MPetUsers CreatedByID
        {
            get { return fCreatedByID; }
            set { SetPropertyValue<MPetUsers>("CreatedByID", ref fCreatedByID, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedByID;
        [Association(@"FieldDataCollectionReferencesMPetUsers1")]
        public MPetUsers ModifiedByID
        {
            get { return fModifiedByID; }
            set { SetPropertyValue<MPetUsers>("ModifiedByID", ref fModifiedByID, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
    }

}
