//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    [NonPersistent]
    public partial class filter_GetFilteredJobListForSchedulerResult
    {
        public int n_jobstepid { get; set; }
        public int n_jobid { get; set; }
        public string T { get; set; }
        public string A { get; set; }
        public string Jobid { get; set; }
        public string ObjectID { get; set; }
        public int step { get; set; }
        public string StepTitle { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public DateTime Requested { get; set; }
        public DateTime StartingDate { get; set; }
        public string LaborClass { get; set; }
        public string Group { get; set; }
        public string Outcome { get; set; }
        public string Supervisor { get; set; }
        public string H { get; set; }
        public string I { get; set; }
        public string JobReasonID { get; set; }
        public string AssignedTaskID { get; set; }
        public int Column20 { get; set; }
        public int Column21 { get; set; }
        public int Column22 { get; set; }
        public DateTime CompletionDate { get; set; }
        public int ReturnWithin { get; set; }
        public string WorkOpID { get; set; }
    }

}
