//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    [NonPersistent]
    public partial class filter_GetFilteredFundSourceLinkListResult
    {
        public int n_FundSrcCodeLinkID { get; set; }
        public int n_FundSrcCodeID { get; set; }
        public string FundSrcCodeID { get; set; }
        public int n_WorkOrderCodeID { get; set; }
        public string WorkOrderCodeID { get; set; }
        public string Description { get; set; }
    }

}
