//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    [NonPersistent]
    public partial class filter_GetFilteredMaintenanceObjectsListResult
    {
        public int n_objectid { get; set; }
        public string objectid { get; set; }
        public string description { get; set; }
        public string b_active { get; set; }
        public string b_chargeable { get; set; }
        public string CurrentCondition { get; set; }
        public string ReponsiblePerson { get; set; }
        public string Storeroom { get; set; }
        public string Area { get; set; }
        public string TaskID { get; set; }
        public string LocationID { get; set; }
        public string ObjectType { get; set; }
        public string ObjectClass { get; set; }
        public string AssetNumber { get; set; }
        public string Misc_Ref_ { get; set; }
        public string Manufacturer { get; set; }
        public string ModelNumber { get; set; }
        public string SerialNumber { get; set; }
        public DateTime Build_Purchase { get; set; }
        public DateTime In_Service { get; set; }
        public DateTime WarrantyExp_ { get; set; }
        public DateTime LifeCycle { get; set; }
        public string RunUnit1Desc { get; set; }
        public decimal RunUnit1Reading { get; set; }
        public int n_productlineid { get; set; }
        public string ProductLineID { get; set; }
        public string HighwayRouteID { get; set; }
        public decimal MileMarker { get; set; }
        public decimal MileMarkerTo { get; set; }
        public decimal ChargeRate { get; set; }
        public string UnitsOfMeasureID { get; set; }
        public decimal Quantity { get; set; }
        public string MilePostDirection { get; set; }
        public int FlaggedRecordID { get; set; }
        public string ParentObjectID { get; set; }
        public string costcodeid { get; set; }
        public string SupplementalCode { get; set; }
        public string FundSrcCodeID { get; set; }
        public string WorkOrderCodeID { get; set; }
        public string WorkOpID { get; set; }
        public string OrganizationCodeID { get; set; }
        public string FundingGroupCodeID { get; set; }
        public string ControlSectionID { get; set; }
        public string EquipmentNumberID { get; set; }
        public string VendorID { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    }

}
