//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    [NonPersistent]
    public partial class filter_GetFilteredIncidentLogsListResult
    {
        public int RecordID { get; set; }
        public string IncidentNum { get; set; }
        public string IncidentSummary { get; set; }
        public int n_IncidentID { get; set; }
        public string IncidentID { get; set; }
        public int n_IncidentTypeID { get; set; }
        public string IncidentTypeID { get; set; }
        public int n_IncidentSourceID { get; set; }
        public string IncidentSourceID { get; set; }
        public int n_IncidentResponseID { get; set; }
        public string IncidentResponseID { get; set; }
        public int n_JobID { get; set; }
        public string JobID { get; set; }
        public int n_ShiftID { get; set; }
        public string ShiftID { get; set; }
        public string b_Closed { get; set; }
        public DateTime ReportedOn { get; set; }
        public int n_ReportedBy { get; set; }
        public string ReportedBy { get; set; }
        public DateTime ClosedOn { get; set; }
        public int n_ClosedBy { get; set; }
        public string ClosedBy { get; set; }
        public int FlaggedRecordID { get; set; }
        public string StateRouteID { get; set; }
        public string AreaID { get; set; }
        public string CostCodeID { get; set; }
        public string FundSrcCodeID { get; set; }
        public string WorkOrderCodeID { get; set; }
        public string WorkOpID { get; set; }
        public string OrganizationCodeID { get; set; }
        public string FundingGroupID { get; set; }
        public string ControlSectionID { get; set; }
        public string EquipmentNumberID { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    }

}
