//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    [NonPersistent]
    public partial class filter_GetFilteredStoreroomTransferPartsListResult
    {
        public int n_partatlocid { get; set; }
        public int n_masterpartid { get; set; }
        public string PartIDDesc { get; set; }
        public string Aisle { get; set; }
        public string Shelf { get; set; }
        public string Bin { get; set; }
        public int Quantity { get; set; }
        public int n_storeroomid { get; set; }
        public string storeroomid { get; set; }
    }

}
