//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    [NonPersistent]
    public partial class filter_GetFilteredObjectTypeListResult
    {
        public int n_objtypeid { get; set; }
        public string objtypeid { get; set; }
        public string descr { get; set; }
        public int tasknum { get; set; }
        public int count { get; set; }
        public string b_IsActive { get; set; }
    }

}
