//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    [NonPersistent]
    public partial class filter_GetFilteredMPETUserListResult
    {
        public int nUserID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public string PositionCode { get; set; }
        public string PersonClass { get; set; }
        public string Location { get; set; }
        public int LaborClassID { get; set; }
        public string LaborClass { get; set; }
        public int GroupID { get; set; }
        public string Group { get; set; }
        public int FlaggedRecordID { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    }

}
