//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    [NonPersistent]
    public partial class filter_GetFilteredOutcomeCodeListResult
    {
        public int n_outcomecodeid { get; set; }
        public string outcomecodeid { get; set; }
        public string description { get; set; }
        public string SubtractFromIssued { get; set; }
        public string CountAsCompleted { get; set; }
        public string WorkNotDone { get; set; }
        public string b_IsActive { get; set; }
        public string PostNotesRequired { get; set; }
    }

}
