//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class FontAndColors : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        MPetUsers fPersonID;
        [Association(@"FontAndColorsReferencesMPetUsers")]
        public MPetUsers PersonID
        {
            get { return fPersonID; }
            set { SetPropertyValue<MPetUsers>("PersonID", ref fPersonID, value); }
        }
        string fPrintOrientation;
        [Size(10)]
        public string PrintOrientation
        {
            get { return fPrintOrientation; }
            set { SetPropertyValue<string>("PrintOrientation", ref fPrintOrientation, value); }
        }
        string fReportTitleFont;
        [Size(50)]
        public string ReportTitleFont
        {
            get { return fReportTitleFont; }
            set { SetPropertyValue<string>("ReportTitleFont", ref fReportTitleFont, value); }
        }
        string fFontName;
        [Size(50)]
        public string FontName
        {
            get { return fFontName; }
            set { SetPropertyValue<string>("FontName", ref fFontName, value); }
        }
        string fFontSize;
        [Size(50)]
        public string FontSize
        {
            get { return fFontSize; }
            set { SetPropertyValue<string>("FontSize", ref fFontSize, value); }
        }
        string fFontBold;
        [Size(50)]
        public string FontBold
        {
            get { return fFontBold; }
            set { SetPropertyValue<string>("FontBold", ref fFontBold, value); }
        }
        string fFontUnderline;
        [Size(50)]
        public string FontUnderline
        {
            get { return fFontUnderline; }
            set { SetPropertyValue<string>("FontUnderline", ref fFontUnderline, value); }
        }
        string fFontItalic;
        [Size(50)]
        public string FontItalic
        {
            get { return fFontItalic; }
            set { SetPropertyValue<string>("FontItalic", ref fFontItalic, value); }
        }
        int fRequiredForegroundColor;
        public int RequiredForegroundColor
        {
            get { return fRequiredForegroundColor; }
            set { SetPropertyValue<int>("RequiredForegroundColor", ref fRequiredForegroundColor, value); }
        }
        int fRequiredBackgroundColor;
        public int RequiredBackgroundColor
        {
            get { return fRequiredBackgroundColor; }
            set { SetPropertyValue<int>("RequiredBackgroundColor", ref fRequiredBackgroundColor, value); }
        }
        int fDisplayOnlyForegroundColor;
        public int DisplayOnlyForegroundColor
        {
            get { return fDisplayOnlyForegroundColor; }
            set { SetPropertyValue<int>("DisplayOnlyForegroundColor", ref fDisplayOnlyForegroundColor, value); }
        }
        int fDisplayOnlyBackgoundColor;
        public int DisplayOnlyBackgoundColor
        {
            get { return fDisplayOnlyBackgoundColor; }
            set { SetPropertyValue<int>("DisplayOnlyBackgoundColor", ref fDisplayOnlyBackgoundColor, value); }
        }
        int fOtherForegroundColor;
        public int OtherForegroundColor
        {
            get { return fOtherForegroundColor; }
            set { SetPropertyValue<int>("OtherForegroundColor", ref fOtherForegroundColor, value); }
        }
        int fOtherBackgroundcolor;
        public int OtherBackgroundcolor
        {
            get { return fOtherBackgroundcolor; }
            set { SetPropertyValue<int>("OtherBackgroundcolor", ref fOtherBackgroundcolor, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"FontAndColorsReferencesMPetUsers1")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"FontAndColorsReferencesMPetUsers2")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
    }

}
