//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class groups : XPLiteObject
    {
        int fn_groupid;
        [Key(true)]
        public int n_groupid
        {
            get { return fn_groupid; }
            set { SetPropertyValue<int>("n_groupid", ref fn_groupid, value); }
        }
        string fgroupid;
        [Size(20)]
        public string groupid
        {
            get { return fgroupid; }
            set { SetPropertyValue<string>("groupid", ref fgroupid, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fActive;
        [Size(1)]
        public string Active
        {
            get { return fActive; }
            set { SetPropertyValue<string>("Active", ref fActive, value); }
        }
        Tasks fTaskNum;
        [Association(@"groupsReferencesTasks")]
        public Tasks TaskNum
        {
            get { return fTaskNum; }
            set { SetPropertyValue<Tasks>("TaskNum", ref fTaskNum, value); }
        }
        MPetUsers fn_supervisorid;
        [Association(@"groupsReferencesMPetUsers2")]
        public MPetUsers n_supervisorid
        {
            get { return fn_supervisorid; }
            set { SetPropertyValue<MPetUsers>("n_supervisorid", ref fn_supervisorid, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"groupsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreationDate;
        public DateTime CreationDate
        {
            get { return fCreationDate; }
            set { SetPropertyValue<DateTime>("CreationDate", ref fCreationDate, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"groupsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime flast_modified;
        public DateTime last_modified
        {
            get { return flast_modified; }
            set { SetPropertyValue<DateTime>("last_modified", ref flast_modified, value); }
        }
        Areas fn_AreaID;
        [Association(@"groupsReferencesAreas")]
        public Areas n_AreaID
        {
            get { return fn_AreaID; }
            set { SetPropertyValue<Areas>("n_AreaID", ref fn_AreaID, value); }
        }
        [Association(@"groupmembersReferencesgroups", typeof(groupmembers))]
        public XPCollection<groupmembers> groupmembersCollection { get { return GetCollection<groupmembers>("groupmembersCollection"); } }
        [Association(@"JobsReferencesgroups", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection { get { return GetCollection<Jobs>("JobsCollection"); } }
        [Association(@"JobsReferencesgroups1", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection1 { get { return GetCollection<Jobs>("JobsCollection1"); } }
        [Association(@"JobstepsReferencesgroups", typeof(Jobsteps))]
        public XPCollection<Jobsteps> JobstepsCollection { get { return GetCollection<Jobsteps>("JobstepsCollection"); } }
        [Association(@"ObjectTasksReferencesgroups", typeof(ObjectTasks))]
        public XPCollection<ObjectTasks> ObjectTasksCollection { get { return GetCollection<ObjectTasks>("ObjectTasksCollection"); } }
        [Association(@"ObjectTasksReferencesgroups1", typeof(ObjectTasks))]
        public XPCollection<ObjectTasks> ObjectTasksCollection1 { get { return GetCollection<ObjectTasks>("ObjectTasksCollection1"); } }
        [Association(@"TestpointsReferencesgroups", typeof(Testpoints))]
        public XPCollection<Testpoints> TestpointsCollection { get { return GetCollection<Testpoints>("TestpointsCollection"); } }
        [Association(@"time_batchesReferencesgroups", typeof(time_batches))]
        public XPCollection<time_batches> time_batchess { get { return GetCollection<time_batches>("time_batchess"); } }
    }

}
