//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Incidents : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        string fIncidentNum;
        [Size(12)]
        public string IncidentNum
        {
            get { return fIncidentNum; }
            set { SetPropertyValue<string>("IncidentNum", ref fIncidentNum, value); }
        }
        string fIncidentSummary;
        [Size(254)]
        public string IncidentSummary
        {
            get { return fIncidentSummary; }
            set { SetPropertyValue<string>("IncidentSummary", ref fIncidentSummary, value); }
        }
        IncidentIDs fn_IncidentID;
        [Association(@"IncidentsReferencesIncidentIDs")]
        public IncidentIDs n_IncidentID
        {
            get { return fn_IncidentID; }
            set { SetPropertyValue<IncidentIDs>("n_IncidentID", ref fn_IncidentID, value); }
        }
        IncidentTypes fn_IncidentTypeID;
        [Association(@"IncidentsReferencesIncidentTypes")]
        public IncidentTypes n_IncidentTypeID
        {
            get { return fn_IncidentTypeID; }
            set { SetPropertyValue<IncidentTypes>("n_IncidentTypeID", ref fn_IncidentTypeID, value); }
        }
        IncidentSources fn_IncidentSourceID;
        [Association(@"IncidentsReferencesIncidentSources")]
        public IncidentSources n_IncidentSourceID
        {
            get { return fn_IncidentSourceID; }
            set { SetPropertyValue<IncidentSources>("n_IncidentSourceID", ref fn_IncidentSourceID, value); }
        }
        IncidentResponses fn_IncidentResponseID;
        [Association(@"IncidentsReferencesIncidentResponses")]
        public IncidentResponses n_IncidentResponseID
        {
            get { return fn_IncidentResponseID; }
            set { SetPropertyValue<IncidentResponses>("n_IncidentResponseID", ref fn_IncidentResponseID, value); }
        }
        Jobs fn_JobID;
        [Association(@"IncidentsReferencesJobs")]
        public Jobs n_JobID
        {
            get { return fn_JobID; }
            set { SetPropertyValue<Jobs>("n_JobID", ref fn_JobID, value); }
        }
        Shifts fn_ShiftID;
        [Association(@"IncidentsReferencesShifts")]
        public Shifts n_ShiftID
        {
            get { return fn_ShiftID; }
            set { SetPropertyValue<Shifts>("n_ShiftID", ref fn_ShiftID, value); }
        }
        string fProblemDescription;
        [Size(SizeAttribute.Unlimited)]
        public string ProblemDescription
        {
            get { return fProblemDescription; }
            set { SetPropertyValue<string>("ProblemDescription", ref fProblemDescription, value); }
        }
        string fResolution;
        [Size(SizeAttribute.Unlimited)]
        public string Resolution
        {
            get { return fResolution; }
            set { SetPropertyValue<string>("Resolution", ref fResolution, value); }
        }
        string fInterimFixes;
        [Size(SizeAttribute.Unlimited)]
        public string InterimFixes
        {
            get { return fInterimFixes; }
            set { SetPropertyValue<string>("InterimFixes", ref fInterimFixes, value); }
        }
        string fPermanentFixes;
        [Size(SizeAttribute.Unlimited)]
        public string PermanentFixes
        {
            get { return fPermanentFixes; }
            set { SetPropertyValue<string>("PermanentFixes", ref fPermanentFixes, value); }
        }
        string fVerification;
        [Size(SizeAttribute.Unlimited)]
        public string Verification
        {
            get { return fVerification; }
            set { SetPropertyValue<string>("Verification", ref fVerification, value); }
        }
        string fPrevention;
        [Size(SizeAttribute.Unlimited)]
        public string Prevention
        {
            get { return fPrevention; }
            set { SetPropertyValue<string>("Prevention", ref fPrevention, value); }
        }
        string fb_Closed;
        [Size(1)]
        public string b_Closed
        {
            get { return fb_Closed; }
            set { SetPropertyValue<string>("b_Closed", ref fb_Closed, value); }
        }
        DateTime fReportedOn;
        public DateTime ReportedOn
        {
            get { return fReportedOn; }
            set { SetPropertyValue<DateTime>("ReportedOn", ref fReportedOn, value); }
        }
        MPetUsers fReportedBy;
        [Association(@"IncidentsReferencesMPetUsers3")]
        public MPetUsers ReportedBy
        {
            get { return fReportedBy; }
            set { SetPropertyValue<MPetUsers>("ReportedBy", ref fReportedBy, value); }
        }
        DateTime fClosedOn;
        public DateTime ClosedOn
        {
            get { return fClosedOn; }
            set { SetPropertyValue<DateTime>("ClosedOn", ref fClosedOn, value); }
        }
        MPetUsers fClosedBy;
        [Association(@"IncidentsReferencesMPetUsers")]
        public MPetUsers ClosedBy
        {
            get { return fClosedBy; }
            set { SetPropertyValue<MPetUsers>("ClosedBy", ref fClosedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"IncidentsReferencesMPetUsers2")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"IncidentsReferencesMPetUsers1")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        StateRoutes fn_StateRouteID;
        [Association(@"IncidentsReferencesStateRoutes")]
        public StateRoutes n_StateRouteID
        {
            get { return fn_StateRouteID; }
            set { SetPropertyValue<StateRoutes>("n_StateRouteID", ref fn_StateRouteID, value); }
        }
        Areas fn_AreaID;
        [Association(@"IncidentsReferencesAreas")]
        public Areas n_AreaID
        {
            get { return fn_AreaID; }
            set { SetPropertyValue<Areas>("n_AreaID", ref fn_AreaID, value); }
        }
        CostCodes fn_CostCodeID;
        [Association(@"IncidentsReferencesCostCodes")]
        public CostCodes n_CostCodeID
        {
            get { return fn_CostCodeID; }
            set { SetPropertyValue<CostCodes>("n_CostCodeID", ref fn_CostCodeID, value); }
        }
        FundSrcCodes fn_FundSrcCodeID;
        [Association(@"IncidentsReferencesFundSrcCodes")]
        public FundSrcCodes n_FundSrcCodeID
        {
            get { return fn_FundSrcCodeID; }
            set { SetPropertyValue<FundSrcCodes>("n_FundSrcCodeID", ref fn_FundSrcCodeID, value); }
        }
        WorkOrderCodes fn_WorkOrderCodeID;
        [Association(@"IncidentsReferencesWorkOrderCodes")]
        public WorkOrderCodes n_WorkOrderCodeID
        {
            get { return fn_WorkOrderCodeID; }
            set { SetPropertyValue<WorkOrderCodes>("n_WorkOrderCodeID", ref fn_WorkOrderCodeID, value); }
        }
        WorkOperations fn_WorkOpID;
        [Association(@"IncidentsReferencesWorkOperations")]
        public WorkOperations n_WorkOpID
        {
            get { return fn_WorkOpID; }
            set { SetPropertyValue<WorkOperations>("n_WorkOpID", ref fn_WorkOpID, value); }
        }
        OrganizationCodes fn_OrganizationCodeID;
        [Association(@"IncidentsReferencesOrganizationCodes")]
        public OrganizationCodes n_OrganizationCodeID
        {
            get { return fn_OrganizationCodeID; }
            set { SetPropertyValue<OrganizationCodes>("n_OrganizationCodeID", ref fn_OrganizationCodeID, value); }
        }
        FundingGroupCodes fn_FundingGroupCodeID;
        [Association(@"IncidentsReferencesFundingGroupCodes")]
        public FundingGroupCodes n_FundingGroupCodeID
        {
            get { return fn_FundingGroupCodeID; }
            set { SetPropertyValue<FundingGroupCodes>("n_FundingGroupCodeID", ref fn_FundingGroupCodeID, value); }
        }
        ControlSections fn_ControlSectionID;
        [Association(@"IncidentsReferencesControlSections")]
        public ControlSections n_ControlSectionID
        {
            get { return fn_ControlSectionID; }
            set { SetPropertyValue<ControlSections>("n_ControlSectionID", ref fn_ControlSectionID, value); }
        }
        EquipmentNumber fn_EquipmentNumberID;
        [Association(@"IncidentsReferencesEquipmentNumber")]
        public EquipmentNumber n_EquipmentNumberID
        {
            get { return fn_EquipmentNumberID; }
            set { SetPropertyValue<EquipmentNumber>("n_EquipmentNumberID", ref fn_EquipmentNumberID, value); }
        }
        [Association(@"JobstepsReferencesIncidents", typeof(Jobsteps))]
        public XPCollection<Jobsteps> JobstepsCollection { get { return GetCollection<Jobsteps>("JobstepsCollection"); } }
        [Association(@"UsersFlaggedRecordsReferencesIncidents", typeof(UsersFlaggedRecords))]
        public XPCollection<UsersFlaggedRecords> UsersFlaggedRecordsCollection { get { return GetCollection<UsersFlaggedRecords>("UsersFlaggedRecordsCollection"); } }
    }

}
