//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class JobAlertDefaults : XPLiteObject
    {
        int fJobAlertID;
        [Key(true)]
        public int JobAlertID
        {
            get { return fJobAlertID; }
            set { SetPropertyValue<int>("JobAlertID", ref fJobAlertID, value); }
        }
        int fJobAlertLevel;
        public int JobAlertLevel
        {
            get { return fJobAlertLevel; }
            set { SetPropertyValue<int>("JobAlertLevel", ref fJobAlertLevel, value); }
        }
        int fActive;
        public int Active
        {
            get { return fActive; }
            set { SetPropertyValue<int>("Active", ref fActive, value); }
        }
        string fJobRequest;
        [Size(1)]
        public string JobRequest
        {
            get { return fJobRequest; }
            set { SetPropertyValue<string>("JobRequest", ref fJobRequest, value); }
        }
        int fDaysLate;
        public int DaysLate
        {
            get { return fDaysLate; }
            set { SetPropertyValue<int>("DaysLate", ref fDaysLate, value); }
        }
        int fForegroundColor;
        public int ForegroundColor
        {
            get { return fForegroundColor; }
            set { SetPropertyValue<int>("ForegroundColor", ref fForegroundColor, value); }
        }
        int fBackgroundColor;
        public int BackgroundColor
        {
            get { return fBackgroundColor; }
            set { SetPropertyValue<int>("BackgroundColor", ref fBackgroundColor, value); }
        }
        string fPriorityChanges;
        [Size(1)]
        public string PriorityChanges
        {
            get { return fPriorityChanges; }
            set { SetPropertyValue<string>("PriorityChanges", ref fPriorityChanges, value); }
        }
        string fSendEmail;
        [Size(1)]
        public string SendEmail
        {
            get { return fSendEmail; }
            set { SetPropertyValue<string>("SendEmail", ref fSendEmail, value); }
        }
        int fBasedOnJobDateTypeID;
        public int BasedOnJobDateTypeID
        {
            get { return fBasedOnJobDateTypeID; }
            set { SetPropertyValue<int>("BasedOnJobDateTypeID", ref fBasedOnJobDateTypeID, value); }
        }
        string fApplyDaysBefore;
        [Size(1)]
        public string ApplyDaysBefore
        {
            get { return fApplyDaysBefore; }
            set { SetPropertyValue<string>("ApplyDaysBefore", ref fApplyDaysBefore, value); }
        }
        int fPriorityChangeID;
        public int PriorityChangeID
        {
            get { return fPriorityChangeID; }
            set { SetPropertyValue<int>("PriorityChangeID", ref fPriorityChangeID, value); }
        }
        int fEmailID;
        public int EmailID
        {
            get { return fEmailID; }
            set { SetPropertyValue<int>("EmailID", ref fEmailID, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"JobAlertDefaultsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"JobAlertDefaultsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        string fUseReturnWithIn;
        [Size(1)]
        public string UseReturnWithIn
        {
            get { return fUseReturnWithIn; }
            set { SetPropertyValue<string>("UseReturnWithIn", ref fUseReturnWithIn, value); }
        }
    }

}
