//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class JobEquipment : XPLiteObject
    {
        int fn_JobEquipmentID;
        [Key(true)]
        public int n_JobEquipmentID
        {
            get { return fn_JobEquipmentID; }
            set { SetPropertyValue<int>("n_JobEquipmentID", ref fn_JobEquipmentID, value); }
        }
        Jobs fn_JobID;
        [Association(@"JobEquipmentReferencesJobs")]
        public Jobs n_JobID
        {
            get { return fn_JobID; }
            set { SetPropertyValue<Jobs>("n_JobID", ref fn_JobID, value); }
        }
        Jobsteps fn_jobstepid;
        [Association(@"JobEquipmentReferencesJobsteps")]
        public Jobsteps n_jobstepid
        {
            get { return fn_jobstepid; }
            set { SetPropertyValue<Jobsteps>("n_jobstepid", ref fn_jobstepid, value); }
        }
        MaintenanceObjects fn_MaintObjectID;
        [Association(@"JobEquipmentReferencesMaintenanceObjects")]
        public MaintenanceObjects n_MaintObjectID
        {
            get { return fn_MaintObjectID; }
            set { SetPropertyValue<MaintenanceObjects>("n_MaintObjectID", ref fn_MaintObjectID, value); }
        }
        decimal fEquipCost;
        public decimal EquipCost
        {
            get { return fEquipCost; }
            set { SetPropertyValue<decimal>("EquipCost", ref fEquipCost, value); }
        }
        string fEquipDescr;
        [Size(254)]
        public string EquipDescr
        {
            get { return fEquipDescr; }
            set { SetPropertyValue<string>("EquipDescr", ref fEquipDescr, value); }
        }
        string fMiscellaneousReference;
        [Size(30)]
        public string MiscellaneousReference
        {
            get { return fMiscellaneousReference; }
            set { SetPropertyValue<string>("MiscellaneousReference", ref fMiscellaneousReference, value); }
        }
        decimal fqtyused;
        public decimal qtyused
        {
            get { return fqtyused; }
            set { SetPropertyValue<decimal>("qtyused", ref fqtyused, value); }
        }
        decimal fqtyplanned;
        public decimal qtyplanned
        {
            get { return fqtyplanned; }
            set { SetPropertyValue<decimal>("qtyplanned", ref fqtyplanned, value); }
        }
        int fDMRKey;
        public int DMRKey
        {
            get { return fDMRKey; }
            set { SetPropertyValue<int>("DMRKey", ref fDMRKey, value); }
        }
        DateTime fWorkDate;
        public DateTime WorkDate
        {
            get { return fWorkDate; }
            set { SetPropertyValue<DateTime>("WorkDate", ref fWorkDate, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"JobEquipmentReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"JobEquipmentReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
        decimal fstart_meter;
        public decimal start_meter
        {
            get { return fstart_meter; }
            set { SetPropertyValue<decimal>("start_meter", ref fstart_meter, value); }
        }
        decimal fend_meter;
        public decimal end_meter
        {
            get { return fend_meter; }
            set { SetPropertyValue<decimal>("end_meter", ref fend_meter, value); }
        }
        [Association(@"time_batch_equipReferencesJobEquipment", typeof(time_batch_equip))]
        public XPCollection<time_batch_equip> time_batch_equips { get { return GetCollection<time_batch_equip>("time_batch_equips"); } }
    }

}
