//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class JobOther : XPLiteObject
    {
        int fn_JobOtherID;
        [Key(true)]
        public int n_JobOtherID
        {
            get { return fn_JobOtherID; }
            set { SetPropertyValue<int>("n_JobOtherID", ref fn_JobOtherID, value); }
        }
        Jobs fn_JobID;
        [Association(@"JobOtherReferencesJobs")]
        public Jobs n_JobID
        {
            get { return fn_JobID; }
            set { SetPropertyValue<Jobs>("n_JobID", ref fn_JobID, value); }
        }
        Jobsteps fn_JobStepID;
        [Association(@"JobOtherReferencesJobsteps")]
        public Jobsteps n_JobStepID
        {
            get { return fn_JobStepID; }
            set { SetPropertyValue<Jobsteps>("n_JobStepID", ref fn_JobStepID, value); }
        }
        string fOtherDescr;
        [Size(254)]
        public string OtherDescr
        {
            get { return fOtherDescr; }
            set { SetPropertyValue<string>("OtherDescr", ref fOtherDescr, value); }
        }
        decimal fOtherCost;
        public decimal OtherCost
        {
            get { return fOtherCost; }
            set { SetPropertyValue<decimal>("OtherCost", ref fOtherCost, value); }
        }
        string fMiscellaneousReference;
        [Size(30)]
        public string MiscellaneousReference
        {
            get { return fMiscellaneousReference; }
            set { SetPropertyValue<string>("MiscellaneousReference", ref fMiscellaneousReference, value); }
        }
        decimal fqtyused;
        public decimal qtyused
        {
            get { return fqtyused; }
            set { SetPropertyValue<decimal>("qtyused", ref fqtyused, value); }
        }
        decimal fqtyplanned;
        public decimal qtyplanned
        {
            get { return fqtyplanned; }
            set { SetPropertyValue<decimal>("qtyplanned", ref fqtyplanned, value); }
        }
        int fDMRKey;
        public int DMRKey
        {
            get { return fDMRKey; }
            set { SetPropertyValue<int>("DMRKey", ref fDMRKey, value); }
        }
        DateTime fWorkDate;
        public DateTime WorkDate
        {
            get { return fWorkDate; }
            set { SetPropertyValue<DateTime>("WorkDate", ref fWorkDate, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"JobOtherReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"JobOtherReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
    }

}
