//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class JobRequesterInfo : XPLiteObject
    {
        int fn_JobRequestInfoID;
        public int n_JobRequestInfoID
        {
            get { return fn_JobRequestInfoID; }
            set { SetPropertyValue<int>("n_JobRequestInfoID", ref fn_JobRequestInfoID, value); }
        }
        string fAssignedGUID;
        [Key]
        [Size(50)]
        public string AssignedGUID
        {
            get { return fAssignedGUID; }
            set { SetPropertyValue<string>("AssignedGUID", ref fAssignedGUID, value); }
        }
        string fFirstName;
        [Size(20)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>("FirstName", ref fFirstName, value); }
        }
        string fLastName;
        [Size(25)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>("LastName", ref fLastName, value); }
        }
        string fCompanyName;
        [Size(50)]
        public string CompanyName
        {
            get { return fCompanyName; }
            set { SetPropertyValue<string>("CompanyName", ref fCompanyName, value); }
        }
        string fHomePhone;
        [Size(20)]
        public string HomePhone
        {
            get { return fHomePhone; }
            set { SetPropertyValue<string>("HomePhone", ref fHomePhone, value); }
        }
        string fCellPhone;
        [Size(20)]
        public string CellPhone
        {
            get { return fCellPhone; }
            set { SetPropertyValue<string>("CellPhone", ref fCellPhone, value); }
        }
        string fWorkPhone;
        [Size(20)]
        public string WorkPhone
        {
            get { return fWorkPhone; }
            set { SetPropertyValue<string>("WorkPhone", ref fWorkPhone, value); }
        }
        string fWorkExtension;
        [Size(5)]
        public string WorkExtension
        {
            get { return fWorkExtension; }
            set { SetPropertyValue<string>("WorkExtension", ref fWorkExtension, value); }
        }
        string fAddress1;
        [Size(40)]
        public string Address1
        {
            get { return fAddress1; }
            set { SetPropertyValue<string>("Address1", ref fAddress1, value); }
        }
        string fAddress2;
        [Size(30)]
        public string Address2
        {
            get { return fAddress2; }
            set { SetPropertyValue<string>("Address2", ref fAddress2, value); }
        }
        string fCity;
        [Size(15)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>("City", ref fCity, value); }
        }
        string fState;
        [Size(2)]
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>("State", ref fState, value); }
        }
        string fZip;
        [Size(10)]
        public string Zip
        {
            get { return fZip; }
            set { SetPropertyValue<string>("Zip", ref fZip, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"JobRequesterInfoReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"JobRequesterInfoReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        string fLocation;
        [Size(50)]
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>("Location", ref fLocation, value); }
        }
        string fCounty;
        [Size(50)]
        public string County
        {
            get { return fCounty; }
            set { SetPropertyValue<string>("County", ref fCounty, value); }
        }
        string fDamageCode;
        [Size(30)]
        public string DamageCode
        {
            get { return fDamageCode; }
            set { SetPropertyValue<string>("DamageCode", ref fDamageCode, value); }
        }
        DateTime fDamageDate;
        public DateTime DamageDate
        {
            get { return fDamageDate; }
            set { SetPropertyValue<DateTime>("DamageDate", ref fDamageDate, value); }
        }
        string fDamageDescription;
        [Size(254)]
        public string DamageDescription
        {
            get { return fDamageDescription; }
            set { SetPropertyValue<string>("DamageDescription", ref fDamageDescription, value); }
        }
        string fOwnerInfo;
        [Size(254)]
        public string OwnerInfo
        {
            get { return fOwnerInfo; }
            set { SetPropertyValue<string>("OwnerInfo", ref fOwnerInfo, value); }
        }
        string fDriverInfo;
        [Size(254)]
        public string DriverInfo
        {
            get { return fDriverInfo; }
            set { SetPropertyValue<string>("DriverInfo", ref fDriverInfo, value); }
        }
        string fVehicleInfo;
        [Size(50)]
        public string VehicleInfo
        {
            get { return fVehicleInfo; }
            set { SetPropertyValue<string>("VehicleInfo", ref fVehicleInfo, value); }
        }
        string fVehicleLicense;
        [Size(30)]
        public string VehicleLicense
        {
            get { return fVehicleLicense; }
            set { SetPropertyValue<string>("VehicleLicense", ref fVehicleLicense, value); }
        }
        string fDepartment;
        [Size(30)]
        public string Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<string>("Department", ref fDepartment, value); }
        }
        string fDepartmentID;
        [Size(30)]
        public string DepartmentID
        {
            get { return fDepartmentID; }
            set { SetPropertyValue<string>("DepartmentID", ref fDepartmentID, value); }
        }
    }

}
