//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Jobsteps : XPLiteObject
    {
        int fn_jobstepid;
        [Key(true)]
        public int n_jobstepid
        {
            get { return fn_jobstepid; }
            set { SetPropertyValue<int>("n_jobstepid", ref fn_jobstepid, value); }
        }
        Jobs fn_jobid;
        [Association(@"JobstepsReferencesJobs")]
        public Jobs n_jobid
        {
            get { return fn_jobid; }
            set { SetPropertyValue<Jobs>("n_jobid", ref fn_jobid, value); }
        }
        int fstepnumber;
        public int stepnumber
        {
            get { return fstepnumber; }
            set { SetPropertyValue<int>("stepnumber", ref fstepnumber, value); }
        }
        int fconcurwithstep;
        public int concurwithstep
        {
            get { return fconcurwithstep; }
            set { SetPropertyValue<int>("concurwithstep", ref fconcurwithstep, value); }
        }
        int ffollowstep;
        public int followstep
        {
            get { return ffollowstep; }
            set { SetPropertyValue<int>("followstep", ref ffollowstep, value); }
        }
        string fJobstepTitle;
        [Size(254)]
        public string JobstepTitle
        {
            get { return fJobstepTitle; }
            set { SetPropertyValue<string>("JobstepTitle", ref fJobstepTitle, value); }
        }
        Statuses fn_statusid;
        [Association(@"JobstepsReferencesStatuses")]
        public Statuses n_statusid
        {
            get { return fn_statusid; }
            set { SetPropertyValue<Statuses>("n_statusid", ref fn_statusid, value); }
        }
        laborclasses fn_laborclassid;
        [Association(@"JobstepsReferenceslaborclasses")]
        public laborclasses n_laborclassid
        {
            get { return fn_laborclassid; }
            set { SetPropertyValue<laborclasses>("n_laborclassid", ref fn_laborclassid, value); }
        }
        string fCompletionNotes;
        [Size(SizeAttribute.Unlimited)]
        public string CompletionNotes
        {
            get { return fCompletionNotes; }
            set { SetPropertyValue<string>("CompletionNotes", ref fCompletionNotes, value); }
        }
        string fJobstepNotes;
        [Size(SizeAttribute.Unlimited)]
        public string JobstepNotes
        {
            get { return fJobstepNotes; }
            set { SetPropertyValue<string>("JobstepNotes", ref fJobstepNotes, value); }
        }
        MaintenanceObjects fn_ServicingEquipment;
        [Association(@"JobstepsReferencesMaintenanceObjects")]
        public MaintenanceObjects n_ServicingEquipment
        {
            get { return fn_ServicingEquipment; }
            set { SetPropertyValue<MaintenanceObjects>("n_ServicingEquipment", ref fn_ServicingEquipment, value); }
        }
        groups fn_groupid;
        [Association(@"JobstepsReferencesgroups")]
        public groups n_groupid
        {
            get { return fn_groupid; }
            set { SetPropertyValue<groups>("n_groupid", ref fn_groupid, value); }
        }
        OutcomeCodes fn_OutcomeCode;
        [Association(@"JobstepsReferencesOutcomeCodes")]
        public OutcomeCodes n_OutcomeCode
        {
            get { return fn_OutcomeCode; }
            set { SetPropertyValue<OutcomeCodes>("n_OutcomeCode", ref fn_OutcomeCode, value); }
        }
        Shifts fn_shiftID;
        [Association(@"JobstepsReferencesShifts")]
        public Shifts n_shiftID
        {
            get { return fn_shiftID; }
            set { SetPropertyValue<Shifts>("n_shiftID", ref fn_shiftID, value); }
        }
        MPetUsers fn_supervisorid;
        [Association(@"JobstepsReferencesMPetUsers2")]
        public MPetUsers n_supervisorid
        {
            get { return fn_supervisorid; }
            set { SetPropertyValue<MPetUsers>("n_supervisorid", ref fn_supervisorid, value); }
        }
        decimal factualdowntime;
        public decimal actualdowntime
        {
            get { return factualdowntime; }
            set { SetPropertyValue<decimal>("actualdowntime", ref factualdowntime, value); }
        }
        decimal factuallength;
        public decimal actuallength
        {
            get { return factuallength; }
            set { SetPropertyValue<decimal>("actuallength", ref factuallength, value); }
        }
        decimal festimateddowntime;
        public decimal estimateddowntime
        {
            get { return festimateddowntime; }
            set { SetPropertyValue<decimal>("estimateddowntime", ref festimateddowntime, value); }
        }
        decimal festimatedlength;
        public decimal estimatedlength
        {
            get { return festimatedlength; }
            set { SetPropertyValue<decimal>("estimatedlength", ref festimatedlength, value); }
        }
        DateTime fOriginalStartingDate;
        public DateTime OriginalStartingDate
        {
            get { return fOriginalStartingDate; }
            set { SetPropertyValue<DateTime>("OriginalStartingDate", ref fOriginalStartingDate, value); }
        }
        DateTime fStartingDate;
        public DateTime StartingDate
        {
            get { return fStartingDate; }
            set { SetPropertyValue<DateTime>("StartingDate", ref fStartingDate, value); }
        }
        DateTime fDateTimeCompleted;
        public DateTime DateTimeCompleted
        {
            get { return fDateTimeCompleted; }
            set { SetPropertyValue<DateTime>("DateTimeCompleted", ref fDateTimeCompleted, value); }
        }
        decimal fRemainingLength;
        public decimal RemainingLength
        {
            get { return fRemainingLength; }
            set { SetPropertyValue<decimal>("RemainingLength", ref fRemainingLength, value); }
        }
        decimal fRemainingDowntime;
        public decimal RemainingDowntime
        {
            get { return fRemainingDowntime; }
            set { SetPropertyValue<decimal>("RemainingDowntime", ref fRemainingDowntime, value); }
        }
        int freturn_within;
        public int return_within
        {
            get { return freturn_within; }
            set { SetPropertyValue<int>("return_within", ref freturn_within, value); }
        }
        FundSrcCodes fn_FundSrcCodeID;
        [Association(@"JobstepsReferencesFundSrcCodes")]
        public FundSrcCodes n_FundSrcCodeID
        {
            get { return fn_FundSrcCodeID; }
            set { SetPropertyValue<FundSrcCodes>("n_FundSrcCodeID", ref fn_FundSrcCodeID, value); }
        }
        SubAssemblyNames fSubAssemblyID;
        [Association(@"JobstepsReferencesSubAssemblyNames")]
        public SubAssemblyNames SubAssemblyID
        {
            get { return fSubAssemblyID; }
            set { SetPropertyValue<SubAssemblyNames>("SubAssemblyID", ref fSubAssemblyID, value); }
        }
        Priorities fPriorityID;
        [Association(@"JobstepsReferencesPriorities")]
        public Priorities PriorityID
        {
            get { return fPriorityID; }
            set { SetPropertyValue<Priorities>("PriorityID", ref fPriorityID, value); }
        }
        JobReasons fReasoncodeID;
        [Association(@"JobstepsReferencesJobReasons")]
        public JobReasons ReasoncodeID
        {
            get { return fReasoncodeID; }
            set { SetPropertyValue<JobReasons>("ReasoncodeID", ref fReasoncodeID, value); }
        }
        string fPostNotes;
        [Size(SizeAttribute.Unlimited)]
        public string PostNotes
        {
            get { return fPostNotes; }
            set { SetPropertyValue<string>("PostNotes", ref fPostNotes, value); }
        }
        string fHistoryAuditTrail;
        [Size(SizeAttribute.Unlimited)]
        public string HistoryAuditTrail
        {
            get { return fHistoryAuditTrail; }
            set { SetPropertyValue<string>("HistoryAuditTrail", ref fHistoryAuditTrail, value); }
        }
        int fCompletedBy;
        public int CompletedBy
        {
            get { return fCompletedBy; }
            set { SetPropertyValue<int>("CompletedBy", ref fCompletedBy, value); }
        }
        WorkOperations fn_WorkTypeCodeID;
        [Association(@"JobstepsReferencesWorkOperations1")]
        public WorkOperations n_WorkTypeCodeID
        {
            get { return fn_WorkTypeCodeID; }
            set { SetPropertyValue<WorkOperations>("n_WorkTypeCodeID", ref fn_WorkTypeCodeID, value); }
        }
        MPetUsers fn_RouteToID;
        [Association(@"JobstepsReferencesMPetUsers3")]
        public MPetUsers n_RouteToID
        {
            get { return fn_RouteToID; }
            set { SetPropertyValue<MPetUsers>("n_RouteToID", ref fn_RouteToID, value); }
        }
        string fChargeTo;
        [Size(10)]
        public string ChargeTo
        {
            get { return fChargeTo; }
            set { SetPropertyValue<string>("ChargeTo", ref fChargeTo, value); }
        }
        DateTime fLast_modified;
        public DateTime Last_modified
        {
            get { return fLast_modified; }
            set { SetPropertyValue<DateTime>("Last_modified", ref fLast_modified, value); }
        }
        MPetUsers fLastModifiedBy;
        [Association(@"JobstepsReferencesMPetUsers1")]
        public MPetUsers LastModifiedBy
        {
            get { return fLastModifiedBy; }
            set { SetPropertyValue<MPetUsers>("LastModifiedBy", ref fLastModifiedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"JobstepsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        Incidents fn_IncidentLogID;
        [Association(@"JobstepsReferencesIncidents")]
        public Incidents n_IncidentLogID
        {
            get { return fn_IncidentLogID; }
            set { SetPropertyValue<Incidents>("n_IncidentLogID", ref fn_IncidentLogID, value); }
        }
        WorkOrderCodes fn_WorkOrderCodeID;
        [Association(@"JobstepsReferencesWorkOrderCodes")]
        public WorkOrderCodes n_WorkOrderCodeID
        {
            get { return fn_WorkOrderCodeID; }
            set { SetPropertyValue<WorkOrderCodes>("n_WorkOrderCodeID", ref fn_WorkOrderCodeID, value); }
        }
        WorkOperations fn_WorkOpID;
        [Association(@"JobstepsReferencesWorkOperations")]
        public WorkOperations n_WorkOpID
        {
            get { return fn_WorkOpID; }
            set { SetPropertyValue<WorkOperations>("n_WorkOpID", ref fn_WorkOpID, value); }
        }
        OrganizationCodes fn_OrganizationCodeID;
        [Association(@"JobstepsReferencesOrganizationCodes")]
        public OrganizationCodes n_OrganizationCodeID
        {
            get { return fn_OrganizationCodeID; }
            set { SetPropertyValue<OrganizationCodes>("n_OrganizationCodeID", ref fn_OrganizationCodeID, value); }
        }
        FundingGroupCodes fn_FundingGroupCodeID;
        [Association(@"JobstepsReferencesFundingGroupCodes")]
        public FundingGroupCodes n_FundingGroupCodeID
        {
            get { return fn_FundingGroupCodeID; }
            set { SetPropertyValue<FundingGroupCodes>("n_FundingGroupCodeID", ref fn_FundingGroupCodeID, value); }
        }
        ControlSections fn_ControlSectionID;
        [Association(@"JobstepsReferencesControlSections")]
        public ControlSections n_ControlSectionID
        {
            get { return fn_ControlSectionID; }
            set { SetPropertyValue<ControlSections>("n_ControlSectionID", ref fn_ControlSectionID, value); }
        }
        EquipmentNumber fn_EquipmentNumberID;
        [Association(@"JobstepsReferencesEquipmentNumber")]
        public EquipmentNumber n_EquipmentNumberID
        {
            get { return fn_EquipmentNumberID; }
            set { SetPropertyValue<EquipmentNumber>("n_EquipmentNumberID", ref fn_EquipmentNumberID, value); }
        }
        ObjectCodes fn_ObjectCodeID;
        [Association(@"JobstepsReferencesObjectCodes")]
        public ObjectCodes n_ObjectCodeID
        {
            get { return fn_ObjectCodeID; }
            set { SetPropertyValue<ObjectCodes>("n_ObjectCodeID", ref fn_ObjectCodeID, value); }
        }
        CostCodes fn_CostCodeID;
        [Association(@"JobstepsReferencesCostCodes")]
        public CostCodes n_CostCodeID
        {
            get { return fn_CostCodeID; }
            set { SetPropertyValue<CostCodes>("n_CostCodeID", ref fn_CostCodeID, value); }
        }
        string fb_IsRoutePost;
        [Size(1)]
        public string b_IsRoutePost
        {
            get { return fb_IsRoutePost; }
            set { SetPropertyValue<string>("b_IsRoutePost", ref fb_IsRoutePost, value); }
        }
        int fn_RouteJobID;
        public int n_RouteJobID
        {
            get { return fn_RouteJobID; }
            set { SetPropertyValue<int>("n_RouteJobID", ref fn_RouteJobID, value); }
        }
        [Association(@"AttachmentsReferencesJobsteps", typeof(Attachments))]
        public XPCollection<Attachments> AttachmentsCollection { get { return GetCollection<Attachments>("AttachmentsCollection"); } }
        [Association(@"JobcrewsReferencesJobsteps", typeof(Jobcrews))]
        public XPCollection<Jobcrews> JobcrewsCollection { get { return GetCollection<Jobcrews>("JobcrewsCollection"); } }
        [Association(@"JobEquipmentReferencesJobsteps", typeof(JobEquipment))]
        public XPCollection<JobEquipment> JobEquipments { get { return GetCollection<JobEquipment>("JobEquipments"); } }
        [Association(@"JobOtherReferencesJobsteps", typeof(JobOther))]
        public XPCollection<JobOther> JobOthers { get { return GetCollection<JobOther>("JobOthers"); } }
        [Association(@"JobPartsReferencesJobsteps", typeof(JobParts))]
        public XPCollection<JobParts> JobPartsCollection { get { return GetCollection<JobParts>("JobPartsCollection"); } }
        [Association(@"partxactionsReferencesJobsteps", typeof(partxactions))]
        public XPCollection<partxactions> partxactionsCollection { get { return GetCollection<partxactions>("partxactionsCollection"); } }
        [Association(@"requisitionsReferencesJobsteps", typeof(requisitions))]
        public XPCollection<requisitions> requisitionsCollection { get { return GetCollection<requisitions>("requisitionsCollection"); } }
        [Association(@"StoresIssuesReferencesJobsteps", typeof(StoresIssues))]
        public XPCollection<StoresIssues> StoresIssuesCollection { get { return GetCollection<StoresIssues>("StoresIssuesCollection"); } }
        [Association(@"UsersFlaggedRecordsReferencesJobsteps", typeof(UsersFlaggedRecords))]
        public XPCollection<UsersFlaggedRecords> UsersFlaggedRecordsCollection { get { return GetCollection<UsersFlaggedRecords>("UsersFlaggedRecordsCollection"); } }
    }

}
