//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class laborclasses : XPLiteObject
    {
        int fn_laborclassid;
        [Key(true)]
        public int n_laborclassid
        {
            get { return fn_laborclassid; }
            set { SetPropertyValue<int>("n_laborclassid", ref fn_laborclassid, value); }
        }
        string flaborclassid;
        [Size(20)]
        public string laborclassid
        {
            get { return flaborclassid; }
            set { SetPropertyValue<string>("laborclassid", ref flaborclassid, value); }
        }
        string fdescription;
        [Size(254)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        decimal frate1;
        public decimal rate1
        {
            get { return frate1; }
            set { SetPropertyValue<decimal>("rate1", ref frate1, value); }
        }
        decimal frate2;
        public decimal rate2
        {
            get { return frate2; }
            set { SetPropertyValue<decimal>("rate2", ref frate2, value); }
        }
        decimal frate3;
        public decimal rate3
        {
            get { return frate3; }
            set { SetPropertyValue<decimal>("rate3", ref frate3, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"laborclassesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"laborclassesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime flast_modified;
        public DateTime last_modified
        {
            get { return flast_modified; }
            set { SetPropertyValue<DateTime>("last_modified", ref flast_modified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        [Association(@"JobcrewsReferenceslaborclasses", typeof(Jobcrews))]
        public XPCollection<Jobcrews> JobcrewsCollection { get { return GetCollection<Jobcrews>("JobcrewsCollection"); } }
        [Association(@"JobstepsReferenceslaborclasses", typeof(Jobsteps))]
        public XPCollection<Jobsteps> JobstepsCollection { get { return GetCollection<Jobsteps>("JobstepsCollection"); } }
        [Association(@"ObjectTasksReferenceslaborclasses", typeof(ObjectTasks))]
        public XPCollection<ObjectTasks> ObjectTasksCollection { get { return GetCollection<ObjectTasks>("ObjectTasksCollection"); } }
        [Association(@"taskcrewsReferenceslaborclasses", typeof(taskcrews))]
        public XPCollection<taskcrews> taskcrewsCollection { get { return GetCollection<taskcrews>("taskcrewsCollection"); } }
        [Association(@"TestpointsReferenceslaborclasses", typeof(Testpoints))]
        public XPCollection<Testpoints> TestpointsCollection { get { return GetCollection<Testpoints>("TestpointsCollection"); } }
    }

}
