//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Manufacturers : XPLiteObject
    {
        int fn_mfgid;
        [Key(true)]
        public int n_mfgid
        {
            get { return fn_mfgid; }
            set { SetPropertyValue<int>("n_mfgid", ref fn_mfgid, value); }
        }
        string fmfgid;
        [Size(10)]
        public string mfgid
        {
            get { return fmfgid; }
            set { SetPropertyValue<string>("mfgid", ref fmfgid, value); }
        }
        string fdescription;
        [Size(254)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        string faddress1;
        [Size(40)]
        public string address1
        {
            get { return faddress1; }
            set { SetPropertyValue<string>("address1", ref faddress1, value); }
        }
        string faddress2;
        [Size(30)]
        public string address2
        {
            get { return faddress2; }
            set { SetPropertyValue<string>("address2", ref faddress2, value); }
        }
        string fcity;
        [Size(15)]
        public string city
        {
            get { return fcity; }
            set { SetPropertyValue<string>("city", ref fcity, value); }
        }
        string fcontact;
        [Size(20)]
        public string contact
        {
            get { return fcontact; }
            set { SetPropertyValue<string>("contact", ref fcontact, value); }
        }
        string fcountry;
        [Size(10)]
        public string country
        {
            get { return fcountry; }
            set { SetPropertyValue<string>("country", ref fcountry, value); }
        }
        string fextension;
        [Size(10)]
        public string extension
        {
            get { return fextension; }
            set { SetPropertyValue<string>("extension", ref fextension, value); }
        }
        string ffax;
        [Size(20)]
        public string fax
        {
            get { return ffax; }
            set { SetPropertyValue<string>("fax", ref ffax, value); }
        }
        string fnotes;
        [Size(254)]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        string fphone;
        [Size(20)]
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>("phone", ref fphone, value); }
        }
        string fstate;
        [Size(2)]
        public string state
        {
            get { return fstate; }
            set { SetPropertyValue<string>("state", ref fstate, value); }
        }
        decimal ftax_pct;
        public decimal tax_pct
        {
            get { return ftax_pct; }
            set { SetPropertyValue<decimal>("tax_pct", ref ftax_pct, value); }
        }
        string fzip;
        [Size(10)]
        public string zip
        {
            get { return fzip; }
            set { SetPropertyValue<string>("zip", ref fzip, value); }
        }
        string fWebsiteURL;
        [Size(254)]
        public string WebsiteURL
        {
            get { return fWebsiteURL; }
            set { SetPropertyValue<string>("WebsiteURL", ref fWebsiteURL, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ManufacturersReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ManufacturersReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime flast_modified;
        public DateTime last_modified
        {
            get { return flast_modified; }
            set { SetPropertyValue<DateTime>("last_modified", ref flast_modified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        string fEmailAddress;
        [Size(254)]
        public string EmailAddress
        {
            get { return fEmailAddress; }
            set { SetPropertyValue<string>("EmailAddress", ref fEmailAddress, value); }
        }
        [Association(@"CycleCountsReferencesManufacturers", typeof(CycleCounts))]
        public XPCollection<CycleCounts> CycleCountsCollection { get { return GetCollection<CycleCounts>("CycleCountsCollection"); } }
        [Association(@"MaintenanceObjectsReferencesManufacturers", typeof(MaintenanceObjects))]
        public XPCollection<MaintenanceObjects> MaintenanceObjectsCollection { get { return GetCollection<MaintenanceObjects>("MaintenanceObjectsCollection"); } }
        [Association(@"MasterpartsReferencesManufacturers", typeof(Masterparts))]
        public XPCollection<Masterparts> MasterpartsCollection { get { return GetCollection<Masterparts>("MasterpartsCollection"); } }
        [Association(@"MfgPartsReferencesManufacturers", typeof(MfgParts))]
        public XPCollection<MfgParts> MfgPartsCollection { get { return GetCollection<MfgParts>("MfgPartsCollection"); } }
        [Association(@"VendorPartsReferencesManufacturers", typeof(VendorParts))]
        public XPCollection<VendorParts> VendorPartsCollection { get { return GetCollection<VendorParts>("VendorPartsCollection"); } }
    }

}
