//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class MilePostDirections : XPLiteObject
    {
        int fn_MilePostDirectionID;
        [Key(true)]
        public int n_MilePostDirectionID
        {
            get { return fn_MilePostDirectionID; }
            set { SetPropertyValue<int>("n_MilePostDirectionID", ref fn_MilePostDirectionID, value); }
        }
        string fMilePostDirectionID;
        [Size(30)]
        public string MilePostDirectionID
        {
            get { return fMilePostDirectionID; }
            set { SetPropertyValue<string>("MilePostDirectionID", ref fMilePostDirectionID, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"MilePostDirectionsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"MilePostDirectionsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        [Association(@"FieldDataCollectionReferencesMilePostDirections", typeof(FieldDataCollection))]
        public XPCollection<FieldDataCollection> FieldDataCollections { get { return GetCollection<FieldDataCollection>("FieldDataCollections"); } }
        [Association(@"JobsReferencesMilePostDirections", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection { get { return GetCollection<Jobs>("JobsCollection"); } }
        [Association(@"MaintenanceObjectsReferencesMilePostDirections", typeof(MaintenanceObjects))]
        public XPCollection<MaintenanceObjects> MaintenanceObjectsCollection { get { return GetCollection<MaintenanceObjects>("MaintenanceObjectsCollection"); } }
    }

}
