//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class MPETExeVersion : XPLiteObject
    {
        string fMPETExeVersion1;
        [Size(50)]
        [Persistent(@"MPETExeVersion")]
        public string MPETExeVersion1
        {
            get { return fMPETExeVersion1; }
            set { SetPropertyValue<string>("MPETExeVersion1", ref fMPETExeVersion1, value); }
        }
        int fJobPoolType;
        public int JobPoolType
        {
            get { return fJobPoolType; }
            set { SetPropertyValue<int>("JobPoolType", ref fJobPoolType, value); }
        }
        string fAttachmentFolder;
        [Size(2048)]
        public string AttachmentFolder
        {
            get { return fAttachmentFolder; }
            set { SetPropertyValue<string>("AttachmentFolder", ref fAttachmentFolder, value); }
        }
        string fProceduresFolder;
        [Size(2048)]
        public string ProceduresFolder
        {
            get { return fProceduresFolder; }
            set { SetPropertyValue<string>("ProceduresFolder", ref fProceduresFolder, value); }
        }
        MPetUsers fPMGeneratorUserID;
        [Association(@"MPETExeVersionReferencesMPetUsers")]
        public MPetUsers PMGeneratorUserID
        {
            get { return fPMGeneratorUserID; }
            set { SetPropertyValue<MPetUsers>("PMGeneratorUserID", ref fPMGeneratorUserID, value); }
        }
        string fEXEUserLicenseKey;
        [Size(254)]
        public string EXEUserLicenseKey
        {
            get { return fEXEUserLicenseKey; }
            set { SetPropertyValue<string>("EXEUserLicenseKey", ref fEXEUserLicenseKey, value); }
        }
        string fFirstUsagePassword;
        [Size(4000)]
        public string FirstUsagePassword
        {
            get { return fFirstUsagePassword; }
            set { SetPropertyValue<string>("FirstUsagePassword", ref fFirstUsagePassword, value); }
        }
        string fEncryptionKey;
        [Size(500)]
        public string EncryptionKey
        {
            get { return fEncryptionKey; }
            set { SetPropertyValue<string>("EncryptionKey", ref fEncryptionKey, value); }
        }
        string fEncryptionIV;
        [Size(50)]
        public string EncryptionIV
        {
            get { return fEncryptionIV; }
            set { SetPropertyValue<string>("EncryptionIV", ref fEncryptionIV, value); }
        }
        string fActiveDirectoryInUse;
        [Size(1)]
        public string ActiveDirectoryInUse
        {
            get { return fActiveDirectoryInUse; }
            set { SetPropertyValue<string>("ActiveDirectoryInUse", ref fActiveDirectoryInUse, value); }
        }
        string fADAccount;
        [Size(4000)]
        public string ADAccount
        {
            get { return fADAccount; }
            set { SetPropertyValue<string>("ADAccount", ref fADAccount, value); }
        }
        string fADAccountPWD;
        [Size(4000)]
        public string ADAccountPWD
        {
            get { return fADAccountPWD; }
            set { SetPropertyValue<string>("ADAccountPWD", ref fADAccountPWD, value); }
        }
        string fADLoginGroup;
        [Size(4000)]
        public string ADLoginGroup
        {
            get { return fADLoginGroup; }
            set { SetPropertyValue<string>("ADLoginGroup", ref fADLoginGroup, value); }
        }
        string fADLDAPPath;
        [Size(4000)]
        public string ADLDAPPath
        {
            get { return fADLDAPPath; }
            set { SetPropertyValue<string>("ADLDAPPath", ref fADLDAPPath, value); }
        }
        string fAutoCheckInOnReceipt;
        [Size(1)]
        public string AutoCheckInOnReceipt
        {
            get { return fAutoCheckInOnReceipt; }
            set { SetPropertyValue<string>("AutoCheckInOnReceipt", ref fAutoCheckInOnReceipt, value); }
        }
        string fPostWithOutValidation;
        [Size(1)]
        public string PostWithOutValidation
        {
            get { return fPostWithOutValidation; }
            set { SetPropertyValue<string>("PostWithOutValidation", ref fPostWithOutValidation, value); }
        }
        string fUseSystemReports;
        [Size(1)]
        public string UseSystemReports
        {
            get { return fUseSystemReports; }
            set { SetPropertyValue<string>("UseSystemReports", ref fUseSystemReports, value); }
        }
        string fEmailEnabled;
        [Size(1)]
        public string EmailEnabled
        {
            get { return fEmailEnabled; }
            set { SetPropertyValue<string>("EmailEnabled", ref fEmailEnabled, value); }
        }
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        string fValidateStorerooms;
        [Size(1)]
        public string ValidateStorerooms
        {
            get { return fValidateStorerooms; }
            set { SetPropertyValue<string>("ValidateStorerooms", ref fValidateStorerooms, value); }
        }
        string fValidateWorkOps;
        [Size(1)]
        public string ValidateWorkOps
        {
            get { return fValidateWorkOps; }
            set { SetPropertyValue<string>("ValidateWorkOps", ref fValidateWorkOps, value); }
        }
        decimal fDefaultOverheadRate;
        public decimal DefaultOverheadRate
        {
            get { return fDefaultOverheadRate; }
            set { SetPropertyValue<decimal>("DefaultOverheadRate", ref fDefaultOverheadRate, value); }
        }
        string fUseSimpleCostLinking;
        [Size(1)]
        public string UseSimpleCostLinking
        {
            get { return fUseSimpleCostLinking; }
            set { SetPropertyValue<string>("UseSimpleCostLinking", ref fUseSimpleCostLinking, value); }
        }
        int fSystemLeadTimeDefault;
        public int SystemLeadTimeDefault
        {
            get { return fSystemLeadTimeDefault; }
            set { SetPropertyValue<int>("SystemLeadTimeDefault", ref fSystemLeadTimeDefault, value); }
        }
        string fReconciliationDefaultCode;
        public string ReconciliationDefaultCode
        {
            get { return fReconciliationDefaultCode; }
            set { SetPropertyValue<string>("ReconciliationDefaultCode", ref fReconciliationDefaultCode, value); }
        }
        string fPostToRouteMembers;
        [Size(1)]
        public string PostToRouteMembers
        {
            get { return fPostToRouteMembers; }
            set { SetPropertyValue<string>("PostToRouteMembers", ref fPostToRouteMembers, value); }
        }
        string fExternalPurchaseProcessing;
        [Size(1)]
        public string ExternalPurchaseProcessing
        {
            get { return fExternalPurchaseProcessing; }
            set { SetPropertyValue<string>("ExternalPurchaseProcessing", ref fExternalPurchaseProcessing, value); }
        }
        string fTimecardInventoryProcessing;
        [Size(1)]
        public string TimecardInventoryProcessing
        {
            get { return fTimecardInventoryProcessing; }
            set { SetPropertyValue<string>("TimecardInventoryProcessing", ref fTimecardInventoryProcessing, value); }
        }
        string fTaxableEnvironment;
        [Size(1)]
        public string TaxableEnvironment
        {
            get { return fTaxableEnvironment; }
            set { SetPropertyValue<string>("TaxableEnvironment", ref fTaxableEnvironment, value); }
        }
        string fAzureHostedAttachments;
        [Size(1)]
        public string AzureHostedAttachments
        {
            get { return fAzureHostedAttachments; }
            set { SetPropertyValue<string>("AzureHostedAttachments", ref fAzureHostedAttachments, value); }
        }
        string fLockStartDateToAdmin;
        [Size(1)]
        public string LockStartDateToAdmin
        {
            get { return fLockStartDateToAdmin; }
            set { SetPropertyValue<string>("LockStartDateToAdmin", ref fLockStartDateToAdmin, value); }
        }
        string fLockReturnWithinToAdmin;
        [Size(1)]
        public string LockReturnWithinToAdmin
        {
            get { return fLockReturnWithinToAdmin; }
            set { SetPropertyValue<string>("LockReturnWithinToAdmin", ref fLockReturnWithinToAdmin, value); }
        }
        string fLockSupervisorToAdmin;
        [Size(1)]
        public string LockSupervisorToAdmin
        {
            get { return fLockSupervisorToAdmin; }
            set { SetPropertyValue<string>("LockSupervisorToAdmin", ref fLockSupervisorToAdmin, value); }
        }
        string fLockStartDateToSupervisor;
        [Size(1)]
        public string LockStartDateToSupervisor
        {
            get { return fLockStartDateToSupervisor; }
            set { SetPropertyValue<string>("LockStartDateToSupervisor", ref fLockStartDateToSupervisor, value); }
        }
        string fLockReturnWithinToSupervisor;
        [Size(1)]
        public string LockReturnWithinToSupervisor
        {
            get { return fLockReturnWithinToSupervisor; }
            set { SetPropertyValue<string>("LockReturnWithinToSupervisor", ref fLockReturnWithinToSupervisor, value); }
        }
        string fLockSupervisorToSupervisor;
        [Size(1)]
        public string LockSupervisorToSupervisor
        {
            get { return fLockSupervisorToSupervisor; }
            set { SetPropertyValue<string>("LockSupervisorToSupervisor", ref fLockSupervisorToSupervisor, value); }
        }
        string fAutoCompleteJobMembers;
        [Size(1)]
        public string AutoCompleteJobMembers
        {
            get { return fAutoCompleteJobMembers; }
            set { SetPropertyValue<string>("AutoCompleteJobMembers", ref fAutoCompleteJobMembers, value); }
        }
        string fAutoFillJobMemberDates;
        [Size(1)]
        public string AutoFillJobMemberDates
        {
            get { return fAutoFillJobMemberDates; }
            set { SetPropertyValue<string>("AutoFillJobMemberDates", ref fAutoFillJobMemberDates, value); }
        }
        string fWarnForNonJobMemberCompletion;
        [Size(1)]
        public string WarnForNonJobMemberCompletion
        {
            get { return fWarnForNonJobMemberCompletion; }
            set { SetPropertyValue<string>("WarnForNonJobMemberCompletion", ref fWarnForNonJobMemberCompletion, value); }
        }
        string fUseTimecardGroupLock;
        [Size(1)]
        public string UseTimecardGroupLock
        {
            get { return fUseTimecardGroupLock; }
            set { SetPropertyValue<string>("UseTimecardGroupLock", ref fUseTimecardGroupLock, value); }
        }
    }

}
