//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class MultiDBUsers : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        DatabaseConnections fDatabaseID;
        [Association(@"MultiDBUsersReferencesDatabaseConnections")]
        public DatabaseConnections DatabaseID
        {
            get { return fDatabaseID; }
            set { SetPropertyValue<DatabaseConnections>("DatabaseID", ref fDatabaseID, value); }
        }
        MPetUsers fUserID;
        [Association(@"MultiDBUsersReferencesMPetUsers")]
        public MPetUsers UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<MPetUsers>("UserID", ref fUserID, value); }
        }
        string fLockedOut;
        [Size(1)]
        public string LockedOut
        {
            get { return fLockedOut; }
            set { SetPropertyValue<string>("LockedOut", ref fLockedOut, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"MultiDBUsersReferencesMPetUsers1")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"MultiDBUsersReferencesMPetUsers2")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
    }

}
