//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class ObjectTasks : XPLiteObject
    {
        int fn_objtaskid;
        [Key(true)]
        public int n_objtaskid
        {
            get { return fn_objtaskid; }
            set { SetPropertyValue<int>("n_objtaskid", ref fn_objtaskid, value); }
        }
        groups fn_groupid;
        [Association(@"ObjectTasksReferencesgroups")]
        public groups n_groupid
        {
            get { return fn_groupid; }
            set { SetPropertyValue<groups>("n_groupid", ref fn_groupid, value); }
        }
        JobReasons fn_jobreasonid;
        [Association(@"ObjectTasksReferencesJobReasons")]
        public JobReasons n_jobreasonid
        {
            get { return fn_jobreasonid; }
            set { SetPropertyValue<JobReasons>("n_jobreasonid", ref fn_jobreasonid, value); }
        }
        laborclasses fn_laborclassid;
        [Association(@"ObjectTasksReferenceslaborclasses")]
        public laborclasses n_laborclassid
        {
            get { return fn_laborclassid; }
            set { SetPropertyValue<laborclasses>("n_laborclassid", ref fn_laborclassid, value); }
        }
        MaintenanceObjects fn_objectid;
        [Association(@"ObjectTasksReferencesMaintenanceObjects")]
        public MaintenanceObjects n_objectid
        {
            get { return fn_objectid; }
            set { SetPropertyValue<MaintenanceObjects>("n_objectid", ref fn_objectid, value); }
        }
        objecttypes fn_objtypetaskid;
        [Association(@"ObjectTasksReferencesobjecttypes")]
        public objecttypes n_objtypetaskid
        {
            get { return fn_objtypetaskid; }
            set { SetPropertyValue<objecttypes>("n_objtypetaskid", ref fn_objtypetaskid, value); }
        }
        groups fn_ownerid;
        [Association(@"ObjectTasksReferencesgroups1")]
        public groups n_ownerid
        {
            get { return fn_ownerid; }
            set { SetPropertyValue<groups>("n_ownerid", ref fn_ownerid, value); }
        }
        Priorities fn_priorityid;
        [Association(@"ObjectTasksReferencesPriorities")]
        public Priorities n_priorityid
        {
            get { return fn_priorityid; }
            set { SetPropertyValue<Priorities>("n_priorityid", ref fn_priorityid, value); }
        }
        Shifts fn_shiftid;
        [Association(@"ObjectTasksReferencesShifts")]
        public Shifts n_shiftid
        {
            get { return fn_shiftid; }
            set { SetPropertyValue<Shifts>("n_shiftid", ref fn_shiftid, value); }
        }
        MPetUsers fn_supervisorid;
        [Association(@"ObjectTasksReferencesMPetUsers2")]
        public MPetUsers n_supervisorid
        {
            get { return fn_supervisorid; }
            set { SetPropertyValue<MPetUsers>("n_supervisorid", ref fn_supervisorid, value); }
        }
        Tasks fn_taskid;
        [Association(@"ObjectTasksReferencesTasks")]
        public Tasks n_taskid
        {
            get { return fn_taskid; }
            set { SetPropertyValue<Tasks>("n_taskid", ref fn_taskid, value); }
        }
        WorkOperations fn_worktypeid;
        [Association(@"ObjectTasksReferencesWorkOperations")]
        public WorkOperations n_worktypeid
        {
            get { return fn_worktypeid; }
            set { SetPropertyValue<WorkOperations>("n_worktypeid", ref fn_worktypeid, value); }
        }
        SubAssemblyNames fnSubAssemblyID;
        [Association(@"ObjectTasksReferencesSubAssemblyNames")]
        public SubAssemblyNames nSubAssemblyID
        {
            get { return fnSubAssemblyID; }
            set { SetPropertyValue<SubAssemblyNames>("nSubAssemblyID", ref fnSubAssemblyID, value); }
        }
        DateTime fbegindate;
        public DateTime begindate
        {
            get { return fbegindate; }
            set { SetPropertyValue<DateTime>("begindate", ref fbegindate, value); }
        }
        string fb_disabled;
        [Size(1)]
        public string b_disabled
        {
            get { return fb_disabled; }
            set { SetPropertyValue<string>("b_disabled", ref fb_disabled, value); }
        }
        string fb_fixedinterval;
        [Size(1)]
        public string b_fixedinterval
        {
            get { return fb_fixedinterval; }
            set { SetPropertyValue<string>("b_fixedinterval", ref fb_fixedinterval, value); }
        }
        string fb_seasonal;
        [Size(1)]
        public string b_seasonal
        {
            get { return fb_seasonal; }
            set { SetPropertyValue<string>("b_seasonal", ref fb_seasonal, value); }
        }
        DateTime fdatelastdone;
        public DateTime datelastdone
        {
            get { return fdatelastdone; }
            set { SetPropertyValue<DateTime>("datelastdone", ref fdatelastdone, value); }
        }
        int fendday;
        public int endday
        {
            get { return fendday; }
            set { SetPropertyValue<int>("endday", ref fendday, value); }
        }
        int fendmo;
        public int endmo
        {
            get { return fendmo; }
            set { SetPropertyValue<int>("endmo", ref fendmo, value); }
        }
        int fevery;
        public int every
        {
            get { return fevery; }
            set { SetPropertyValue<int>("every", ref fevery, value); }
        }
        string fmm_dd_of_yr;
        [Size(5)]
        public string mm_dd_of_yr
        {
            get { return fmm_dd_of_yr; }
            set { SetPropertyValue<string>("mm_dd_of_yr", ref fmm_dd_of_yr, value); }
        }
        int fon_day_of_month;
        public int on_day_of_month
        {
            get { return fon_day_of_month; }
            set { SetPropertyValue<int>("on_day_of_month", ref fon_day_of_month, value); }
        }
        string fon_day_of_week;
        [Size(3)]
        public string on_day_of_week
        {
            get { return fon_day_of_week; }
            set { SetPropertyValue<string>("on_day_of_week", ref fon_day_of_week, value); }
        }
        decimal fpoint1last;
        public decimal point1last
        {
            get { return fpoint1last; }
            set { SetPropertyValue<decimal>("point1last", ref fpoint1last, value); }
        }
        decimal fpoint1trigger;
        public decimal point1trigger
        {
            get { return fpoint1trigger; }
            set { SetPropertyValue<decimal>("point1trigger", ref fpoint1trigger, value); }
        }
        decimal fpoint2last;
        public decimal point2last
        {
            get { return fpoint2last; }
            set { SetPropertyValue<decimal>("point2last", ref fpoint2last, value); }
        }
        decimal fpoint2trigger;
        public decimal point2trigger
        {
            get { return fpoint2trigger; }
            set { SetPropertyValue<decimal>("point2trigger", ref fpoint2trigger, value); }
        }
        decimal fpoint3last;
        public decimal point3last
        {
            get { return fpoint3last; }
            set { SetPropertyValue<decimal>("point3last", ref fpoint3last, value); }
        }
        decimal fpoint3trigger;
        public decimal point3trigger
        {
            get { return fpoint3trigger; }
            set { SetPropertyValue<decimal>("point3trigger", ref fpoint3trigger, value); }
        }
        string fshutdown_code;
        [Size(10)]
        public string shutdown_code
        {
            get { return fshutdown_code; }
            set { SetPropertyValue<string>("shutdown_code", ref fshutdown_code, value); }
        }
        int fdefer_days;
        public int defer_days
        {
            get { return fdefer_days; }
            set { SetPropertyValue<int>("defer_days", ref fdefer_days, value); }
        }
        int freturn_within;
        public int return_within
        {
            get { return freturn_within; }
            set { SetPropertyValue<int>("return_within", ref freturn_within, value); }
        }
        int fstartday;
        public int startday
        {
            get { return fstartday; }
            set { SetPropertyValue<int>("startday", ref fstartday, value); }
        }
        int fstartmo;
        public int startmo
        {
            get { return fstartmo; }
            set { SetPropertyValue<int>("startmo", ref fstartmo, value); }
        }
        DateTime fstarttime;
        public DateTime starttime
        {
            get { return fstarttime; }
            set { SetPropertyValue<DateTime>("starttime", ref fstarttime, value); }
        }
        string ftime_units;
        [Size(10)]
        public string time_units
        {
            get { return ftime_units; }
            set { SetPropertyValue<string>("time_units", ref ftime_units, value); }
        }
        int fpending_delete;
        public int pending_delete
        {
            get { return fpending_delete; }
            set { SetPropertyValue<int>("pending_delete", ref fpending_delete, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ObjectTasksReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ObjectTasksReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
        [Association(@"JobsReferencesObjectTasks", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection { get { return GetCollection<Jobs>("JobsCollection"); } }
    }

}
