//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class ObjectParts : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        MaintenanceObjects fobjectid;
        [Association(@"ObjectPartsReferencesMaintenanceObjects")]
        public MaintenanceObjects objectid
        {
            get { return fobjectid; }
            set { SetPropertyValue<MaintenanceObjects>("objectid", ref fobjectid, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        Masterparts fmasterpartid;
        [Association(@"ObjectPartsReferencesMasterparts")]
        public Masterparts masterpartid
        {
            get { return fmasterpartid; }
            set { SetPropertyValue<Masterparts>("masterpartid", ref fmasterpartid, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>("Notes", ref fNotes, value); }
        }
        string fCritical;
        [Size(1)]
        public string Critical
        {
            get { return fCritical; }
            set { SetPropertyValue<string>("Critical", ref fCritical, value); }
        }
        int fqty;
        public int qty
        {
            get { return fqty; }
            set { SetPropertyValue<int>("qty", ref fqty, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ObjectPartsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ObjectPartsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
    }

}
