//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class OptDropdownValues : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        int fValueDefinitionID;
        public int ValueDefinitionID
        {
            get { return fValueDefinitionID; }
            set { SetPropertyValue<int>("ValueDefinitionID", ref fValueDefinitionID, value); }
        }
        string fTextValue;
        [Size(4000)]
        public string TextValue
        {
            get { return fTextValue; }
            set { SetPropertyValue<string>("TextValue", ref fTextValue, value); }
        }
        int fTypeOfData;
        public int TypeOfData
        {
            get { return fTypeOfData; }
            set { SetPropertyValue<int>("TypeOfData", ref fTypeOfData, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"OptDropdownValuesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"OptDropdownValuesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_modified;
        public DateTime Last_modified
        {
            get { return fLast_modified; }
            set { SetPropertyValue<DateTime>("Last_modified", ref fLast_modified, value); }
        }
    }

}
