//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class OptionalValues : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        int fValueDefinitionID;
        public int ValueDefinitionID
        {
            get { return fValueDefinitionID; }
            set { SetPropertyValue<int>("ValueDefinitionID", ref fValueDefinitionID, value); }
        }
        int fAssociatedTableKey;
        public int AssociatedTableKey
        {
            get { return fAssociatedTableKey; }
            set { SetPropertyValue<int>("AssociatedTableKey", ref fAssociatedTableKey, value); }
        }
        string fAssociatedGuid;
        [Size(50)]
        public string AssociatedGuid
        {
            get { return fAssociatedGuid; }
            set { SetPropertyValue<string>("AssociatedGuid", ref fAssociatedGuid, value); }
        }
        string fOptionalValue;
        [Size(4000)]
        public string OptionalValue
        {
            get { return fOptionalValue; }
            set { SetPropertyValue<string>("OptionalValue", ref fOptionalValue, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"OptionalValuesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"OptionalValuesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
    }

}
