//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class OutcomeCodes : XPLiteObject
    {
        int fn_outcomecodeid;
        [Key(true)]
        public int n_outcomecodeid
        {
            get { return fn_outcomecodeid; }
            set { SetPropertyValue<int>("n_outcomecodeid", ref fn_outcomecodeid, value); }
        }
        string foutcomecodeid;
        [Size(10)]
        public string outcomecodeid
        {
            get { return foutcomecodeid; }
            set { SetPropertyValue<string>("outcomecodeid", ref foutcomecodeid, value); }
        }
        string fdescription;
        [Size(254)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        string fSubtractFromIssued;
        [Size(1)]
        public string SubtractFromIssued
        {
            get { return fSubtractFromIssued; }
            set { SetPropertyValue<string>("SubtractFromIssued", ref fSubtractFromIssued, value); }
        }
        string fCountAsCompleted;
        [Size(1)]
        public string CountAsCompleted
        {
            get { return fCountAsCompleted; }
            set { SetPropertyValue<string>("CountAsCompleted", ref fCountAsCompleted, value); }
        }
        string fWorkNotDone;
        [Size(1)]
        public string WorkNotDone
        {
            get { return fWorkNotDone; }
            set { SetPropertyValue<string>("WorkNotDone", ref fWorkNotDone, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"OutcomeCodesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"OutcomeCodesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        string fPostNotesRequired;
        [Size(1)]
        public string PostNotesRequired
        {
            get { return fPostNotesRequired; }
            set { SetPropertyValue<string>("PostNotesRequired", ref fPostNotesRequired, value); }
        }
        [Association(@"FieldDataCollectionReferencesOutcomeCodes", typeof(FieldDataCollection))]
        public XPCollection<FieldDataCollection> FieldDataCollections { get { return GetCollection<FieldDataCollection>("FieldDataCollections"); } }
        [Association(@"JobsReferencesOutcomeCodes", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection { get { return GetCollection<Jobs>("JobsCollection"); } }
        [Association(@"JobstepsReferencesOutcomeCodes", typeof(Jobsteps))]
        public XPCollection<Jobsteps> JobstepsCollection { get { return GetCollection<Jobsteps>("JobstepsCollection"); } }
    }

}
