//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class partxactions : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        int fn_xactionid;
        public int n_xactionid
        {
            get { return fn_xactionid; }
            set { SetPropertyValue<int>("n_xactionid", ref fn_xactionid, value); }
        }
        string fxactionnum;
        [Size(50)]
        public string xactionnum
        {
            get { return fxactionnum; }
            set { SetPropertyValue<string>("xactionnum", ref fxactionnum, value); }
        }
        Carriers fn_carrierid;
        [Association(@"partxactionsReferencesCarriers")]
        public Carriers n_carrierid
        {
            get { return fn_carrierid; }
            set { SetPropertyValue<Carriers>("n_carrierid", ref fn_carrierid, value); }
        }
        CheckInReasons fn_chkinreasonid;
        [Association(@"partxactionsReferencesCheckInReasons")]
        public CheckInReasons n_chkinreasonid
        {
            get { return fn_chkinreasonid; }
            set { SetPropertyValue<CheckInReasons>("n_chkinreasonid", ref fn_chkinreasonid, value); }
        }
        CheckOutReasons fn_chkoutreasonid;
        [Association(@"partxactionsReferencesCheckOutReasons")]
        public CheckOutReasons n_chkoutreasonid
        {
            get { return fn_chkoutreasonid; }
            set { SetPropertyValue<CheckOutReasons>("n_chkoutreasonid", ref fn_chkoutreasonid, value); }
        }
        MPetUsers fn_givenby;
        [Association(@"partxactionsReferencesMPetUsers")]
        public MPetUsers n_givenby
        {
            get { return fn_givenby; }
            set { SetPropertyValue<MPetUsers>("n_givenby", ref fn_givenby, value); }
        }
        Jobs fn_jobid;
        [Association(@"partxactionsReferencesJobs")]
        public Jobs n_jobid
        {
            get { return fn_jobid; }
            set { SetPropertyValue<Jobs>("n_jobid", ref fn_jobid, value); }
        }
        Jobsteps fn_jobstepid;
        [Association(@"partxactionsReferencesJobsteps")]
        public Jobsteps n_jobstepid
        {
            get { return fn_jobstepid; }
            set { SetPropertyValue<Jobsteps>("n_jobstepid", ref fn_jobstepid, value); }
        }
        purchaseorders fn_purchaseorderid;
        [Association(@"partxactionsReferencespurchaseorders")]
        public purchaseorders n_purchaseorderid
        {
            get { return fn_purchaseorderid; }
            set { SetPropertyValue<purchaseorders>("n_purchaseorderid", ref fn_purchaseorderid, value); }
        }
        Storerooms fn_storeroomid;
        [Association(@"partxactionsReferencesStorerooms")]
        public Storerooms n_storeroomid
        {
            get { return fn_storeroomid; }
            set { SetPropertyValue<Storerooms>("n_storeroomid", ref fn_storeroomid, value); }
        }
        MPetUsers fn_takenby;
        [Association(@"partxactionsReferencesMPetUsers3")]
        public MPetUsers n_takenby
        {
            get { return fn_takenby; }
            set { SetPropertyValue<MPetUsers>("n_takenby", ref fn_takenby, value); }
        }
        Vendors fn_vendorid;
        [Association(@"partxactionsReferencesVendors")]
        public Vendors n_vendorid
        {
            get { return fn_vendorid; }
            set { SetPropertyValue<Vendors>("n_vendorid", ref fn_vendorid, value); }
        }
        StoresIssues fn_StoresIssueID;
        [Association(@"partxactionsReferencesStoresIssues")]
        public StoresIssues n_StoresIssueID
        {
            get { return fn_StoresIssueID; }
            set { SetPropertyValue<StoresIssues>("n_StoresIssueID", ref fn_StoresIssueID, value); }
        }
        string fb_posted;
        [Size(1)]
        public string b_posted
        {
            get { return fb_posted; }
            set { SetPropertyValue<string>("b_posted", ref fb_posted, value); }
        }
        DateTime fdatereceived;
        public DateTime datereceived
        {
            get { return fdatereceived; }
            set { SetPropertyValue<DateTime>("datereceived", ref fdatereceived, value); }
        }
        string finvoicenum;
        [Size(15)]
        public string invoicenum
        {
            get { return finvoicenum; }
            set { SetPropertyValue<string>("invoicenum", ref finvoicenum, value); }
        }
        string fnotes;
        [Size(SizeAttribute.Unlimited)]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        int fn_ReceiptID;
        public int n_ReceiptID
        {
            get { return fn_ReceiptID; }
            set { SetPropertyValue<int>("n_ReceiptID", ref fn_ReceiptID, value); }
        }
        DateTime fxactiondate;
        public DateTime xactiondate
        {
            get { return fxactiondate; }
            set { SetPropertyValue<DateTime>("xactiondate", ref fxactiondate, value); }
        }
        string fxactiontype;
        [Size(50)]
        public string xactiontype
        {
            get { return fxactiontype; }
            set { SetPropertyValue<string>("xactiontype", ref fxactiontype, value); }
        }
        string fb_Canceled;
        [Size(1)]
        public string b_Canceled
        {
            get { return fb_Canceled; }
            set { SetPropertyValue<string>("b_Canceled", ref fb_Canceled, value); }
        }
        string fHistoryAuditTrail;
        [Size(SizeAttribute.Unlimited)]
        public string HistoryAuditTrail
        {
            get { return fHistoryAuditTrail; }
            set { SetPropertyValue<string>("HistoryAuditTrail", ref fHistoryAuditTrail, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"partxactionsReferencesMPetUsers1")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"partxactionsReferencesMPetUsers2")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        string fb_IsProcessed;
        [Size(1)]
        public string b_IsProcessed
        {
            get { return fb_IsProcessed; }
            set { SetPropertyValue<string>("b_IsProcessed", ref fb_IsProcessed, value); }
        }
    }

}
