//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class personskills : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        MPetUsers fn_personid;
        [Association(@"personskillsReferencesMPetUsers")]
        public MPetUsers n_personid
        {
            get { return fn_personid; }
            set { SetPropertyValue<MPetUsers>("n_personid", ref fn_personid, value); }
        }
        skills fn_skillid;
        [Association(@"personskillsReferencesskills")]
        public skills n_skillid
        {
            get { return fn_skillid; }
            set { SetPropertyValue<skills>("n_skillid", ref fn_skillid, value); }
        }
        DateTime fCertificationDate;
        public DateTime CertificationDate
        {
            get { return fCertificationDate; }
            set { SetPropertyValue<DateTime>("CertificationDate", ref fCertificationDate, value); }
        }
        DateTime fCertificationExpireDate;
        public DateTime CertificationExpireDate
        {
            get { return fCertificationExpireDate; }
            set { SetPropertyValue<DateTime>("CertificationExpireDate", ref fCertificationExpireDate, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"personskillsReferencesMPetUsers1")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"personskillsReferencesMPetUsers2")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime flast_modified;
        public DateTime last_modified
        {
            get { return flast_modified; }
            set { SetPropertyValue<DateTime>("last_modified", ref flast_modified, value); }
        }
    }

}
