//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class personclasses : XPLiteObject
    {
        int fn_personclassid;
        [Key(true)]
        public int n_personclassid
        {
            get { return fn_personclassid; }
            set { SetPropertyValue<int>("n_personclassid", ref fn_personclassid, value); }
        }
        string fpersonclassid;
        [Size(20)]
        public string personclassid
        {
            get { return fpersonclassid; }
            set { SetPropertyValue<string>("personclassid", ref fpersonclassid, value); }
        }
        string fdescription;
        [Size(254)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"personclassesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime flast_modified;
        public DateTime last_modified
        {
            get { return flast_modified; }
            set { SetPropertyValue<DateTime>("last_modified", ref flast_modified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"personclassesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
    }

}
