//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Priorities : XPLiteObject
    {
        int fn_priorityid;
        [Key(true)]
        public int n_priorityid
        {
            get { return fn_priorityid; }
            set { SetPropertyValue<int>("n_priorityid", ref fn_priorityid, value); }
        }
        string fpriorityid;
        [Size(10)]
        public string priorityid
        {
            get { return fpriorityid; }
            set { SetPropertyValue<string>("priorityid", ref fpriorityid, value); }
        }
        string fdescription;
        [Size(254)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        int fPriorityOrder;
        public int PriorityOrder
        {
            get { return fPriorityOrder; }
            set { SetPropertyValue<int>("PriorityOrder", ref fPriorityOrder, value); }
        }
        char fActive;
        public char Active
        {
            get { return fActive; }
            set { SetPropertyValue<char>("Active", ref fActive, value); }
        }
        char fSystem;
        public char System
        {
            get { return fSystem; }
            set { SetPropertyValue<char>("System", ref fSystem, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"PrioritiesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"PrioritiesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        [Association(@"FieldDataCollectionReferencesPriorities", typeof(FieldDataCollection))]
        public XPCollection<FieldDataCollection> FieldDataCollections { get { return GetCollection<FieldDataCollection>("FieldDataCollections"); } }
        [Association(@"JobsReferencesPriorities", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection { get { return GetCollection<Jobs>("JobsCollection"); } }
        [Association(@"JobsReferencesPriorities1", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection1 { get { return GetCollection<Jobs>("JobsCollection1"); } }
        [Association(@"JobstepsReferencesPriorities", typeof(Jobsteps))]
        public XPCollection<Jobsteps> JobstepsCollection { get { return GetCollection<Jobsteps>("JobstepsCollection"); } }
        [Association(@"ObjectTasksReferencesPriorities", typeof(ObjectTasks))]
        public XPCollection<ObjectTasks> ObjectTasksCollection { get { return GetCollection<ObjectTasks>("ObjectTasksCollection"); } }
    }

}
