//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class ProjectDiary : XPLiteObject
    {
        int fn_ProjectDiaryID;
        [Key(true)]
        public int n_ProjectDiaryID
        {
            get { return fn_ProjectDiaryID; }
            set { SetPropertyValue<int>("n_ProjectDiaryID", ref fn_ProjectDiaryID, value); }
        }
        string fProjectDiaryNum;
        [Size(30)]
        public string ProjectDiaryNum
        {
            get { return fProjectDiaryNum; }
            set { SetPropertyValue<string>("ProjectDiaryNum", ref fProjectDiaryNum, value); }
        }
        Projects fn_ProjectID;
        [Association(@"ProjectDiaryReferencesProjects")]
        public Projects n_ProjectID
        {
            get { return fn_ProjectID; }
            set { SetPropertyValue<Projects>("n_ProjectID", ref fn_ProjectID, value); }
        }
        MPetUsers fn_EngineerID;
        [Association(@"ProjectDiaryReferencesMPetUsers")]
        public MPetUsers n_EngineerID
        {
            get { return fn_EngineerID; }
            set { SetPropertyValue<MPetUsers>("n_EngineerID", ref fn_EngineerID, value); }
        }
        Weather fn_weatherid;
        [Association(@"ProjectDiaryReferencesWeather")]
        public Weather n_weatherid
        {
            get { return fn_weatherid; }
            set { SetPropertyValue<Weather>("n_weatherid", ref fn_weatherid, value); }
        }
        ProjectConditions fn_ProjectCondition;
        [Association(@"ProjectDiaryReferencesProjectConditions")]
        public ProjectConditions n_ProjectCondition
        {
            get { return fn_ProjectCondition; }
            set { SetPropertyValue<ProjectConditions>("n_ProjectCondition", ref fn_ProjectCondition, value); }
        }
        DateTime fWorkDate;
        public DateTime WorkDate
        {
            get { return fWorkDate; }
            set { SetPropertyValue<DateTime>("WorkDate", ref fWorkDate, value); }
        }
        DateTime fStartTime;
        public DateTime StartTime
        {
            get { return fStartTime; }
            set { SetPropertyValue<DateTime>("StartTime", ref fStartTime, value); }
        }
        DateTime fEndTime;
        public DateTime EndTime
        {
            get { return fEndTime; }
            set { SetPropertyValue<DateTime>("EndTime", ref fEndTime, value); }
        }
        CostCodes fn_CostCodeID;
        [Association(@"ProjectDiaryReferencesCostCodes")]
        public CostCodes n_CostCodeID
        {
            get { return fn_CostCodeID; }
            set { SetPropertyValue<CostCodes>("n_CostCodeID", ref fn_CostCodeID, value); }
        }
        WorkOperations fn_WorkOpID;
        [Association(@"ProjectDiaryReferencesWorkOperations")]
        public WorkOperations n_WorkOpID
        {
            get { return fn_WorkOpID; }
            set { SetPropertyValue<WorkOperations>("n_WorkOpID", ref fn_WorkOpID, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>("Notes", ref fNotes, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        int fn_DMRKey;
        public int n_DMRKey
        {
            get { return fn_DMRKey; }
            set { SetPropertyValue<int>("n_DMRKey", ref fn_DMRKey, value); }
        }
        string fBMPInspection;
        [Size(30)]
        public string BMPInspection
        {
            get { return fBMPInspection; }
            set { SetPropertyValue<string>("BMPInspection", ref fBMPInspection, value); }
        }
        string fBMPDef;
        [Size(1)]
        public string BMPDef
        {
            get { return fBMPDef; }
            set { SetPropertyValue<string>("BMPDef", ref fBMPDef, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ProjectDiaryReferencesMPetUsers1")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ProjectDiaryReferencesMPetUsers2")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        [Association(@"ProjectDiaryItemAttachmentsReferencesProjectDiary", typeof(ProjectDiaryItemAttachments))]
        public XPCollection<ProjectDiaryItemAttachments> ProjectDiaryItemAttachmentsCollection { get { return GetCollection<ProjectDiaryItemAttachments>("ProjectDiaryItemAttachmentsCollection"); } }
        [Association(@"ProjectDiaryItemEquipmentReferencesProjectDiary", typeof(ProjectDiaryItemEquipment))]
        public XPCollection<ProjectDiaryItemEquipment> ProjectDiaryItemEquipments { get { return GetCollection<ProjectDiaryItemEquipment>("ProjectDiaryItemEquipments"); } }
        [Association(@"ProjectDiaryItemPersonnelReferencesProjectDiary", typeof(ProjectDiaryItemPersonnel))]
        public XPCollection<ProjectDiaryItemPersonnel> ProjectDiaryItemPersonnels { get { return GetCollection<ProjectDiaryItemPersonnel>("ProjectDiaryItemPersonnels"); } }
        [Association(@"ProjectDiaryItemsReferencesProjectDiary", typeof(ProjectDiaryItems))]
        public XPCollection<ProjectDiaryItems> ProjectDiaryItemsCollection { get { return GetCollection<ProjectDiaryItems>("ProjectDiaryItemsCollection"); } }
        [Association(@"ProjectDiaryWeatherReferencesProjectDiary", typeof(ProjectDiaryWeather))]
        public XPCollection<ProjectDiaryWeather> ProjectDiaryWeathers { get { return GetCollection<ProjectDiaryWeather>("ProjectDiaryWeathers"); } }
        [Association(@"UsersFlaggedRecordsReferencesProjectDiary", typeof(UsersFlaggedRecords))]
        public XPCollection<UsersFlaggedRecords> UsersFlaggedRecordsCollection { get { return GetCollection<UsersFlaggedRecords>("UsersFlaggedRecordsCollection"); } }
    }

}
