//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Projects : XPLiteObject
    {
        int fn_ProjectID;
        [Key(true)]
        public int n_ProjectID
        {
            get { return fn_ProjectID; }
            set { SetPropertyValue<int>("n_ProjectID", ref fn_ProjectID, value); }
        }
        string fProjectID;
        [Size(20)]
        public string ProjectID
        {
            get { return fProjectID; }
            set { SetPropertyValue<string>("ProjectID", ref fProjectID, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        CostCodes fn_ChargeCodeID;
        [Association(@"ProjectsReferencesCostCodes")]
        public CostCodes n_ChargeCodeID
        {
            get { return fn_ChargeCodeID; }
            set { SetPropertyValue<CostCodes>("n_ChargeCodeID", ref fn_ChargeCodeID, value); }
        }
        WorkOperations fn_WorkOpID;
        [Association(@"ProjectsReferencesWorkOperations")]
        public WorkOperations n_WorkOpID
        {
            get { return fn_WorkOpID; }
            set { SetPropertyValue<WorkOperations>("n_WorkOpID", ref fn_WorkOpID, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ProjectsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ProjectsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        [Association(@"ProjectAttachmentsReferencesProjects", typeof(ProjectAttachments))]
        public XPCollection<ProjectAttachments> ProjectAttachmentsCollection { get { return GetCollection<ProjectAttachments>("ProjectAttachmentsCollection"); } }
        [Association(@"ProjectDiaryReferencesProjects", typeof(ProjectDiary))]
        public XPCollection<ProjectDiary> ProjectDiaries { get { return GetCollection<ProjectDiary>("ProjectDiaries"); } }
        [Association(@"ProjectPayItemLinksReferencesProjects", typeof(ProjectPayItemLinks))]
        public XPCollection<ProjectPayItemLinks> ProjectPayItemLinksCollection { get { return GetCollection<ProjectPayItemLinks>("ProjectPayItemLinksCollection"); } }
    }

}
