//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class purchaseorders : XPLiteObject
    {
        int fn_purchaseorderid;
        [Key(true)]
        public int n_purchaseorderid
        {
            get { return fn_purchaseorderid; }
            set { SetPropertyValue<int>("n_purchaseorderid", ref fn_purchaseorderid, value); }
        }
        string fpurchaseorderid;
        [Size(12)]
        public string purchaseorderid
        {
            get { return fpurchaseorderid; }
            set { SetPropertyValue<string>("purchaseorderid", ref fpurchaseorderid, value); }
        }
        Carriers fn_CarrierID;
        [Association(@"purchaseordersReferencesCarriers")]
        public Carriers n_CarrierID
        {
            get { return fn_CarrierID; }
            set { SetPropertyValue<Carriers>("n_CarrierID", ref fn_CarrierID, value); }
        }
        MPetUsers fn_creator;
        [Association(@"purchaseordersReferencesMPetUsers")]
        public MPetUsers n_creator
        {
            get { return fn_creator; }
            set { SetPropertyValue<MPetUsers>("n_creator", ref fn_creator, value); }
        }
        MPetUsers fn_StatusBy;
        [Association(@"purchaseordersReferencesMPetUsers2")]
        public MPetUsers n_StatusBy
        {
            get { return fn_StatusBy; }
            set { SetPropertyValue<MPetUsers>("n_StatusBy", ref fn_StatusBy, value); }
        }
        Vendors fn_vendorid;
        [Association(@"purchaseordersReferencesVendors")]
        public Vendors n_vendorid
        {
            get { return fn_vendorid; }
            set { SetPropertyValue<Vendors>("n_vendorid", ref fn_vendorid, value); }
        }
        ShipToAddresses fn_Ship2AddressID;
        [Association(@"purchaseordersReferencesShipToAddresses")]
        public ShipToAddresses n_Ship2AddressID
        {
            get { return fn_Ship2AddressID; }
            set { SetPropertyValue<ShipToAddresses>("n_Ship2AddressID", ref fn_Ship2AddressID, value); }
        }
        string fb_closed;
        [Size(1)]
        public string b_closed
        {
            get { return fb_closed; }
            set { SetPropertyValue<string>("b_closed", ref fb_closed, value); }
        }
        DateTime fcreationdate;
        public DateTime creationdate
        {
            get { return fcreationdate; }
            set { SetPropertyValue<DateTime>("creationdate", ref fcreationdate, value); }
        }
        DateTime fdateclosed;
        public DateTime dateclosed
        {
            get { return fdateclosed; }
            set { SetPropertyValue<DateTime>("dateclosed", ref fdateclosed, value); }
        }
        string fb_Taxable;
        [Size(1)]
        public string b_Taxable
        {
            get { return fb_Taxable; }
            set { SetPropertyValue<string>("b_Taxable", ref fb_Taxable, value); }
        }
        string fPurchaseAuth;
        [Size(25)]
        public string PurchaseAuth
        {
            get { return fPurchaseAuth; }
            set { SetPropertyValue<string>("PurchaseAuth", ref fPurchaseAuth, value); }
        }
        string fnotes;
        [Size(SizeAttribute.Unlimited)]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        string fFreightTerms;
        [Size(26)]
        public string FreightTerms
        {
            get { return fFreightTerms; }
            set { SetPropertyValue<string>("FreightTerms", ref fFreightTerms, value); }
        }
        string fFOB;
        [Size(26)]
        public string FOB
        {
            get { return fFOB; }
            set { SetPropertyValue<string>("FOB", ref fFOB, value); }
        }
        string fStatus;
        [Size(25)]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>("Status", ref fStatus, value); }
        }
        DateTime fStatusDate;
        public DateTime StatusDate
        {
            get { return fStatusDate; }
            set { SetPropertyValue<DateTime>("StatusDate", ref fStatusDate, value); }
        }
        string fb_FullyPriced;
        [Size(1)]
        public string b_FullyPriced
        {
            get { return fb_FullyPriced; }
            set { SetPropertyValue<string>("b_FullyPriced", ref fb_FullyPriced, value); }
        }
        string fDisposition;
        [Size(25)]
        public string Disposition
        {
            get { return fDisposition; }
            set { SetPropertyValue<string>("Disposition", ref fDisposition, value); }
        }
        string fHistoryAuditTrail;
        [Size(SizeAttribute.Unlimited)]
        public string HistoryAuditTrail
        {
            get { return fHistoryAuditTrail; }
            set { SetPropertyValue<string>("HistoryAuditTrail", ref fHistoryAuditTrail, value); }
        }
        string fb_IsCanceled;
        [Size(1)]
        public string b_IsCanceled
        {
            get { return fb_IsCanceled; }
            set { SetPropertyValue<string>("b_IsCanceled", ref fb_IsCanceled, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"purchaseordersReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        PurchaseAuthority fn_PurchaseAuthorityID;
        [Association(@"purchaseordersReferencesPurchaseAuthority")]
        public PurchaseAuthority n_PurchaseAuthorityID
        {
            get { return fn_PurchaseAuthorityID; }
            set { SetPropertyValue<PurchaseAuthority>("n_PurchaseAuthorityID", ref fn_PurchaseAuthorityID, value); }
        }
        string fnotesHistory;
        [Size(SizeAttribute.Unlimited)]
        public string notesHistory
        {
            get { return fnotesHistory; }
            set { SetPropertyValue<string>("notesHistory", ref fnotesHistory, value); }
        }
        PaymentTerms fn_PaymentTermsID;
        [Association(@"purchaseordersReferencesPaymentTerms")]
        public PaymentTerms n_PaymentTermsID
        {
            get { return fn_PaymentTermsID; }
            set { SetPropertyValue<PaymentTerms>("n_PaymentTermsID", ref fn_PaymentTermsID, value); }
        }
        FreightTerms fn_FreightTermID;
        [Association(@"purchaseordersReferencesFreightTerms")]
        public FreightTerms n_FreightTermID
        {
            get { return fn_FreightTermID; }
            set { SetPropertyValue<FreightTerms>("n_FreightTermID", ref fn_FreightTermID, value); }
        }
        FreightOnBoard fn_FreightOnBoardID;
        [Association(@"purchaseordersReferencesFreightOnBoard")]
        public FreightOnBoard n_FreightOnBoardID
        {
            get { return fn_FreightOnBoardID; }
            set { SetPropertyValue<FreightOnBoard>("n_FreightOnBoardID", ref fn_FreightOnBoardID, value); }
        }
        string fbuyersNotes;
        [Size(SizeAttribute.Unlimited)]
        public string buyersNotes
        {
            get { return fbuyersNotes; }
            set { SetPropertyValue<string>("buyersNotes", ref fbuyersNotes, value); }
        }
        string fbuyersNotesHistory;
        [Size(SizeAttribute.Unlimited)]
        public string buyersNotesHistory
        {
            get { return fbuyersNotesHistory; }
            set { SetPropertyValue<string>("buyersNotesHistory", ref fbuyersNotesHistory, value); }
        }
        string fmiscrefnum;
        [Size(254)]
        public string miscrefnum
        {
            get { return fmiscrefnum; }
            set { SetPropertyValue<string>("miscrefnum", ref fmiscrefnum, value); }
        }
        string fb_IsProcessed;
        [Size(1)]
        public string b_IsProcessed
        {
            get { return fb_IsProcessed; }
            set { SetPropertyValue<string>("b_IsProcessed", ref fb_IsProcessed, value); }
        }
        [Association(@"GriefLogsReferencespurchaseorders", typeof(GriefLogs))]
        public XPCollection<GriefLogs> GriefLogsCollection { get { return GetCollection<GriefLogs>("GriefLogsCollection"); } }
        [Association(@"partxactionsReferencespurchaseorders", typeof(partxactions))]
        public XPCollection<partxactions> partxactionsCollection { get { return GetCollection<partxactions>("partxactionsCollection"); } }
        [Association(@"PurchaseOrderAttachmentsReferencespurchaseorders", typeof(PurchaseOrderAttachments))]
        public XPCollection<PurchaseOrderAttachments> PurchaseOrderAttachmentsCollection { get { return GetCollection<PurchaseOrderAttachments>("PurchaseOrderAttachmentsCollection"); } }
        [Association(@"requisitionitemsReferencespurchaseorders", typeof(requisitionitems))]
        public XPCollection<requisitionitems> requisitionitemsCollection { get { return GetCollection<requisitionitems>("requisitionitemsCollection"); } }
        [Association(@"requisitionsReferencespurchaseorders", typeof(requisitions))]
        public XPCollection<requisitions> requisitionsCollection { get { return GetCollection<requisitions>("requisitionsCollection"); } }
        [Association(@"ShippingReportsReferencespurchaseorders", typeof(ShippingReports))]
        public XPCollection<ShippingReports> ShippingReportsCollection { get { return GetCollection<ShippingReports>("ShippingReportsCollection"); } }
        [Association(@"UsersFlaggedRecordsReferencespurchaseorders", typeof(UsersFlaggedRecords))]
        public XPCollection<UsersFlaggedRecords> UsersFlaggedRecordsCollection { get { return GetCollection<UsersFlaggedRecords>("UsersFlaggedRecordsCollection"); } }
    }

}
