//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class QueryTableHeaders : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        StoredProcsAndQueries fStoredProcOrQueryID;
        [Association(@"QueryTableHeadersReferencesStoredProcsAndQueries")]
        public StoredProcsAndQueries StoredProcOrQueryID
        {
            get { return fStoredProcOrQueryID; }
            set { SetPropertyValue<StoredProcsAndQueries>("StoredProcOrQueryID", ref fStoredProcOrQueryID, value); }
        }
        string fQueryHeader;
        [Size(50)]
        public string QueryHeader
        {
            get { return fQueryHeader; }
            set { SetPropertyValue<string>("QueryHeader", ref fQueryHeader, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"QueryTableHeadersReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"QueryTableHeadersReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
    }

}
