//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class QueryTableFields : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        string fFieldname;
        [Size(50)]
        public string Fieldname
        {
            get { return fFieldname; }
            set { SetPropertyValue<string>("Fieldname", ref fFieldname, value); }
        }
        string fTablename;
        [Size(50)]
        public string Tablename
        {
            get { return fTablename; }
            set { SetPropertyValue<string>("Tablename", ref fTablename, value); }
        }
        string fDatatype;
        [Size(20)]
        public string Datatype
        {
            get { return fDatatype; }
            set { SetPropertyValue<string>("Datatype", ref fDatatype, value); }
        }
        string fTooltip;
        [Size(254)]
        public string Tooltip
        {
            get { return fTooltip; }
            set { SetPropertyValue<string>("Tooltip", ref fTooltip, value); }
        }
        string fLabelText;
        [Size(80)]
        public string LabelText
        {
            get { return fLabelText; }
            set { SetPropertyValue<string>("LabelText", ref fLabelText, value); }
        }
        string fIsFilterable;
        [Size(1)]
        public string IsFilterable
        {
            get { return fIsFilterable; }
            set { SetPropertyValue<string>("IsFilterable", ref fIsFilterable, value); }
        }
        string fIsVisible;
        [Size(1)]
        public string IsVisible
        {
            get { return fIsVisible; }
            set { SetPropertyValue<string>("IsVisible", ref fIsVisible, value); }
        }
        int fFieldLength;
        public int FieldLength
        {
            get { return fFieldLength; }
            set { SetPropertyValue<int>("FieldLength", ref fFieldLength, value); }
        }
        int fDecimalSize;
        public int DecimalSize
        {
            get { return fDecimalSize; }
            set { SetPropertyValue<int>("DecimalSize", ref fDecimalSize, value); }
        }
        int fDecimals;
        public int Decimals
        {
            get { return fDecimals; }
            set { SetPropertyValue<int>("Decimals", ref fDecimals, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"QueryTableFieldsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"QueryTableFieldsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
    }

}
