//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class ReportParameters : XPLiteObject
    {
        int fUniqueID;
        [Key(true)]
        public int UniqueID
        {
            get { return fUniqueID; }
            set { SetPropertyValue<int>("UniqueID", ref fUniqueID, value); }
        }
        Reports fReportKey;
        [Association(@"ReportParametersReferencesReports")]
        public Reports ReportKey
        {
            get { return fReportKey; }
            set { SetPropertyValue<Reports>("ReportKey", ref fReportKey, value); }
        }
        string fParameterName;
        [Size(50)]
        public string ParameterName
        {
            get { return fParameterName; }
            set { SetPropertyValue<string>("ParameterName", ref fParameterName, value); }
        }
        string fParameterDesc;
        [Size(254)]
        public string ParameterDesc
        {
            get { return fParameterDesc; }
            set { SetPropertyValue<string>("ParameterDesc", ref fParameterDesc, value); }
        }
        string fParameterType;
        [Size(10)]
        public string ParameterType
        {
            get { return fParameterType; }
            set { SetPropertyValue<string>("ParameterType", ref fParameterType, value); }
        }
        int fParameterOrder;
        public int ParameterOrder
        {
            get { return fParameterOrder; }
            set { SetPropertyValue<int>("ParameterOrder", ref fParameterOrder, value); }
        }
        string fDisplayHeading;
        [Size(512)]
        public string DisplayHeading
        {
            get { return fDisplayHeading; }
            set { SetPropertyValue<string>("DisplayHeading", ref fDisplayHeading, value); }
        }
        string fAllowsNullParameter;
        [Size(1)]
        public string AllowsNullParameter
        {
            get { return fAllowsNullParameter; }
            set { SetPropertyValue<string>("AllowsNullParameter", ref fAllowsNullParameter, value); }
        }
        string fDefaultValue;
        [Size(254)]
        public string DefaultValue
        {
            get { return fDefaultValue; }
            set { SetPropertyValue<string>("DefaultValue", ref fDefaultValue, value); }
        }
        string fRequiredParameter;
        [Size(1)]
        public string RequiredParameter
        {
            get { return fRequiredParameter; }
            set { SetPropertyValue<string>("RequiredParameter", ref fRequiredParameter, value); }
        }
        int fDisplayOrder;
        public int DisplayOrder
        {
            get { return fDisplayOrder; }
            set { SetPropertyValue<int>("DisplayOrder", ref fDisplayOrder, value); }
        }
        string fLookupTableName;
        [Size(50)]
        public string LookupTableName
        {
            get { return fLookupTableName; }
            set { SetPropertyValue<string>("LookupTableName", ref fLookupTableName, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ReportParametersReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ReportParametersReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
    }

}
