//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Reports : XPLiteObject
    {
        int fReportKey;
        [Key(true)]
        public int ReportKey
        {
            get { return fReportKey; }
            set { SetPropertyValue<int>("ReportKey", ref fReportKey, value); }
        }
        string fReportName;
        [Size(80)]
        public string ReportName
        {
            get { return fReportName; }
            set { SetPropertyValue<string>("ReportName", ref fReportName, value); }
        }
        string fDescription;
        [Size(1000)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        int fDisplayOrder;
        public int DisplayOrder
        {
            get { return fDisplayOrder; }
            set { SetPropertyValue<int>("DisplayOrder", ref fDisplayOrder, value); }
        }
        string fReportPath;
        [Size(1000)]
        public string ReportPath
        {
            get { return fReportPath; }
            set { SetPropertyValue<string>("ReportPath", ref fReportPath, value); }
        }
        string fStoredProcedureName;
        [Size(50)]
        public string StoredProcedureName
        {
            get { return fStoredProcedureName; }
            set { SetPropertyValue<string>("StoredProcedureName", ref fStoredProcedureName, value); }
        }
        string fParameterizedReport;
        [Size(1)]
        public string ParameterizedReport
        {
            get { return fParameterizedReport; }
            set { SetPropertyValue<string>("ParameterizedReport", ref fParameterizedReport, value); }
        }
        string fReportBackend;
        [Size(20)]
        public string ReportBackend
        {
            get { return fReportBackend; }
            set { SetPropertyValue<string>("ReportBackend", ref fReportBackend, value); }
        }
        string fSystemReport;
        [Size(1)]
        public string SystemReport
        {
            get { return fSystemReport; }
            set { SetPropertyValue<string>("SystemReport", ref fSystemReport, value); }
        }
        int fAttachToScreenID;
        public int AttachToScreenID
        {
            get { return fAttachToScreenID; }
            set { SetPropertyValue<int>("AttachToScreenID", ref fAttachToScreenID, value); }
        }
        string fImported;
        [Size(1)]
        public string Imported
        {
            get { return fImported; }
            set { SetPropertyValue<string>("Imported", ref fImported, value); }
        }
        int fReportClass;
        public int ReportClass
        {
            get { return fReportClass; }
            set { SetPropertyValue<int>("ReportClass", ref fReportClass, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ReportsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ReportsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
        [Association(@"ReportParametersReferencesReports", typeof(ReportParameters))]
        public XPCollection<ReportParameters> ReportParametersCollection { get { return GetCollection<ReportParameters>("ReportParametersCollection"); } }
        [Association(@"ReportUsersReferencesReports", typeof(ReportUsers))]
        public XPCollection<ReportUsers> ReportUsersCollection { get { return GetCollection<ReportUsers>("ReportUsersCollection"); } }
    }

}
