//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class requisitions : XPLiteObject
    {
        int fn_requisitionid;
        [Key(true)]
        public int n_requisitionid
        {
            get { return fn_requisitionid; }
            set { SetPropertyValue<int>("n_requisitionid", ref fn_requisitionid, value); }
        }
        string frequisitionid;
        [Size(10)]
        public string requisitionid
        {
            get { return frequisitionid; }
            set { SetPropertyValue<string>("requisitionid", ref frequisitionid, value); }
        }
        string fOrigRequisitionID;
        [Size(10)]
        public string OrigRequisitionID
        {
            get { return fOrigRequisitionID; }
            set { SetPropertyValue<string>("OrigRequisitionID", ref fOrigRequisitionID, value); }
        }
        Areas fn_Area;
        [Association(@"requisitionsReferencesAreas")]
        public Areas n_Area
        {
            get { return fn_Area; }
            set { SetPropertyValue<Areas>("n_Area", ref fn_Area, value); }
        }
        MPetUsers fn_approvedby;
        [Association(@"requisitionsReferencesMPetUsers")]
        public MPetUsers n_approvedby
        {
            get { return fn_approvedby; }
            set { SetPropertyValue<MPetUsers>("n_approvedby", ref fn_approvedby, value); }
        }
        MPetUsers fn_BuyerReviewer;
        [Association(@"requisitionsReferencesMPetUsers1")]
        public MPetUsers n_BuyerReviewer
        {
            get { return fn_BuyerReviewer; }
            set { SetPropertyValue<MPetUsers>("n_BuyerReviewer", ref fn_BuyerReviewer, value); }
        }
        CostCodes fn_costcodeid;
        [Association(@"requisitionsReferencesCostCodes")]
        public CostCodes n_costcodeid
        {
            get { return fn_costcodeid; }
            set { SetPropertyValue<CostCodes>("n_costcodeid", ref fn_costcodeid, value); }
        }
        MPetUsers fn_keyer;
        [Association(@"requisitionsReferencesMPetUsers2")]
        public MPetUsers n_keyer
        {
            get { return fn_keyer; }
            set { SetPropertyValue<MPetUsers>("n_keyer", ref fn_keyer, value); }
        }
        purchaseorders fn_purchaseorderid;
        [Association(@"requisitionsReferencespurchaseorders")]
        public purchaseorders n_purchaseorderid
        {
            get { return fn_purchaseorderid; }
            set { SetPropertyValue<purchaseorders>("n_purchaseorderid", ref fn_purchaseorderid, value); }
        }
        MPetUsers fn_requestor;
        [Association(@"requisitionsReferencesMPetUsers6")]
        public MPetUsers n_requestor
        {
            get { return fn_requestor; }
            set { SetPropertyValue<MPetUsers>("n_requestor", ref fn_requestor, value); }
        }
        MPetUsers fn_SuperReviewer;
        [Association(@"requisitionsReferencesMPetUsers8")]
        public MPetUsers n_SuperReviewer
        {
            get { return fn_SuperReviewer; }
            set { SetPropertyValue<MPetUsers>("n_SuperReviewer", ref fn_SuperReviewer, value); }
        }
        MPetUsers fn_StatusBy;
        [Association(@"requisitionsReferencesMPetUsers7")]
        public MPetUsers n_StatusBy
        {
            get { return fn_StatusBy; }
            set { SetPropertyValue<MPetUsers>("n_StatusBy", ref fn_StatusBy, value); }
        }
        DateTime fDateRequired;
        public DateTime DateRequired
        {
            get { return fDateRequired; }
            set { SetPropertyValue<DateTime>("DateRequired", ref fDateRequired, value); }
        }
        DateTime frequestdate;
        public DateTime requestdate
        {
            get { return frequestdate; }
            set { SetPropertyValue<DateTime>("requestdate", ref frequestdate, value); }
        }
        string fb_BuyerReviewed;
        [Size(1)]
        public string b_BuyerReviewed
        {
            get { return fb_BuyerReviewed; }
            set { SetPropertyValue<string>("b_BuyerReviewed", ref fb_BuyerReviewed, value); }
        }
        string fb_SuperReviewed;
        [Size(1)]
        public string b_SuperReviewed
        {
            get { return fb_SuperReviewed; }
            set { SetPropertyValue<string>("b_SuperReviewed", ref fb_SuperReviewed, value); }
        }
        string fb_closed;
        [Size(1)]
        public string b_closed
        {
            get { return fb_closed; }
            set { SetPropertyValue<string>("b_closed", ref fb_closed, value); }
        }
        DateTime fdateclosed;
        public DateTime dateclosed
        {
            get { return fdateclosed; }
            set { SetPropertyValue<DateTime>("dateclosed", ref fdateclosed, value); }
        }
        string fnotes;
        [Size(SizeAttribute.Unlimited)]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        string fb_PriceOnly;
        [Size(1)]
        public string b_PriceOnly
        {
            get { return fb_PriceOnly; }
            set { SetPropertyValue<string>("b_PriceOnly", ref fb_PriceOnly, value); }
        }
        string fStatus;
        [Size(25)]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>("Status", ref fStatus, value); }
        }
        DateTime fStatusDate;
        public DateTime StatusDate
        {
            get { return fStatusDate; }
            set { SetPropertyValue<DateTime>("StatusDate", ref fStatusDate, value); }
        }
        Jobs fn_jobid;
        [Association(@"requisitionsReferencesJobs")]
        public Jobs n_jobid
        {
            get { return fn_jobid; }
            set { SetPropertyValue<Jobs>("n_jobid", ref fn_jobid, value); }
        }
        DateTime fApprovalDate;
        public DateTime ApprovalDate
        {
            get { return fApprovalDate; }
            set { SetPropertyValue<DateTime>("ApprovalDate", ref fApprovalDate, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"requisitionsReferencesMPetUsers3")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"requisitionsReferencesMPetUsers4")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        MPetUsers fn_OriginatorReviewer;
        [Association(@"requisitionsReferencesMPetUsers5")]
        public MPetUsers n_OriginatorReviewer
        {
            get { return fn_OriginatorReviewer; }
            set { SetPropertyValue<MPetUsers>("n_OriginatorReviewer", ref fn_OriginatorReviewer, value); }
        }
        string fb_OriginatorReviewed;
        [Size(1)]
        public string b_OriginatorReviewed
        {
            get { return fb_OriginatorReviewed; }
            set { SetPropertyValue<string>("b_OriginatorReviewed", ref fb_OriginatorReviewed, value); }
        }
        FundSrcCodes fn_FundSrcCodeID;
        [Association(@"requisitionsReferencesFundSrcCodes")]
        public FundSrcCodes n_FundSrcCodeID
        {
            get { return fn_FundSrcCodeID; }
            set { SetPropertyValue<FundSrcCodes>("n_FundSrcCodeID", ref fn_FundSrcCodeID, value); }
        }
        WorkOrderCodes fn_WorkOrderCodeID;
        [Association(@"requisitionsReferencesWorkOrderCodes")]
        public WorkOrderCodes n_WorkOrderCodeID
        {
            get { return fn_WorkOrderCodeID; }
            set { SetPropertyValue<WorkOrderCodes>("n_WorkOrderCodeID", ref fn_WorkOrderCodeID, value); }
        }
        WorkOperations fn_WorkOpID;
        [Association(@"requisitionsReferencesWorkOperations")]
        public WorkOperations n_WorkOpID
        {
            get { return fn_WorkOpID; }
            set { SetPropertyValue<WorkOperations>("n_WorkOpID", ref fn_WorkOpID, value); }
        }
        OrganizationCodes fn_OrganizationCodeID;
        [Association(@"requisitionsReferencesOrganizationCodes")]
        public OrganizationCodes n_OrganizationCodeID
        {
            get { return fn_OrganizationCodeID; }
            set { SetPropertyValue<OrganizationCodes>("n_OrganizationCodeID", ref fn_OrganizationCodeID, value); }
        }
        FundingGroupCodes fn_FundingGroupCodeID;
        [Association(@"requisitionsReferencesFundingGroupCodes")]
        public FundingGroupCodes n_FundingGroupCodeID
        {
            get { return fn_FundingGroupCodeID; }
            set { SetPropertyValue<FundingGroupCodes>("n_FundingGroupCodeID", ref fn_FundingGroupCodeID, value); }
        }
        ControlSections fn_ControlSectionID;
        [Association(@"requisitionsReferencesControlSections")]
        public ControlSections n_ControlSectionID
        {
            get { return fn_ControlSectionID; }
            set { SetPropertyValue<ControlSections>("n_ControlSectionID", ref fn_ControlSectionID, value); }
        }
        EquipmentNumber fn_EquipmentNumberID;
        [Association(@"requisitionsReferencesEquipmentNumber")]
        public EquipmentNumber n_EquipmentNumberID
        {
            get { return fn_EquipmentNumberID; }
            set { SetPropertyValue<EquipmentNumber>("n_EquipmentNumberID", ref fn_EquipmentNumberID, value); }
        }
        string fnotesHistory;
        [Size(SizeAttribute.Unlimited)]
        public string notesHistory
        {
            get { return fnotesHistory; }
            set { SetPropertyValue<string>("notesHistory", ref fnotesHistory, value); }
        }
        Jobsteps fn_jobstepid;
        [Association(@"requisitionsReferencesJobsteps")]
        public Jobsteps n_jobstepid
        {
            get { return fn_jobstepid; }
            set { SetPropertyValue<Jobsteps>("n_jobstepid", ref fn_jobstepid, value); }
        }
        string fb_IsForJob;
        [Size(1)]
        public string b_IsForJob
        {
            get { return fb_IsForJob; }
            set { SetPropertyValue<string>("b_IsForJob", ref fb_IsForJob, value); }
        }
        [Association(@"JobPartsReferencesrequisitions", typeof(JobParts))]
        public XPCollection<JobParts> JobPartsCollection { get { return GetCollection<JobParts>("JobPartsCollection"); } }
        [Association(@"RequisitionAttachmentsReferencesrequisitions", typeof(RequisitionAttachments))]
        public XPCollection<RequisitionAttachments> RequisitionAttachmentsCollection { get { return GetCollection<RequisitionAttachments>("RequisitionAttachmentsCollection"); } }
        [Association(@"requisitionitemsReferencesrequisitions", typeof(requisitionitems))]
        public XPCollection<requisitionitems> requisitionitemsCollection { get { return GetCollection<requisitionitems>("requisitionitemsCollection"); } }
        [Association(@"UsersFlaggedRecordsReferencesrequisitions", typeof(UsersFlaggedRecords))]
        public XPCollection<UsersFlaggedRecords> UsersFlaggedRecordsCollection { get { return GetCollection<UsersFlaggedRecords>("UsersFlaggedRecordsCollection"); } }
        [Association(@"xactionitemsReferencesrequisitions", typeof(xactionitems))]
        public XPCollection<xactionitems> xactionitemsCollection { get { return GetCollection<xactionitems>("xactionitemsCollection"); } }
    }

}
