//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class RequisitionAttachments : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        string fAssignedGuid;
        [Size(36)]
        public string AssignedGuid
        {
            get { return fAssignedGuid; }
            set { SetPropertyValue<string>("AssignedGuid", ref fAssignedGuid, value); }
        }
        requisitions fn_requisitionid;
        [Association(@"RequisitionAttachmentsReferencesrequisitions")]
        public requisitions n_requisitionid
        {
            get { return fn_requisitionid; }
            set { SetPropertyValue<requisitions>("n_requisitionid", ref fn_requisitionid, value); }
        }
        string fDocType;
        [Size(10)]
        public string DocType
        {
            get { return fDocType; }
            set { SetPropertyValue<string>("DocType", ref fDocType, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fLocationOrURL;
        [Size(2304)]
        public string LocationOrURL
        {
            get { return fLocationOrURL; }
            set { SetPropertyValue<string>("LocationOrURL", ref fLocationOrURL, value); }
        }
        string fShortName;
        [Size(20)]
        public string ShortName
        {
            get { return fShortName; }
            set { SetPropertyValue<string>("ShortName", ref fShortName, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"RequisitionAttachmentsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"RequisitionAttachmentsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
    }

}
