//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Shifts : XPLiteObject
    {
        int fn_shiftid;
        [Key(true)]
        public int n_shiftid
        {
            get { return fn_shiftid; }
            set { SetPropertyValue<int>("n_shiftid", ref fn_shiftid, value); }
        }
        string fShiftID;
        [Indexed(Name = @"IX_Shifts", Unique = true)]
        [Size(10)]
        public string ShiftID
        {
            get { return fShiftID; }
            set { SetPropertyValue<string>("ShiftID", ref fShiftID, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        DateTime fStartingTime;
        public DateTime StartingTime
        {
            get { return fStartingTime; }
            set { SetPropertyValue<DateTime>("StartingTime", ref fStartingTime, value); }
        }
        DateTime fEndingTime;
        public DateTime EndingTime
        {
            get { return fEndingTime; }
            set { SetPropertyValue<DateTime>("EndingTime", ref fEndingTime, value); }
        }
        decimal fDiffPct;
        public decimal DiffPct
        {
            get { return fDiffPct; }
            set { SetPropertyValue<decimal>("DiffPct", ref fDiffPct, value); }
        }
        decimal fDiffDollars;
        public decimal DiffDollars
        {
            get { return fDiffDollars; }
            set { SetPropertyValue<decimal>("DiffDollars", ref fDiffDollars, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ShiftsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ShiftsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_modified;
        public DateTime Last_modified
        {
            get { return fLast_modified; }
            set { SetPropertyValue<DateTime>("Last_modified", ref fLast_modified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        [Association(@"IncidentsReferencesShifts", typeof(Incidents))]
        public XPCollection<Incidents> IncidentsCollection { get { return GetCollection<Incidents>("IncidentsCollection"); } }
        [Association(@"JobcrewsReferencesShifts", typeof(Jobcrews))]
        public XPCollection<Jobcrews> JobcrewsCollection { get { return GetCollection<Jobcrews>("JobcrewsCollection"); } }
        [Association(@"JobstepsReferencesShifts", typeof(Jobsteps))]
        public XPCollection<Jobsteps> JobstepsCollection { get { return GetCollection<Jobsteps>("JobstepsCollection"); } }
        [Association(@"ObjectTasksReferencesShifts", typeof(ObjectTasks))]
        public XPCollection<ObjectTasks> ObjectTasksCollection { get { return GetCollection<ObjectTasks>("ObjectTasksCollection"); } }
        [Association(@"TestpointsReferencesShifts", typeof(Testpoints))]
        public XPCollection<Testpoints> TestpointsCollection { get { return GetCollection<Testpoints>("TestpointsCollection"); } }
        [Association(@"time_batch_timesReferencesShifts", typeof(time_batch_times))]
        public XPCollection<time_batch_times> time_batch_timess { get { return GetCollection<time_batch_times>("time_batch_timess"); } }
    }

}
