//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class ShipToAddresses : XPLiteObject
    {
        int fn_ShipToAddressID;
        [Key(true)]
        public int n_ShipToAddressID
        {
            get { return fn_ShipToAddressID; }
            set { SetPropertyValue<int>("n_ShipToAddressID", ref fn_ShipToAddressID, value); }
        }
        string fShipToAddressID;
        [Size(25)]
        public string ShipToAddressID
        {
            get { return fShipToAddressID; }
            set { SetPropertyValue<string>("ShipToAddressID", ref fShipToAddressID, value); }
        }
        string fDescr;
        [Size(254)]
        public string Descr
        {
            get { return fDescr; }
            set { SetPropertyValue<string>("Descr", ref fDescr, value); }
        }
        string fAddress;
        [Size(254)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ShipToAddressesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ShipToAddressesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        [Association(@"purchaseordersReferencesShipToAddresses", typeof(purchaseorders))]
        public XPCollection<purchaseorders> purchaseordersCollection { get { return GetCollection<purchaseorders>("purchaseordersCollection"); } }
    }

}
