//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class ShippingReports : XPLiteObject
    {
        int fn_ShippingRptID;
        [Key(true)]
        public int n_ShippingRptID
        {
            get { return fn_ShippingRptID; }
            set { SetPropertyValue<int>("n_ShippingRptID", ref fn_ShippingRptID, value); }
        }
        string fShippingRptID;
        [Size(10)]
        public string ShippingRptID
        {
            get { return fShippingRptID; }
            set { SetPropertyValue<string>("ShippingRptID", ref fShippingRptID, value); }
        }
        MPetUsers fn_InternalApprover;
        [Association(@"ShippingReportsReferencesMPetUsers")]
        public MPetUsers n_InternalApprover
        {
            get { return fn_InternalApprover; }
            set { SetPropertyValue<MPetUsers>("n_InternalApprover", ref fn_InternalApprover, value); }
        }
        Carriers fn_CarrierID;
        [Association(@"ShippingReportsReferencesCarriers")]
        public Carriers n_CarrierID
        {
            get { return fn_CarrierID; }
            set { SetPropertyValue<Carriers>("n_CarrierID", ref fn_CarrierID, value); }
        }
        purchaseorders fn_PONumber;
        [Association(@"ShippingReportsReferencespurchaseorders")]
        public purchaseorders n_PONumber
        {
            get { return fn_PONumber; }
            set { SetPropertyValue<purchaseorders>("n_PONumber", ref fn_PONumber, value); }
        }
        string fB_Canceled;
        [Size(1)]
        public string B_Canceled
        {
            get { return fB_Canceled; }
            set { SetPropertyValue<string>("B_Canceled", ref fB_Canceled, value); }
        }
        string fConfirmationMethod;
        [Size(24)]
        public string ConfirmationMethod
        {
            get { return fConfirmationMethod; }
            set { SetPropertyValue<string>("ConfirmationMethod", ref fConfirmationMethod, value); }
        }
        string fInstructions;
        [Size(SizeAttribute.Unlimited)]
        public string Instructions
        {
            get { return fInstructions; }
            set { SetPropertyValue<string>("Instructions", ref fInstructions, value); }
        }
        string fMiscExplanation;
        [Size(254)]
        public string MiscExplanation
        {
            get { return fMiscExplanation; }
            set { SetPropertyValue<string>("MiscExplanation", ref fMiscExplanation, value); }
        }
        FreightTerms fn_FreightTermsID;
        [Association(@"ShippingReportsReferencesFreightTerms")]
        public FreightTerms n_FreightTermsID
        {
            get { return fn_FreightTermsID; }
            set { SetPropertyValue<FreightTerms>("n_FreightTermsID", ref fn_FreightTermsID, value); }
        }
        string fPONumber;
        [Size(24)]
        public string PONumber
        {
            get { return fPONumber; }
            set { SetPropertyValue<string>("PONumber", ref fPONumber, value); }
        }
        string fAuthorizationNum;
        [Size(24)]
        public string AuthorizationNum
        {
            get { return fAuthorizationNum; }
            set { SetPropertyValue<string>("AuthorizationNum", ref fAuthorizationNum, value); }
        }
        string fVendorAppover;
        [Size(24)]
        public string VendorAppover
        {
            get { return fVendorAppover; }
            set { SetPropertyValue<string>("VendorAppover", ref fVendorAppover, value); }
        }
        string fShipTo;
        [Size(254)]
        public string ShipTo
        {
            get { return fShipTo; }
            set { SetPropertyValue<string>("ShipTo", ref fShipTo, value); }
        }
        DateTime fShipDate;
        public DateTime ShipDate
        {
            get { return fShipDate; }
            set { SetPropertyValue<DateTime>("ShipDate", ref fShipDate, value); }
        }
        DateTime fConfirmationDate;
        public DateTime ConfirmationDate
        {
            get { return fConfirmationDate; }
            set { SetPropertyValue<DateTime>("ConfirmationDate", ref fConfirmationDate, value); }
        }
        string fConfirmedWith;
        [Size(24)]
        public string ConfirmedWith
        {
            get { return fConfirmedWith; }
            set { SetPropertyValue<string>("ConfirmedWith", ref fConfirmedWith, value); }
        }
        ShippingReturnReasons fn_ReturnReasonID;
        [Association(@"ShippingReportsReferencesShippingReturnReasons")]
        public ShippingReturnReasons n_ReturnReasonID
        {
            get { return fn_ReturnReasonID; }
            set { SetPropertyValue<ShippingReturnReasons>("n_ReturnReasonID", ref fn_ReturnReasonID, value); }
        }
        string fOriginator;
        [Size(254)]
        public string Originator
        {
            get { return fOriginator; }
            set { SetPropertyValue<string>("Originator", ref fOriginator, value); }
        }
        string fHistoryAuditTrail;
        [Size(SizeAttribute.Unlimited)]
        public string HistoryAuditTrail
        {
            get { return fHistoryAuditTrail; }
            set { SetPropertyValue<string>("HistoryAuditTrail", ref fHistoryAuditTrail, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"ShippingReportsReferencesMPetUsers1")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"ShippingReportsReferencesMPetUsers2")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        string fnotesHistory;
        [Size(SizeAttribute.Unlimited)]
        public string notesHistory
        {
            get { return fnotesHistory; }
            set { SetPropertyValue<string>("notesHistory", ref fnotesHistory, value); }
        }
        [Association(@"ShippingRptPartsReferencesShippingReports", typeof(ShippingRptParts))]
        public XPCollection<ShippingRptParts> ShippingRptPartsCollection { get { return GetCollection<ShippingRptParts>("ShippingRptPartsCollection"); } }
        [Association(@"UsersFlaggedRecordsReferencesShippingReports", typeof(UsersFlaggedRecords))]
        public XPCollection<UsersFlaggedRecords> UsersFlaggedRecordsCollection { get { return GetCollection<UsersFlaggedRecords>("UsersFlaggedRecordsCollection"); } }
    }

}
