//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class skills : XPLiteObject
    {
        int fn_skillid;
        [Key(true)]
        public int n_skillid
        {
            get { return fn_skillid; }
            set { SetPropertyValue<int>("n_skillid", ref fn_skillid, value); }
        }
        string fskillid;
        [Size(20)]
        public string skillid
        {
            get { return fskillid; }
            set { SetPropertyValue<string>("skillid", ref fskillid, value); }
        }
        string fdescription;
        [Size(254)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"skillsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"skillsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime flast_modified;
        public DateTime last_modified
        {
            get { return flast_modified; }
            set { SetPropertyValue<DateTime>("last_modified", ref flast_modified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        [Association(@"JobcrewsReferencesskills", typeof(Jobcrews))]
        public XPCollection<Jobcrews> JobcrewsCollection { get { return GetCollection<Jobcrews>("JobcrewsCollection"); } }
        [Association(@"personskillsReferencesskills", typeof(personskills))]
        public XPCollection<personskills> personskillsCollection { get { return GetCollection<personskills>("personskillsCollection"); } }
        [Association(@"taskcrewsReferencesskills", typeof(taskcrews))]
        public XPCollection<taskcrews> taskcrewsCollection { get { return GetCollection<taskcrews>("taskcrewsCollection"); } }
    }

}
