//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class tasksteps : XPLiteObject
    {
        int fn_taskstepid;
        [Key(true)]
        public int n_taskstepid
        {
            get { return fn_taskstepid; }
            set { SetPropertyValue<int>("n_taskstepid", ref fn_taskstepid, value); }
        }
        Tasks fn_taskid;
        [Association(@"taskstepsReferencesTasks")]
        public Tasks n_taskid
        {
            get { return fn_taskid; }
            set { SetPropertyValue<Tasks>("n_taskid", ref fn_taskid, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        int fstepnumber;
        public int stepnumber
        {
            get { return fstepnumber; }
            set { SetPropertyValue<int>("stepnumber", ref fstepnumber, value); }
        }
        int ffollowstep;
        public int followstep
        {
            get { return ffollowstep; }
            set { SetPropertyValue<int>("followstep", ref ffollowstep, value); }
        }
        int fconcurwithstep;
        public int concurwithstep
        {
            get { return fconcurwithstep; }
            set { SetPropertyValue<int>("concurwithstep", ref fconcurwithstep, value); }
        }
        decimal festdowntime;
        public decimal estdowntime
        {
            get { return festdowntime; }
            set { SetPropertyValue<decimal>("estdowntime", ref festdowntime, value); }
        }
        decimal festlen;
        public decimal estlen
        {
            get { return festlen; }
            set { SetPropertyValue<decimal>("estlen", ref festlen, value); }
        }
        int fpending_delete;
        public int pending_delete
        {
            get { return fpending_delete; }
            set { SetPropertyValue<int>("pending_delete", ref fpending_delete, value); }
        }
        string fProceduresText;
        [Size(SizeAttribute.Unlimited)]
        public string ProceduresText
        {
            get { return fProceduresText; }
            set { SetPropertyValue<string>("ProceduresText", ref fProceduresText, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"taskstepsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"taskstepsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
        [Association(@"taskcrewsReferencestasksteps", typeof(taskcrews))]
        public XPCollection<taskcrews> taskcrewsCollection { get { return GetCollection<taskcrews>("taskcrewsCollection"); } }
        [Association(@"TaskEquipmentReferencestasksteps", typeof(TaskEquipment))]
        public XPCollection<TaskEquipment> TaskEquipments { get { return GetCollection<TaskEquipment>("TaskEquipments"); } }
        [Association(@"taskpartsReferencestasksteps", typeof(taskparts))]
        public XPCollection<taskparts> taskpartsCollection { get { return GetCollection<taskparts>("taskpartsCollection"); } }
    }

}
