//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class TemplateFieldGroups : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        string fGroupID;
        [Indexed(Name = @"IX_FLRGroupName", Unique = true)]
        [Size(20)]
        public string GroupID
        {
            get { return fGroupID; }
            set { SetPropertyValue<string>("GroupID", ref fGroupID, value); }
        }
        string fGroupIDDesc;
        [Size(50)]
        public string GroupIDDesc
        {
            get { return fGroupIDDesc; }
            set { SetPropertyValue<string>("GroupIDDesc", ref fGroupIDDesc, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"TemplateFieldGroupsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifedBy;
        [Association(@"TemplateFieldGroupsReferencesMPetUsers1")]
        public MPetUsers ModifedBy
        {
            get { return fModifedBy; }
            set { SetPropertyValue<MPetUsers>("ModifedBy", ref fModifedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        [Association(@"TemplateFieldGroupFieldsReferencesTemplateFieldGroups", typeof(TemplateFieldGroupFields))]
        public XPCollection<TemplateFieldGroupFields> TemplateFieldGroupFieldsCollection { get { return GetCollection<TemplateFieldGroupFields>("TemplateFieldGroupFieldsCollection"); } }
    }

}
