//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class TemplateFields : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        UserRightTemplates fTemplateID;
        [Association(@"TemplateFieldsReferencesUserRightTemplates")]
        public UserRightTemplates TemplateID
        {
            get { return fTemplateID; }
            set { SetPropertyValue<UserRightTemplates>("TemplateID", ref fTemplateID, value); }
        }
        string fTableName;
        public string TableName
        {
            get { return fTableName; }
            set { SetPropertyValue<string>("TableName", ref fTableName, value); }
        }
        string fFieldName;
        public string FieldName
        {
            get { return fFieldName; }
            set { SetPropertyValue<string>("FieldName", ref fFieldName, value); }
        }
        int fCanView;
        public int CanView
        {
            get { return fCanView; }
            set { SetPropertyValue<int>("CanView", ref fCanView, value); }
        }
        int fCanAdd;
        public int CanAdd
        {
            get { return fCanAdd; }
            set { SetPropertyValue<int>("CanAdd", ref fCanAdd, value); }
        }
        int fCanEdit;
        public int CanEdit
        {
            get { return fCanEdit; }
            set { SetPropertyValue<int>("CanEdit", ref fCanEdit, value); }
        }
        int fCanDelete;
        public int CanDelete
        {
            get { return fCanDelete; }
            set { SetPropertyValue<int>("CanDelete", ref fCanDelete, value); }
        }
        int fCanPrint;
        public int CanPrint
        {
            get { return fCanPrint; }
            set { SetPropertyValue<int>("CanPrint", ref fCanPrint, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"TemplateFieldsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"TemplateFieldsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
    }

}
