//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class Testpoints : XPLiteObject
    {
        int fn_TestpointID;
        [Key(true)]
        public int n_TestpointID
        {
            get { return fn_TestpointID; }
            set { SetPropertyValue<int>("n_TestpointID", ref fn_TestpointID, value); }
        }
        string ftestpointid;
        [Size(10)]
        public string testpointid
        {
            get { return ftestpointid; }
            set { SetPropertyValue<string>("testpointid", ref ftestpointid, value); }
        }
        string fdescr;
        [Size(254)]
        public string descr
        {
            get { return fdescr; }
            set { SetPropertyValue<string>("descr", ref fdescr, value); }
        }
        string fcomment;
        [Size(254)]
        public string comment
        {
            get { return fcomment; }
            set { SetPropertyValue<string>("comment", ref fcomment, value); }
        }
        MaintenanceObjects fn_objectid;
        [Association(@"TestpointsReferencesMaintenanceObjects")]
        public MaintenanceObjects n_objectid
        {
            get { return fn_objectid; }
            set { SetPropertyValue<MaintenanceObjects>("n_objectid", ref fn_objectid, value); }
        }
        Jobs fn_jobid;
        [Association(@"TestpointsReferencesJobs")]
        public Jobs n_jobid
        {
            get { return fn_jobid; }
            set { SetPropertyValue<Jobs>("n_jobid", ref fn_jobid, value); }
        }
        Jobs fn_stdJobID;
        [Association(@"TestpointsReferencesJobs1")]
        public Jobs n_stdJobID
        {
            get { return fn_stdJobID; }
            set { SetPropertyValue<Jobs>("n_stdJobID", ref fn_stdJobID, value); }
        }
        JobReasons fn_jobreasonid;
        [Association(@"TestpointsReferencesJobReasons")]
        public JobReasons n_jobreasonid
        {
            get { return fn_jobreasonid; }
            set { SetPropertyValue<JobReasons>("n_jobreasonid", ref fn_jobreasonid, value); }
        }
        WorkOperations fn_worktypeid;
        [Association(@"TestpointsReferencesWorkOperations")]
        public WorkOperations n_worktypeid
        {
            get { return fn_worktypeid; }
            set { SetPropertyValue<WorkOperations>("n_worktypeid", ref fn_worktypeid, value); }
        }
        MPetUsers fn_ownerid;
        [Association(@"TestpointsReferencesMPetUsers2")]
        public MPetUsers n_ownerid
        {
            get { return fn_ownerid; }
            set { SetPropertyValue<MPetUsers>("n_ownerid", ref fn_ownerid, value); }
        }
        groups fn_groupid;
        [Association(@"TestpointsReferencesgroups")]
        public groups n_groupid
        {
            get { return fn_groupid; }
            set { SetPropertyValue<groups>("n_groupid", ref fn_groupid, value); }
        }
        Shifts fn_shiftid;
        [Association(@"TestpointsReferencesShifts")]
        public Shifts n_shiftid
        {
            get { return fn_shiftid; }
            set { SetPropertyValue<Shifts>("n_shiftid", ref fn_shiftid, value); }
        }
        MPetUsers fn_supervisorid;
        [Association(@"TestpointsReferencesMPetUsers3")]
        public MPetUsers n_supervisorid
        {
            get { return fn_supervisorid; }
            set { SetPropertyValue<MPetUsers>("n_supervisorid", ref fn_supervisorid, value); }
        }
        laborclasses fn_LaborClass;
        [Association(@"TestpointsReferenceslaborclasses")]
        public laborclasses n_LaborClass
        {
            get { return fn_LaborClass; }
            set { SetPropertyValue<laborclasses>("n_LaborClass", ref fn_LaborClass, value); }
        }
        Tasks fn_tasknum;
        [Association(@"TestpointsReferencesTasks")]
        public Tasks n_tasknum
        {
            get { return fn_tasknum; }
            set { SetPropertyValue<Tasks>("n_tasknum", ref fn_tasknum, value); }
        }
        string freadingtype;
        [Size(20)]
        public string readingtype
        {
            get { return freadingtype; }
            set { SetPropertyValue<string>("readingtype", ref freadingtype, value); }
        }
        int fdecimal_places;
        public int decimal_places
        {
            get { return fdecimal_places; }
            set { SetPropertyValue<int>("decimal_places", ref fdecimal_places, value); }
        }
        decimal flowerlimit;
        public decimal lowerlimit
        {
            get { return flowerlimit; }
            set { SetPropertyValue<decimal>("lowerlimit", ref flowerlimit, value); }
        }
        decimal fupperlimit;
        public decimal upperlimit
        {
            get { return fupperlimit; }
            set { SetPropertyValue<decimal>("upperlimit", ref fupperlimit, value); }
        }
        decimal fmaxdecay;
        public decimal maxdecay
        {
            get { return fmaxdecay; }
            set { SetPropertyValue<decimal>("maxdecay", ref fmaxdecay, value); }
        }
        int finterval;
        public int interval
        {
            get { return finterval; }
            set { SetPropertyValue<int>("interval", ref finterval, value); }
        }
        int fexpectedlife;
        public int expectedlife
        {
            get { return fexpectedlife; }
            set { SetPropertyValue<int>("expectedlife", ref fexpectedlife, value); }
        }
        int freturnwithin;
        public int returnwithin
        {
            get { return freturnwithin; }
            set { SetPropertyValue<int>("returnwithin", ref freturnwithin, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"TestpointsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"TestpointsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
        [Association(@"TestpointReadingsReferencesTestpoints", typeof(TestpointReadings))]
        public XPCollection<TestpointReadings> TestpointReadingsCollection { get { return GetCollection<TestpointReadings>("TestpointReadingsCollection"); } }
    }

}
