//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class time_batch_times : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        int fn_itemid;
        public int n_itemid
        {
            get { return fn_itemid; }
            set { SetPropertyValue<int>("n_itemid", ref fn_itemid, value); }
        }
        time_batches fn_time_batchid;
        [Association(@"time_batch_timesReferencestime_batches")]
        public time_batches n_time_batchid
        {
            get { return fn_time_batchid; }
            set { SetPropertyValue<time_batches>("n_time_batchid", ref fn_time_batchid, value); }
        }
        MPetUsers fn_personid;
        [Association(@"time_batch_timesReferencesMPetUsers2")]
        public MPetUsers n_personid
        {
            get { return fn_personid; }
            set { SetPropertyValue<MPetUsers>("n_personid", ref fn_personid, value); }
        }
        string fTypeCode;
        [Size(30)]
        public string TypeCode
        {
            get { return fTypeCode; }
            set { SetPropertyValue<string>("TypeCode", ref fTypeCode, value); }
        }
        MPetUsers fn_ta_for;
        [Association(@"time_batch_timesReferencesMPetUsers3")]
        public MPetUsers n_ta_for
        {
            get { return fn_ta_for; }
            set { SetPropertyValue<MPetUsers>("n_ta_for", ref fn_ta_for, value); }
        }
        positioncodes fn_ta_positionid;
        [Association(@"time_batch_timesReferencespositioncodes")]
        public positioncodes n_ta_positionid
        {
            get { return fn_ta_positionid; }
            set { SetPropertyValue<positioncodes>("n_ta_positionid", ref fn_ta_positionid, value); }
        }
        Jobcrews fn_jobcrewid;
        [Association(@"time_batch_timesReferencesJobcrews")]
        public Jobcrews n_jobcrewid
        {
            get { return fn_jobcrewid; }
            set { SetPropertyValue<Jobcrews>("n_jobcrewid", ref fn_jobcrewid, value); }
        }
        decimal fhours_worked;
        public decimal hours_worked
        {
            get { return fhours_worked; }
            set { SetPropertyValue<decimal>("hours_worked", ref fhours_worked, value); }
        }
        Paycodes fn_PayCodeID;
        [Association(@"time_batch_timesReferencesPaycodes")]
        public Paycodes n_PayCodeID
        {
            get { return fn_PayCodeID; }
            set { SetPropertyValue<Paycodes>("n_PayCodeID", ref fn_PayCodeID, value); }
        }
        payreasons fn_PayReasonID;
        [Association(@"time_batch_timesReferencespayreasons")]
        public payreasons n_PayReasonID
        {
            get { return fn_PayReasonID; }
            set { SetPropertyValue<payreasons>("n_PayReasonID", ref fn_PayReasonID, value); }
        }
        Shifts fn_ShiftID;
        [Association(@"time_batch_timesReferencesShifts")]
        public Shifts n_ShiftID
        {
            get { return fn_ShiftID; }
            set { SetPropertyValue<Shifts>("n_ShiftID", ref fn_ShiftID, value); }
        }
        DateTime fWorkDate;
        public DateTime WorkDate
        {
            get { return fWorkDate; }
            set { SetPropertyValue<DateTime>("WorkDate", ref fWorkDate, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"time_batch_timesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"time_batch_timesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
    }

}
