//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class UserRightTemplates : XPLiteObject
    {
        int fTemplateTypeID;
        [Key(true)]
        public int TemplateTypeID
        {
            get { return fTemplateTypeID; }
            set { SetPropertyValue<int>("TemplateTypeID", ref fTemplateTypeID, value); }
        }
        string fTemplateID;
        [Size(20)]
        public string TemplateID
        {
            get { return fTemplateID; }
            set { SetPropertyValue<string>("TemplateID", ref fTemplateID, value); }
        }
        string fTemplateDescription;
        [Size(40)]
        public string TemplateDescription
        {
            get { return fTemplateDescription; }
            set { SetPropertyValue<string>("TemplateDescription", ref fTemplateDescription, value); }
        }
        int fActive;
        public int Active
        {
            get { return fActive; }
            set { SetPropertyValue<int>("Active", ref fActive, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"UserRightTemplatesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"UserRightTemplatesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        [Association(@"TemplateBaseTablesReferencesUserRightTemplates", typeof(TemplateBaseTables))]
        public XPCollection<TemplateBaseTables> TemplateBaseTablesCollection { get { return GetCollection<TemplateBaseTables>("TemplateBaseTablesCollection"); } }
        [Association(@"TemplateFieldsReferencesUserRightTemplates", typeof(TemplateFields))]
        public XPCollection<TemplateFields> TemplateFieldsCollection { get { return GetCollection<TemplateFields>("TemplateFieldsCollection"); } }
        [Association(@"TemplateFormRightsReferencesUserRightTemplates", typeof(TemplateFormRights))]
        public XPCollection<TemplateFormRights> TemplateFormRightsCollection { get { return GetCollection<TemplateFormRights>("TemplateFormRightsCollection"); } }
        [Association(@"TemplateTasksReferencesUserRightTemplates", typeof(TemplateTasks))]
        public XPCollection<TemplateTasks> TemplateTasksCollection { get { return GetCollection<TemplateTasks>("TemplateTasksCollection"); } }
        [Association(@"UserTemplatesReferencesUserRightTemplates", typeof(UserTemplates))]
        public XPCollection<UserTemplates> UserTemplatesCollection { get { return GetCollection<UserTemplates>("UserTemplatesCollection"); } }
    }

}
