//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class UsersFlaggedRecords : XPLiteObject
    {
        int fRecordID;
        [Key(true)]
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>("RecordID", ref fRecordID, value); }
        }
        int fUserID;
        public int UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<int>("UserID", ref fUserID, value); }
        }
        requisitions fn_requisitionid;
        [Association(@"UsersFlaggedRecordsReferencesrequisitions")]
        public requisitions n_requisitionid
        {
            get { return fn_requisitionid; }
            set { SetPropertyValue<requisitions>("n_requisitionid", ref fn_requisitionid, value); }
        }
        purchaseorders fn_purchaseorderid;
        [Association(@"UsersFlaggedRecordsReferencespurchaseorders")]
        public purchaseorders n_purchaseorderid
        {
            get { return fn_purchaseorderid; }
            set { SetPropertyValue<purchaseorders>("n_purchaseorderid", ref fn_purchaseorderid, value); }
        }
        StoresIssues fn_StoresIssueID;
        [Association(@"UsersFlaggedRecordsReferencesStoresIssues")]
        public StoresIssues n_StoresIssueID
        {
            get { return fn_StoresIssueID; }
            set { SetPropertyValue<StoresIssues>("n_StoresIssueID", ref fn_StoresIssueID, value); }
        }
        GriefLogs fn_GriefLogID;
        [Association(@"UsersFlaggedRecordsReferencesGriefLogs")]
        public GriefLogs n_GriefLogID
        {
            get { return fn_GriefLogID; }
            set { SetPropertyValue<GriefLogs>("n_GriefLogID", ref fn_GriefLogID, value); }
        }
        ShippingReports fn_ShippingRptID;
        [Association(@"UsersFlaggedRecordsReferencesShippingReports")]
        public ShippingReports n_ShippingRptID
        {
            get { return fn_ShippingRptID; }
            set { SetPropertyValue<ShippingReports>("n_ShippingRptID", ref fn_ShippingRptID, value); }
        }
        Jobs fn_Jobid;
        [Association(@"UsersFlaggedRecordsReferencesJobs")]
        public Jobs n_Jobid
        {
            get { return fn_Jobid; }
            set { SetPropertyValue<Jobs>("n_Jobid", ref fn_Jobid, value); }
        }
        Jobsteps fn_jobstepid;
        [Association(@"UsersFlaggedRecordsReferencesJobsteps")]
        public Jobsteps n_jobstepid
        {
            get { return fn_jobstepid; }
            set { SetPropertyValue<Jobsteps>("n_jobstepid", ref fn_jobstepid, value); }
        }
        MaintenanceObjects fn_objectid;
        [Association(@"UsersFlaggedRecordsReferencesMaintenanceObjects")]
        public MaintenanceObjects n_objectid
        {
            get { return fn_objectid; }
            set { SetPropertyValue<MaintenanceObjects>("n_objectid", ref fn_objectid, value); }
        }
        MPetUsers fn_personid;
        [Association(@"UsersFlaggedRecordsReferencesMPetUsers2")]
        public MPetUsers n_personid
        {
            get { return fn_personid; }
            set { SetPropertyValue<MPetUsers>("n_personid", ref fn_personid, value); }
        }
        time_batches fn_time_batchid;
        [Association(@"UsersFlaggedRecordsReferencestime_batches")]
        public time_batches n_time_batchid
        {
            get { return fn_time_batchid; }
            set { SetPropertyValue<time_batches>("n_time_batchid", ref fn_time_batchid, value); }
        }
        Incidents fn_incidentid;
        [Association(@"UsersFlaggedRecordsReferencesIncidents")]
        public Incidents n_incidentid
        {
            get { return fn_incidentid; }
            set { SetPropertyValue<Incidents>("n_incidentid", ref fn_incidentid, value); }
        }
        ProjectDiary fn_ProjectDiaryID;
        [Association(@"UsersFlaggedRecordsReferencesProjectDiary")]
        public ProjectDiary n_ProjectDiaryID
        {
            get { return fn_ProjectDiaryID; }
            set { SetPropertyValue<ProjectDiary>("n_ProjectDiaryID", ref fn_ProjectDiaryID, value); }
        }
        Masterparts fn_masterpartid;
        [Association(@"UsersFlaggedRecordsReferencesMasterparts")]
        public Masterparts n_masterpartid
        {
            get { return fn_masterpartid; }
            set { SetPropertyValue<Masterparts>("n_masterpartid", ref fn_masterpartid, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"UsersFlaggedRecordsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"UsersFlaggedRecordsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
    }

}
