//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class VendorParts : XPLiteObject
    {
        int fn_VendorPartID;
        [Key(true)]
        public int n_VendorPartID
        {
            get { return fn_VendorPartID; }
            set { SetPropertyValue<int>("n_VendorPartID", ref fn_VendorPartID, value); }
        }
        string fVendorPartID;
        [Size(50)]
        public string VendorPartID
        {
            get { return fVendorPartID; }
            set { SetPropertyValue<string>("VendorPartID", ref fVendorPartID, value); }
        }
        string fVendorPartDescription;
        [Size(254)]
        public string VendorPartDescription
        {
            get { return fVendorPartDescription; }
            set { SetPropertyValue<string>("VendorPartDescription", ref fVendorPartDescription, value); }
        }
        Vendors fn_vendorid;
        [Association(@"VendorPartsReferencesVendors")]
        public Vendors n_vendorid
        {
            get { return fn_vendorid; }
            set { SetPropertyValue<Vendors>("n_vendorid", ref fn_vendorid, value); }
        }
        Masterparts fn_masterpartid;
        [Association(@"VendorPartsReferencesMasterparts")]
        public Masterparts n_masterpartid
        {
            get { return fn_masterpartid; }
            set { SetPropertyValue<Masterparts>("n_masterpartid", ref fn_masterpartid, value); }
        }
        Manufacturers fn_mfgid;
        [Association(@"VendorPartsReferencesManufacturers")]
        public Manufacturers n_mfgid
        {
            get { return fn_mfgid; }
            set { SetPropertyValue<Manufacturers>("n_mfgid", ref fn_mfgid, value); }
        }
        MfgParts fn_mfgpartid;
        [Association(@"VendorPartsReferencesMfgParts")]
        public MfgParts n_mfgpartid
        {
            get { return fn_mfgpartid; }
            set { SetPropertyValue<MfgParts>("n_mfgpartid", ref fn_mfgpartid, value); }
        }
        int fleadtime;
        public int leadtime
        {
            get { return fleadtime; }
            set { SetPropertyValue<int>("leadtime", ref fleadtime, value); }
        }
        int funitsperpkg;
        public int unitsperpkg
        {
            get { return funitsperpkg; }
            set { SetPropertyValue<int>("unitsperpkg", ref funitsperpkg, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"VendorPartsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"VendorPartsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLast_Modified;
        public DateTime Last_Modified
        {
            get { return fLast_Modified; }
            set { SetPropertyValue<DateTime>("Last_Modified", ref fLast_Modified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        [Association(@"requisitionitemsReferencesVendorParts", typeof(requisitionitems))]
        public XPCollection<requisitionitems> requisitionitemsCollection { get { return GetCollection<requisitionitems>("requisitionitemsCollection"); } }
    }

}
