//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class WorkOrderCodes : XPLiteObject
    {
        int fn_WorkOrderCodeID;
        [Key(true)]
        public int n_WorkOrderCodeID
        {
            get { return fn_WorkOrderCodeID; }
            set { SetPropertyValue<int>("n_WorkOrderCodeID", ref fn_WorkOrderCodeID, value); }
        }
        string fWorkOrderCodeID;
        [Size(30)]
        public string WorkOrderCodeID
        {
            get { return fWorkOrderCodeID; }
            set { SetPropertyValue<string>("WorkOrderCodeID", ref fWorkOrderCodeID, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"WorkOrderCodesReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"WorkOrderCodesReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fLastModified;
        public DateTime LastModified
        {
            get { return fLastModified; }
            set { SetPropertyValue<DateTime>("LastModified", ref fLastModified, value); }
        }
        [Association(@"FieldDataCollectionReferencesWorkOrderCodes", typeof(FieldDataCollection))]
        public XPCollection<FieldDataCollection> FieldDataCollections { get { return GetCollection<FieldDataCollection>("FieldDataCollections"); } }
        [Association(@"FundSrcCodeLinksReferencesWorkOrderCodes", typeof(FundSrcCodeLinks))]
        public XPCollection<FundSrcCodeLinks> FundSrcCodeLinksCollection { get { return GetCollection<FundSrcCodeLinks>("FundSrcCodeLinksCollection"); } }
        [Association(@"IncidentsReferencesWorkOrderCodes", typeof(Incidents))]
        public XPCollection<Incidents> IncidentsCollection { get { return GetCollection<Incidents>("IncidentsCollection"); } }
        [Association(@"JobPartsReferencesWorkOrderCodes", typeof(JobParts))]
        public XPCollection<JobParts> JobPartsCollection { get { return GetCollection<JobParts>("JobPartsCollection"); } }
        [Association(@"JobsReferencesWorkOrderCodes", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection { get { return GetCollection<Jobs>("JobsCollection"); } }
        [Association(@"JobstepsReferencesWorkOrderCodes", typeof(Jobsteps))]
        public XPCollection<Jobsteps> JobstepsCollection { get { return GetCollection<Jobsteps>("JobstepsCollection"); } }
        [Association(@"MaintenanceObjectsReferencesWorkOrderCodes", typeof(MaintenanceObjects))]
        public XPCollection<MaintenanceObjects> MaintenanceObjectsCollection { get { return GetCollection<MaintenanceObjects>("MaintenanceObjectsCollection"); } }
        [Association(@"requisitionsReferencesWorkOrderCodes", typeof(requisitions))]
        public XPCollection<requisitions> requisitionsCollection { get { return GetCollection<requisitions>("requisitionsCollection"); } }
        [Association(@"StoresIssuesReferencesWorkOrderCodes", typeof(StoresIssues))]
        public XPCollection<StoresIssues> StoresIssuesCollection { get { return GetCollection<StoresIssues>("StoresIssuesCollection"); } }
        [Association(@"time_batch_itemsReferencesWorkOrderCodes", typeof(time_batch_items))]
        public XPCollection<time_batch_items> time_batch_itemss { get { return GetCollection<time_batch_items>("time_batch_itemss"); } }
    }

}
