//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace MpetDataModel.cs
{

    public partial class WorkEvents : XPLiteObject
    {
        int fn_workeventid;
        [Key(true)]
        public int n_workeventid
        {
            get { return fn_workeventid; }
            set { SetPropertyValue<int>("n_workeventid", ref fn_workeventid, value); }
        }
        string fworkeventid;
        [Size(10)]
        public string workeventid
        {
            get { return fworkeventid; }
            set { SetPropertyValue<string>("workeventid", ref fworkeventid, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fnotes;
        [Size(254)]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        string feventgroup;
        [Size(24)]
        public string eventgroup
        {
            get { return feventgroup; }
            set { SetPropertyValue<string>("eventgroup", ref feventgroup, value); }
        }
        Tasks ftasknum;
        [Association(@"WorkEventsReferencesTasks")]
        public Tasks tasknum
        {
            get { return ftasknum; }
            set { SetPropertyValue<Tasks>("tasknum", ref ftasknum, value); }
        }
        MaintenanceObjects fn_objectid;
        [Association(@"WorkEventsReferencesMaintenanceObjects")]
        public MaintenanceObjects n_objectid
        {
            get { return fn_objectid; }
            set { SetPropertyValue<MaintenanceObjects>("n_objectid", ref fn_objectid, value); }
        }
        MPetUsers fn_ownerid;
        [Association(@"WorkEventsReferencesMPetUsers2")]
        public MPetUsers n_ownerid
        {
            get { return fn_ownerid; }
            set { SetPropertyValue<MPetUsers>("n_ownerid", ref fn_ownerid, value); }
        }
        WorkOperations fn_worktypeid;
        [Association(@"WorkEventsReferencesWorkOperations")]
        public WorkOperations n_worktypeid
        {
            get { return fn_worktypeid; }
            set { SetPropertyValue<WorkOperations>("n_worktypeid", ref fn_worktypeid, value); }
        }
        string fb_inactive;
        [Size(1)]
        public string b_inactive
        {
            get { return fb_inactive; }
            set { SetPropertyValue<string>("b_inactive", ref fb_inactive, value); }
        }
        DateTime fcur_begin_ts;
        public DateTime cur_begin_ts
        {
            get { return fcur_begin_ts; }
            set { SetPropertyValue<DateTime>("cur_begin_ts", ref fcur_begin_ts, value); }
        }
        DateTime fcur_end_ts;
        public DateTime cur_end_ts
        {
            get { return fcur_end_ts; }
            set { SetPropertyValue<DateTime>("cur_end_ts", ref fcur_end_ts, value); }
        }
        DateTime forg_begin_ts;
        public DateTime org_begin_ts
        {
            get { return forg_begin_ts; }
            set { SetPropertyValue<DateTime>("org_begin_ts", ref forg_begin_ts, value); }
        }
        DateTime forg_end_ts;
        public DateTime org_end_ts
        {
            get { return forg_end_ts; }
            set { SetPropertyValue<DateTime>("org_end_ts", ref forg_end_ts, value); }
        }
        shutdowns fPMShutdown_ID;
        [Association(@"WorkEventsReferencesshutdowns")]
        public shutdowns PMShutdown_ID
        {
            get { return fPMShutdown_ID; }
            set { SetPropertyValue<shutdowns>("PMShutdown_ID", ref fPMShutdown_ID, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        MPetUsers fCreatedBy;
        [Association(@"WorkEventsReferencesMPetUsers")]
        public MPetUsers CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<MPetUsers>("CreatedBy", ref fCreatedBy, value); }
        }
        MPetUsers fModifiedBy;
        [Association(@"WorkEventsReferencesMPetUsers1")]
        public MPetUsers ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<MPetUsers>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime flast_modified;
        public DateTime last_modified
        {
            get { return flast_modified; }
            set { SetPropertyValue<DateTime>("last_modified", ref flast_modified, value); }
        }
        string fb_IsActive;
        [Size(1)]
        public string b_IsActive
        {
            get { return fb_IsActive; }
            set { SetPropertyValue<string>("b_IsActive", ref fb_IsActive, value); }
        }
        [Association(@"JobsReferencesWorkEvents", typeof(Jobs))]
        public XPCollection<Jobs> JobsCollection { get { return GetCollection<Jobs>("JobsCollection"); } }
    }

}
